### ISSUE TITLE
offset fails when variable has attributes

### ISSUE THREAD

**Issue by mattansb** [glmmTMB/glmmTMB#773] opened 2021-11-24 14:32 UTC
Offset seems to fail when variable has attributes:

``` r
library(datawizard)
library(glmmTMB)

mtcarsz <- standardize(mtcars)

# glmmTMB(mpg ~ 1, offset = hp, data = mtcarsz) # same
glmmTMB(mpg ~ offset(hp), data = mtcarsz)
#> Problem with these data entries:
#> offset 
#>     11
#> Error in MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg, : Only numeric matrices, vectors, arrays, factors, lists or length-1-characters can be interfaced
```

Vars are numeric:

``` r
mtcarsz[c("mpg", "hp")] |> sapply(class)
#>       mpg        hp 
#> "numeric" "numeric"
```

But they have attributes:

``` r
mtcarsz[c("mpg", "hp")] |> str()
#> 'data.frame':    32 obs. of  2 variables:
#>  $ mpg: num  0.151 0.151 0.45 0.217 -0.231 ...
#>   ..- attr(*, "center")= num 20.1
#>   ..- attr(*, "scale")= num 6.03
#>   ..- attr(*, "robust")= logi FALSE
#>  $ hp : num  -0.535 -0.535 -0.783 -0.535 0.413 ...
#>   ..- attr(*, "center")= num 147
#>   ..- attr(*, "scale")= num 68.6
#>   ..- attr(*, "robust")= logi FALSE
```

If we strip the attributes, it works:

``` r
mtcarsz <- mtcarsz |> 
  transform(mpg = c(mpg),
            hp = c(hp))
glmmTMB(mpg ~ offset(hp), data = mtcarsz)
#> Formula:          mpg ~ offset(hp)
#> Data: mtcarsz
#>       AIC       BIC    logLik  df.resid 
#> 134.35949 137.29096 -65.17974        30 
#> 
#> Number of obs: 32
#> 
#> Dispersion estimate for gaussian family (sigma^2): 3.44 
#> 
#> Fixed Effects:
#> 
#> Conditional model:
#> (Intercept)  
#>   3.069e-07
```

<sup>Created on 2021-11-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bbolker** [comment] 2021-11-24 16:31
Hmmm, I wonder if this should be an issue for TMB instead.  The proximal problem is [here](https://github.com/kaskr/adcomp/blob/master/TMB/R/TMB.R#L193):


```r
  ok <- function(x)(is.matrix(x)|is.vector(x)|is.array(x))&(is.numeric(x)|is.logical(x))
```

I think the problem is with `is.vector()`:

> For any ‘mode’, it will return ‘FALSE’ if ‘x’ has any attributes except names.

Also, those `|` should probably be `||`.

Honestly, I don't know why this test couldn't just be reduced to `is.numeric(x) || is.logical(x)`; what R data structure exists where those would be true and the structure *wouldn't* be a vector, matrix, or array ... ???

We could deal with this by applying `c()` to offset (this would also drop dimensions, but I can't think of any use case where the offset would be a matrix or array ... ???), but it might be better to handle it upstream.  @kaskr ... ??

**Comment by kaskr** [comment] 2021-11-25 13:09
> what R data structure exists where those would be true and the structure wouldn't be a vector, matrix, or array ... ???

I can't answer that but that doesn't prove such structures don't exist...

> but it might be better to handle it upstream.

There's currently nothing you can do with the attributes on the C++ side, I prefer the current behavior (an error message) for now.

**Comment by bbolker** [comment] 2021-11-25 18:32
OK. It just feels to me like that this was originally coded with a misunderstanding of the details of what `is.vector()` does (it's very confusing, IMO).  I will set up a branch with code to strip the attributes from offsets (I notice this is already done for the `size` vector ...)

**Comment by bbolker** [comment] 2021-11-25 18:42
oops, pushed the fix directly to the master branch by accident ...

**Closed** 2021-11-25 18:42 UTC

**Comment by mattansb** [comment] 2021-11-28 06:46
Thanks!

**Comment by mmaechler** [comment] 2021-11-29 15:04
Coming late:  I do agree with  @bbolker  that both 
- the use of `is.vector(.)` is conceptually wrong there
- you should (for efficiency only here, but also "out of principle") use  `&&` and `||` instead of the length-1 versions
