### ISSUE TITLE
object 'nbinom2' not found

### ISSUE THREAD

**Issue by benjaminwnelson** [glmmTMB/glmmTMB#664] opened 2021-01-28 20:46 UTC
When I try to run a zero-inflation model, I am unable to set family to nbinom2. Any ideas? 

Error in glmmTMB::glmmTMB(dv ~ iv *  : 
  object 'nbinom2' not found

**Comment by bbolker** [comment] 2021-01-28 21:01
could we please have a reproducible example?

e.g. this works for me (with development version of glmmTMB, but I'd be surprised if it worked differently in earlier versions):

```r
library(glmmTMB)
glmmTMB(SiblingNegotiation ~ FoodTreatment*SexParent, family=nbinom2, ziformula=~1, data =Owls)
```

I can get it to break if I add a `nbinom2` variable in my global environment:

```r
nbinom2 <- FALSE
## rerun model above
## Error: $ operator is invalid for atomic vectors
```

which suggests we might try harder to evaluate the `family` argument in the package namespace, but I don't see an obvious way to get your error.

**Comment by benjaminwnelson** [comment] 2021-01-28 21:26
Unfortunately, the data is not deidentified, so I am unable to share a reproducible example. I'm wondering if another package is overwriting this argument

**Comment by bbolker** [comment] 2021-01-28 21:35
Reproducible examples do not require the original data; they require that you are able to set something up that has a similar structure that will allow me/us to replicate the problem locally. See e.g. http://tinyurl.com/reproducible-000 .  Suggested steps to move forward:

- replicate the problem in the cleanest possible environment (i.e. as few packages as possible: e.g. save your data set to a `.RData` file, then read it back in a clean environment); get `sessionInfo()` or `devtools::session_info()` output
- `find("nbinom2")` to see where `nbinom2` is actually being found (although masking is not really consistent with your error message ...)

**Comment by benjaminwnelson** [comment] 2021-01-28 21:39
Thank you for this information! I removed some packages that were not required for analyses and the error went away. I assume the error was caused by a conflict of packages. Thank you so much!

**Comment by bbolker** [comment] 2021-01-28 21:41
If you can figure out which package it was, it would still be interesting to know which one ... so we can protect against this in the future ...

**Comment by benjaminwnelson** [comment] 2021-01-28 21:43
It was one of the following.

library(r2mlm)
library(merTools)
library(DHARMa)
library(texreg)
library(effects)
library(magrittr)
library(foreign)

**Comment by bbolker** [comment] 2021-01-28 21:48
Still can't get it to break locally.

```r
library(glmmTMB) ## load first to ensure masking
library(r2mlm)
library(merTools)
library(DHARMa)
library(texreg)
library(effects)
library(magrittr)
library(foreign)

## extra pkgs found via sos::findFn("nbinom2")
library(insight)
library(performance)
library(sjstats)

g1 <- glmmTMB(SiblingNegotiation ~ FoodTreatment*SexParent,
        family=nbinom2, ziformula=~1, data =Owls)

## this has an nbinom2 object, but it only causes a warning/
## suboptimal behaviour, not an error
library(glmmfields)

## re-run
update(g1)
```

**Comment by benjaminwnelson** [comment] 2021-01-28 22:59
Hmm, I'm not sure why it worked for me after removing those packages.

**Comment by bbolker** [comment] 2021-02-13 20:13
Closing due to non-reproducibility, happy to reopen in the future.

**Closed by bbolker** 2021-02-13 20:13 UTC
