### ISSUE TITLE
Bug (?) when running glmmTMB from within a user-defined function

### ISSUE THREAD

**Issue by koenvanbenthem** [glmmTMB/glmmTMB#209] opened 2017-01-26 16:20 UTC
Hi all,

when trying to repeat an example from 'ecological statistics, chapter 13', I stumbled upon the following unexpected behaviour when trying to run glmmTMB from within a function. 

When running the following code (minimal working example, here with the sleepstudy data):
```
rm(list=ls())
library(glmmTMB)

data(sleepstudy, package="lme4")
sleepstudy <- transform(sleepstudy, DaysFac = factor(Days))

 Function definition
fitFun <- function(dat){
  glmmTMB(Reaction ~ Days + (1|Subject), data=dat)
}
fitFun(sleepstudy)
```
I get the following error:
```
Error in is.data.frame(data) : object 'dat' not found
```
(I do not get this error when using other packages, e.g. lme4)

When I define dat in the global environment as well, the problem disappears. I have been able to trace it back to the following lines of code (file:glmmTMB.R):
1. line 504: in the function `glmmTMB`, the function `mkTMBStruc` is called within `eval.parent()`
2. line 53-55: within the function `mkTMBStruc` the function `getXReTrms` is called, again within `eval.parent()`
3. line 145: in `getXReTrms` the code `terms(eval.parent(mf))` is run. This is where the 'error' is generated.

I tried to understand the actual problem, but I'm afraid that my understanding of environments is too little. Any thoughts on this?

*Edit: I was able to replicate this behaviour on a second machine.*

**Comment by bbolker** [comment] 2017-02-02 18:17
Thoughts on this problem: this sort of thing always seems to be a pain, and I wish I had a complete/clear way of resolving it.  I *think* the problem is that I thought `eval.parent()` statements would nest (so that it would look like `mf` was being evaluated in the parent environment of the original glmmTMB call), but now it seems I was wrong.

I'm going to try evaluating in the environment of the formula, making sure that the *enclosing environment* of the formula is the glmmTMB call's parent environment ...

**Comment by mmaechler** [comment] 2017-02-03 21:47
I don't have time right now to delve.  But yes, AFAIU,  you *must* always take the environment of the formula and nothing else... that's why they (formula's environments) were introduced. .... There's *the* article on the topic by Thomas Lumley - for about 14 years soon:
https://developer.r-project.org/nonstandard-eval.pdf

**Comment by bbolker** [comment] 2017-02-13 23:18
I think this is fixed on the `bbolker_eval` branch now ... still running tests.  I wish there were a standard series of "try to run models within progressively weirder environments" torture tests ...

**Comment by bbolker** [comment] 2017-02-15 04:13
Here's a harder case:

``` 
   formFun <- function() {
        return(Reaction ~ Days + (1|Subject))
    }
    fitFun <- function(f,dat){
        glmmTMB(f, data=dat)
    }
    f0 <- glmmTMB(Reaction ~ Days + (1|Subject), data=sleepstudy)
    f1 <- fitFun(formFun(),sleepstudy)
```

Does anyone have good ideas about how to make this work?  

Even in the main `glmmTMB` frame, `fr <- eval(mf,envir=parent.frame())` works but `fr <- eval(mf,envir=environment(formula),enclos=parent.frame())`; I would have thought this work?

Even if we can find the right incantation involving the environment of the formula and the parent frame, we still need to pass the parent frame down several levels to `getXReTrms` ...

**Comment by mmaechler** [comment] 2017-02-15 08:24
The gold standard should be lm()   Would the analogue of the above work for lm() ?
If yes, we have to strive to do better
If no,  we should not IMO.
(I'm vacationing currently, so don't ....)

**Comment by mebrooks** [comment] 2017-02-16 16:32
lm() can handle the analog. However, I don't think this bug is bad enough to prevent us from submitting to CRAN. Right?

**Comment by mebrooks** [comment] 2017-02-18 19:43
It looks like this bug is fixed. Should I submit to CRAN now?

**Comment by mmaechler** [comment] 2017-02-18 20:26
Back from vacation.  Yes, even the presence of the bug should not have stopped a CRAN submission.

**Comment by bbolker** [comment] 2017-02-20 15:10
`lm()` can handle the analogue of the example I posted above, but only because it uses `eval.parent()` to evaluate the model frame call in the top level of the `lm()` function; that is, it doesn't try to pass the call down to a lower-level function.  I "solved" the problem by setting the environment of the formulas to `parent.frame()`: this seems to work, and I think we can live with it until someone comes up with an example that doesn't work/breaks our current code, but I'm not entirely happy with it. It makes me nervous to overwrite the formula's environment; what if a user has tried to use the formula's environment in some particular way? (For those users, we could document this behaviour somewhere ...)  What I would have preferred is somehow to set the enclosing environment of the formula's environment to the parent frame, but I'm not sure how to do that/whether it would work ...

**Comment by mmaechler** [comment] 2017-02-20 19:02
you didn't show by which commt you "solved" the problem (can still be added by editing your comment).
Yes, indeed,  the formula's environment has to be the way to work with.
We could "look" at  `environment(formula)` before changing it, and only set to `parent.frame()` if the environment looks "unhelpful" ... which of course needs a helpful definition of  "unhelpful".

**Comment by bbolker** [comment] 2017-02-21 01:54
It was de4d55c3ffb888fa8af677b8bdafccea106b3aab

I think you're right that the problem is coming up with a 'helpful
definition of "unhelpful"' .  The only thing I can think of is testing the
environment of the formula to see whether it contains the data or not, but
I'd like to keep it simple if we can, so for now (since we have something
that's fairly simple and passes our tests) I think we should just wait
until someone succeeds in breaking it.

If someone were feeling really ambitious they could poke around in the
`lme4` tests and see if they could find an example that broke glmmTMB.

**Comment by bbolker** [comment] 2017-02-23 01:40
Martin commented on the commit:

> I don't believe the unconditional `environment(formula) <- parent.frame()` can be correct in generality.

(Reproducing here because I will have an easier time finding it.) I don't disagree, but I can't think of something simple and better.  What I think I would like to do is to set the enclosing environment of the formula's environment equal to the parent frame, but I don't know how to do that (without using `parent.env<-`, which is effectively deprecated in the documentation ("The replacement function `parent.env<-` is extremely dangerous as it can be used to destructively change environments in ways that violate assumptions made by the internal C code.  It may be removed in the near future.") (However, this warning about removal in the "near future" was added in 2001 ... https://github.com/wch/r-source/commit/81b5ce25f3b800a53c889e2248c555482c9aaa63 )

**Comment by mebrooks** [comment] 2017-03-02 14:54
It seems that this bug still exists for the Poisson distribution.
```
library(glmmTMB)

mod = glmmTMB(count~1, Salamanders, family="nbinom2")
sims1 = lapply(simulate(mod, nsim=2, seed=111), 
               function(count){ 
                 cbind(count, Salamanders[,c('site', 'mined', 'spp')])
               })

#These work
lapply(sims1, function(x){glmmTMB(count~1, x)})
lapply(sims1, function(x){glmmTMB(count~1, x, family="gaussian")})
lapply(sims1, function(x){glmmTMB(count~1, x, family="nbinom2")})
lapply(sims1, function(x){glmmTMB(count~1, x, family=nbinom2)})
lapply(sims1, function(x){glmmTMB(count~1, x, family=nbinom2(link="log"))})
lapply(sims1, function(x){glmmTMB(count~1, x, 
	family=list(family="nbinom2", link="log"))})

#These don't work `Error in is.data.frame(data) : object 'x' not found`
lapply(sims1, function(x){glmmTMB(count~1, x, family="poisson")})
lapply(sims1, function(x){glmmTMB(count~1, x, family=poisson(link="log"))})
lapply(sims1, function(x){glmmTMB(count~1, x, 
	family=list(family="poisson", link="log"))})

#sanity check
glmmTMB(count~1, sims1[[1]], family="poisson")
```

**Comment by mebrooks** [comment] 2017-03-02 14:58
Here's an example more closely related to Koen's original example. The Gaussian on works, but the Poisson one give the error.
```
library(glmmTMB)

fitFun <- function(dat){
  glmmTMB(count ~ 1, data=dat, family="poisson" )
}
fitFun(Salamanders)

fitFun2 <- function(dat){
  glmmTMB(count ~ 1, data=dat, family="gaussian" )
}
fitFun2(Salamanders)
```

**Comment by mmaechler** [comment] 2017-03-02 17:22
Yes, this (whole "diversion") makes much sense.... and I think (but w/o time today to check my thinking) is even **_the_** best explanation of why we have problem.

For solution, I'd find it much nicer (more efficient, more cautious, too), to replace
```
  dispformula <- ~0
```
by
```
  dispformula[] <- ~0
```

(note the subtlety: Assigning  `x[] <- val`   typically keeps all attributes `x`, but replaces the content by `val`.

If I had time I'd be happy for once to do a pull request..

**Comment by mebrooks** [comment] 2017-03-03 12:35
Thanks for finding the source of the problem @koenvanbenthem and for suggesting the solution @mmaechler !

**Closed** 2017-03-03 12:34 UTC
Labels: bug
