### ISSUE TITLE
Zero inflated beta Error in eval(family$initialize)

### ISSUE THREAD

**Issue by MfMartel** [glmmTMB/glmmTMB#507] opened 2019-07-19 13:43 UTC
Hi,

I have a dataset of proportion ranging from 0 to 1, with lots of 0 and 1 data points, which is completely expected from my experiment. From what I've read, it seems that I could use glmmTMB with a zero-one inflated beta to fit the distribution the best (with a mixed model). According to this previous post **https://github.com/glmmTMB/glmmTMB/issues/355** citing **https://github.com/glmmTMB/glmmTMB/pull/497** the inflated option seems now possible. But I have an error, even though I'm using the last version of the package (directly downloaded from Github). It is the same error as the one here **https://github.com/glmmTMB/glmmTMB/issues/355**.

> Error in eval(family$initialize) : y values must be 0 <= y < 1

Here **https://github.com/glmmTMB/glmmTMB/pull/497** you wrote something about the problem, but I'm not sure what to do with the "we are defining our own beta_family()

> this is a preliminary stab at allowing zero-inflation for otherwise-positive (Gamma, beta) response models. Right now it seems to work OK in a simple beta example. To make it work for Gamma we will have to work around the $initialize() component of the standard Gamma model, which fails unless 0<y<1. (this wasn't too hard for beta because we are defining our own beta_family())

My fit was:

`fit_zibeta <- glmmTMB(index_attraction ~ Type * Condition + (1|participant), data=DataCleaned, ziformula= ~1, family=beta_family())`

My distribution looks like that:

![Distrib](https://user-images.githubusercontent.com/41061008/61538852-894f2000-aa3a-11e9-88ba-fdeaf94ff70e.JPG)

Any idea what I could do wrong?
Many thanks!

**Comment by bbolker** [comment] 2019-07-19 13:48
I only implemented zero-inflated, not zero-one-inflated, betas. Note that the error message you're getting is subtly different from the one cited in #355. Your error is `0 <= y < 1` rather than `0 < y < 1`.  Zero-one inflation will take a fair amount more effort to implement, as we would need a separate model for the proportion of ones (we already have a proportion-of-zeros model built into glmmTMB).  Since it looks like the ones component in your data set is fairly small and doesn't represent a distinct mode, maybe you could do the usual fudge and shrink the ones values slightly, to 0.99 (or (1+max(y[y<1])/2 , or whatever approach makes sense in your context) ?

**Comment by MfMartel** [comment] 2019-07-20 12:17
I see, thanks! I guess I can yes. It should not change much.

In the experiment, we applied 3 tactile stimuli on the skin that can be either in 2 or 3 different localisations and asked participants to localise them. We calculated the perceived position of stimulus 2 as a percentage of the distance between number 1 and 3. This is what I'm trying to model.
In some of our trials, the 1 and 2 are at the same position, so the value will be 0; or 2 and 3 are at the same position, so the value will be 1.

**Comment by MfMartel** [comment] 2019-07-20 13:59
I changed the 1 into 0.999 and I don't have this error anymore. So I'm wondering, does this mean that if I change all my 0 to 0.001 I could just go with a non-inflated model and this would lead to the same results? Or do I need the inflated model to indicate that the distribution is unbalanced with a lot of values close to 0?

Also, now running my inflated model I get errors about gradient length and NA. 

`fit_zibeta <- glmmTMB(index_attraction ~ Type * Condition + (1|participant) + (1|StimPattern), data=DataCleaned,  ziformula= ~1, family=beta_family())`

> Error in (function (start, objective, gradient = NULL, hessian = NULL,  : 
  la fonction de gradient doit renvoyer un vecteur numérique de longueur 14
In addition: Warning message:
In (function (start, objective, gradient = NULL, hessian = NULL,  :
  NA/NaN function evaluation
Timing stopped at: 0.72 0.09 0.83

Following this (https://mran.microsoft.com/snapshot/2017-11-04/web/packages/glmmTMB/vignettes/troubleshooting.html), I do not have the gradient issue anymore when removing all the random effects

`fit_zibeta <- glmmTMB(index_attraction ~ Type * Condition, data=DataCleaned, ziformula= ~1,  family=beta_family())`

But I do need to be able to fit models with and without so I can compare them and see if it actually fits. Is there a way to do that?

As for the NA error, I have no idea and I have the error no matter my model... I read  [#504](https://github.com/glmmTMB/glmmTMB/issues/504) but couldn't figure out something out from it. [Here](https://mran.microsoft.com/snapshot/2017-11-04/web/packages/glmmTMB/vignettes/troubleshooting.html), it says that

> If you see this error, check that the response variable meets the assumptions of the specified distribution.

Since my values are between 0 and 0.99, I don't know what I could do more...

I hope this is the right place for these questions... Not sure whether it is more a stats or glmmTMB related question...
Thanks!

**Comment by bbolker** [comment] 2019-07-21 00:53
- Your approach to modeling the data sounds reasonable - except that it seems funny to treat `StimPattern` as a random effect.
- Squishing 0 values to 0.001 rather than fitting a hurdle model would change the results - zero-inflation seems more reasonable given your big pile of values at zero.
- The warning message is probably harmless.
- If you could provide your data (post it here or somewhere, or send e-mail if they're sensitive) that would be useful: that error where the gradient function returns the wrong number of values is something we have seen, that's usually related to unstable models, but I don't know that we've ever had an example in our hands so that we could track down exactly what's happening.

**Comment by MfMartel** [comment] 2019-07-21 08:34
Ok, thanks!

I put `StimPattern` as a random effect because we have several possibilities for stimulation localisations for each type of trials (none all the stimPattern are the same for each condition, but some are in common between several conditions). You'll see in the data enclosed. 

[CleanedData_ForDebugging.zip](https://github.com/glmmTMB/glmmTMB/files/3414426/CleanedData_ForDebugging.zip)

Usually, when I run classical models with lmer or glmer, I build one model with all the random effects I think are important, and I compare it with a model without each of them to assess whether they matter or not. I was following the same logic here.

**Comment by MfMartel** [comment] 2019-09-05 14:18
Hi,

Any update on the gradient error?
Thank you!

**Comment by bbolker** [comment] 2019-09-10 15:31
I wasn't able to replicate it - it ran for me with the current development version (master branch):

```
> fit_zibeta_r
Formula:          
index_attraction ~ Type * Condition + (1 | participant) + (1 |  
    StimPattern)
Zero inflation:                    ~1
Data: DataCleaned_v2
      AIC       BIC    logLik  df.resid 
 7352.696  7446.986 -3662.348      6203 
Random-effects (co)variances:

Conditional model:
 Groups      Name        Std.Dev.
 participant (Intercept) 0.3567  
 StimPattern (Intercept) 0.1258  

Number of obs: 6217 / Conditional model: participant, 20; StimPattern, 10

Overdispersion parameter for beta family (): 2.83 

Fixed Effects:

Conditional model:
     (Intercept)             TypeR        Condition2        Condition3  
        -0.62832           0.65157           0.06603          -0.09095  
      Condition4        Condition5  TypeR:Condition2  TypeR:Condition3  
         0.25116           0.30537           0.07658          -0.04792  
TypeR:Condition4  TypeR:Condition5  
        -0.09374           0.23017  

Zero-inflation model:
(Intercept)  
     -0.549  
```

One further suggestion to help with the fitting: try setting your upper 'censored' values to a *smaller* value - right now they're set to 0.999999, you might try 0.999.  It is tempting to think that by setting the values as close to the boundary as possible you will be making the smallest change to the data and getting the best answer, but what this does is to make the values extreme outliers on a logit scale (the model isn't actually technically fitted with logit-transformed data, but some of the effects will be similar).

![qlogis_dens](https://user-images.githubusercontent.com/78918/64627427-a1e61180-d3bd-11e9-9d7e-752b1461b5aa.png)

**Comment by MfMartel** [comment] 2019-09-17 13:23
Thanks for the tip about changing the values back to 0.999.

It still doesn't run on my computer though (Rstudio: 1.2.1335; R: 3.6.1/Win10)
When you say 

> it ran for me with the current development version (master branch)

You mean, that I have to install the last available version, right? 
I used `devtools::install_github("glmmTMB/glmmTMB/glmmTMB")` as indicated on the documentation.
I have the version 0.2.3.

Or am I doing something wrong ?

thx!

**Comment by pv272** [comment] 2019-09-23 10:36
I am trying to model the proportion of time (calculated based on a total duration of observation) spent nest building. Proportions are between 0 and 1, with many zeros and no 1 values in the dataset. I am therefore trying to specify a zero-inflated Beta model, which shall be possible

`
Nest_FS_1 <- glmmTMB(Nest~ Treatment + (1|Colony) + (1|AnimalID),data = CS_FS_Nest, ziformula=~1, family=beta_family())
`
However I get the following error message, 

`
Error in eval(family$initialize) : y values must be 0 < y < 1
`

This suggest that values should be higher than zero, seemingly suggesting that zero-inflation canot be modelled in Beta model

**Comment by bbolker** [comment] 2019-09-23 13:04
@MfMartel : yes, I ran exactly this code. (`sessionInfo()` output below).

```
L <- load("CleanedData_ForDebugging.RData")
library(glmmTMB)
fit_zibeta <- glmmTMB(index_attraction ~ Type * Condition,
                      data=DataCleaned_v2,
                      ziformula= ~1, family=beta_family())

t1 <- system.time(
    fit_zibeta_r <- glmmTMB(index_attraction ~ Type * Condition + (1|participant) +
                          (1|StimPattern),
                      data=DataCleaned_v2, ziformula= ~1,
                      family=beta_family()
                      ##verbose=TRUE
                      )
)
##    user  system elapsed 
## 176.456   0.988 184.578 

library(ggplot2); theme_set(theme_bw())
summary(DataCleaned_v2)

ggplot(DataCleaned_v2,aes(Condition,index_attraction,colour=Type))+
    geom_jitter()

ggplot(DataCleaned_v2,aes(qlogis(index_attraction)))+
    geom_density(fill="gray")
ggsave("qlogis_dens.png")

sessionInfo()
## R Under development (unstable) (2019-08-28 r77082)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 16.04.6 LTS

## Matrix products: default
## BLAS:   /usr/local/lib/R/lib/libRblas.so
## LAPACK: /usr/local/lib/R/lib/libRlapack.so

## locale:
##  [1] LC_CTYPE=en_CA.UTF8       LC_NUMERIC=C             
##  [3] LC_TIME=en_CA.UTF8        LC_COLLATE=en_CA.UTF8    
##  [5] LC_MONETARY=en_CA.UTF8    LC_MESSAGES=en_CA.UTF8   
##  [7] LC_PAPER=en_CA.UTF8       LC_NAME=C                
##  [9] LC_ADDRESS=C              LC_TELEPHONE=C           
## [11] LC_MEASUREMENT=en_CA.UTF8 LC_IDENTIFICATION=C      

## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     

## other attached packages:
## [1] glmmTMB_0.2.3

## loaded via a namespace (and not attached):
##  [1] minqa_1.2.4      MASS_7.3-51.4    compiler_3.7.0   Matrix_1.2-17   
##  [5] tools_3.7.0      TMB_1.7.15       Rcpp_1.0.2       splines_3.7.0   
##  [9] nlme_3.1-141     grid_3.7.0       nloptr_1.2.1     boot_1.3-23     
## [13] lme4_1.1-21.9002 lattice_0.20-38 
```

**Comment by bbolker** [comment] 2019-09-23 13:15
@pv272 : in order to fit a zero-inflated binomial model, you need to install the development version of glmmTMB (`devtools::install_github("glmmTMB/glmmTMB/glmmTMB")`; you'll need compilers etc. (there's a little bit more information about installing the dev version in the [README file](https://github.com/glmmTMB/glmmTMB/blob/master/README.md).

**Comment by bbolker** [comment] 2019-10-12 00:10
So far this is not reproducible on my end.  Can any other developers reproduce it ... ?

**Comment by mebrooks** [comment] 2019-11-12 15:02
The code [from the discussion above](https://github.com/glmmTMB/glmmTMB/issues/507#issuecomment-534089578) runs fine on my computer. So I can't reproduce the convergence problem.

**Comment by Franelizabethgalvez** [comment] 2020-01-17 16:14
Hi, I am trying to model the photosynthetic response (fvfm) that takes values from 0 to 0.7, I am using the beta distribution since I have zero inflation, and I consider a dispersion model because my values move away from the average as they pass days, but when running this model: beta7<-glmmTMB(fvfm~Temperature*dia+(1|ID), zi=~1, disp=~dia, data=ds, family=beta_family(link="logit"))
and  this appears : Error in eval(family$initialize) : y values must be 0 < y < 1
I add to all the values of my response variable 0.001, so I no longer have zero inflation and the model works.
This is correct?? or is there any way to run without adding 0.001??
Thank you!!
Regards Fran

**Comment by bbolker** [comment] 2020-01-17 18:48
See the [comment above](https://github.com/glmmTMB/glmmTMB/issues/507#issuecomment-534093854); if you want to fit a zero-inflated beta distribution, for now you need the development version (see the [README file](https://github.com/glmmTMB/glmmTMB/blob/master/README.md) for installation instructions.  (We hope to submit this version to CRAN very soon - but it could take a week or more, so you might prefer to work with the development version immediately.)

**Comment by bbolker** [comment] 2020-01-17 18:49
Closing this issue as we don't have a reproducible problem any more (happy to re-open if appropriate).

**Closed by bbolker** 2020-01-17 18:49 UTC

**Comment by Franelizabethgalvez** [comment] 2020-01-17 19:07
Thanks for answering !!
I have tried to install the version that indicates them in github, but this appears to me: 
> devtools::install_github("glmmTMB/glmmTMB/glmmTMB")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘pkgbuild’

> remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
Error in loadNamespace(name) : there is no package called ‘remotes’

I have the glmmTMB version: 0.2.3 ....

**Comment by bbolker** [comment] 2020-01-17 20:08
I think you might not have a complete installation of the development tools.  Try `install.packages(
"remotes")` first, **but**: because you are installing from source, and `glmmTMB` has code written in C++, you will also need compilers installed.  I don't know why your `devtools` call didn't work.  (You could try `install.packages("pkgbuild")`.)

**Comment by Franelizabethgalvez** [comment] 2020-01-17 20:38
Thanks for the help!! something worked, but apparently something is wrong: compilation ??
it appears that:
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/glmmTMB’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/glmmTMB’
Error: Failed to install 'glmmTMB' from GitHub:
  (converted from warning) installation of package ‘/var/folders/sz/4z778rqj4px0hkdbjk808bh00000gn/T//RtmpEsc5yU/file5cd3d59246f/glmmTMB_1.0.0.tar.gz’ had non-zero exit status
> 

below the details:
> remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
Downloading GitHub repo glmmTMB/glmmTMB@master
These packages have more recent versions available.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: TMB  (1.7.15 -> 1.7.16) [CRAN]
5: Rcpp (1.0.2  -> 1.0.3 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
TMB  (1.7.15 -> 1.7.16) [CRAN]
Rcpp (1.0.2  -> 1.0.3 ) [CRAN]
Installing 2 packages: TMB, Rcpp
trying URL 'https://CRAN.R-project.org/bin/macosx/el-capitan/contrib/3.5/TMB_1.7.16.tgz'
Content type 'application/x-gzip' length 1200352 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://CRAN.R-project.org/bin/macosx/el-capitan/contrib/3.5/Rcpp_1.0.3.tgz'
Content type 'application/x-gzip' length 3068683 bytes (2.9 MB)
==================================================
downloaded 2.9 MB


The downloaded binary packages are in
	/var/folders/sz/4z778rqj4px0hkdbjk808bh00000gn/T//RtmpEsc5yU/downloaded_packages
Running `R CMD build`...
* checking for file ‘/private/var/folders/sz/4z778rqj4px0hkdbjk808bh00000gn/T/RtmpEsc5yU/remotes5cd1338e569/glmmTMB-glmmTMB-6284f45/glmmTMB/DESCRIPTION’ ... OK
* preparing ‘glmmTMB’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Removed empty directory ‘glmmTMB/inst/misc’
* looking to see if a ‘data/datalist’ file should be added
* building ‘glmmTMB_1.0.0.tar.gz’
* installing *source* package ‘glmmTMB’ ...
** libs
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/TMB/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppEigen/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c glmmTMB.cpp -o glmmTMB.o
clang: error: unsupported option '-fopenmp'
make: *** [glmmTMB.o] Error 1
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/glmmTMB’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/glmmTMB’
Error: Failed to install 'glmmTMB' from GitHub:
  (converted from warning) installation of package ‘/var/folders/sz/4z778rqj4px0hkdbjk808bh00000gn/T//RtmpEsc5yU/file5cd3d59246f/glmmTMB_1.0.0.tar.gz’ had non-zero exit status
>

**Comment by bbolker** [comment] 2020-01-17 20:42
OK, thanks for your patience.  This is something we're working on right now. Try `remotes::install_github("glmmTMB/glmmTMB/glmmTMB@conditional_openmp")` ...

**Comment by Franelizabethgalvez** [comment] 2020-01-17 21:28
remotes::install_github("glmmTMB/glmmTMB/glmmTMB@conditional_openmp"): IT WORKED!! yuju
the model runs with beta considering a zeros inflation model!!
beta2 <-glmmTMB (fvfm ~ Temperature + day + (1 | ID), zi = ~ day, data = ds, beta_family (link = "logit")).
I feel tremendously grateful for your help, really thank you very much !! 
regards, Fran

**Comment by bbolker** [comment] 2020-01-17 21:29
Glad to hear it, this is another data point for us (i.e., more evidence that our latest fix is working).

**Comment by Franelizabethgalvez** [comment] 2020-01-20 21:29
Dear: suggestions for making fitting, model selection and inference from glmmTMB. I have ACItab (bbmle) and tab_model (sjPlot). I was reviewing this page: https://bbolker.github.io/mixedmodels-misc/ecostats_chap.html,  but I do not know if it applies to generalized mixed models or it is only for linear models, thank you!! and excuse me so much query ... Greetings

**Comment by bbolker** [comment] 2020-01-20 22:22
@Franelizabethgalvez  : your question is probably more appropriate for `r-sig-mixed-models@r-project.org` ... see ["where to ask questions"](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions).

Pretty much everything we've developed for model selection and inference is detailed in the `model_evaluation` vignette ([source](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/vignettes/model_evaluation.Rnw), [PDF](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/inst/doc/model_evaluation.pdf)), see especially section 2.5.

**Comment by Franelizabethgalvez** [comment] 2020-01-20 22:30
Thank you very much for the prompt response and recommendations!!, grateful, regards

**Comment by Franelizabethgalvez** [comment] 2020-02-23 03:53
Hi, excuse me, but I have had a doubt and an adjustment of this model: b8<-glmmTMB(fvfm~Temperature*dia+(1|ID), zi=~0, disp=~dia, data=dc, family=beta_family(link="logit")), of two predictors: Temperature (factor, with three levels) and time (days) as numeric. But since I have been suggested to consider time as a categorical variable (17 levels) when running this model and any model with interaction gives me this Warning message:
In fitTMB(TMBStruc) :
  Model convergence problem; false convergence (8). See vignette('troubleshooting').
I've only been able to run additive models, like this one: b7<-glmmTMB(fvfm~Temperature+dia+(1|ID), zi=~dia, disp=~dia, data=dc, family=beta_family(link="logit")). Anyone know why this happens check some posts, but I have not found the answer.
Beforehand thank you very much!!
regards
Fran

**Comment by bbolker** [comment] 2020-12-01 22:14
@Franelizabethgalvez  : sorry, this completely slipped through the cracks. If you still want help, in order of preference (see https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions), you could ask on `r-sig-mixed-models@r-project.org` or open a new issue. (Posting at the end of a *closed* issue is one of the least reliable ways to get us to notice that there is something to answer ...)

A couple of points:

- having access to your data would make it much easier to troubleshoot
- making day a categorical variable makes your much more complex: your original model fits had two conditional-model parameters. With the additive model you have 18 (and 17 each for the dispersion and zero-inflation models). With the interaction model you have 51.

**Comment by sharri396** [comment] 2021-11-03 18:40
Hi,
I have a dataset of proportion ranging from 0 to 1. I am analyzing mortality of insects at different insecticide treatment (6 treatments). The initial mortality values were percentage data which I converted to proportionate data by dividing it to 100. The distribution is right skewed (lots of 1) in the data. Since this is a mixed model I used glmmTMB package. I used following codes.

model1<- glmmTMB(mortality~ trt + (1|block), family="beta_family", data=insect3)
However, I am getting following error message
Error in eval(family$initialize) : y values must be 0 < y < 1
I thought it is due to lots of 1s in data but I converted 1 to 0.99. However, I am still getting same error message. I am not sure what is going wrong? Can anyone help me? 

Thanks,
Sharri

**Comment by SimonDanner** [comment] 2022-07-25 15:18
@sharri396 you don't have a zero-inflation term in the model. Adding zi=~1 should resolve your problem:
`model1<- glmmTMB(mortality~ trt + (1|block), zi=~1, family="beta_family", data=insect3)
`

**Comment by zdiazmar** [comment] 2022-10-06 15:37
Hi all,

I am having a similar issue. I have a zero-inflated response variable that are proportions (Hs or gene diversity). I am hoping to test for differences in Hs between four groups of plants with different statuses (predictor variable). I think I need to include locus as a random effect, since the same loci were sampled for each group. I am hoping to use glmmTMB to detect differences in Hs between groups using the code below.

```
fit_zibeta <- glmmTMB(Hs~(Status)+(1|SNP),
                         data=h2.test,
                         ziformula=~1,
                         family=beta_family)
```

However, I am getting the following error:

```
Error in eval(family$initialize) : y values must be 0 <= y < 1
```

Am I correct in assuming that I am getting this error since the package isn't yet able to fit zero inflated models to beta distributions? Or am I missing something else?

Any advice is much appreciated!

**Comment by zdiazmar** [comment] 2022-10-06 15:53
My goodness, of course! I was so focused on the 0s that I wasn't thinking about the 1s. 

I've changed the handful of 1s to 0.99 (n=36 out of >24,000) as a few other folks have suggested above...

Thanks very much for your speedy response, Dr. Bolker!
