### ISSUE TITLE
predict doesn't work when random intercept variance is specified

### ISSUE THREAD

**Issue by ajkroeg** [glmmTMB/glmmTMB#480] opened 2019-05-09 20:24 UTC
I receive the following error when using predict on a model where I have fixed the random intercept variance to a specific level and requested standard errors:

`
Error in Dphi %*% Vtheta : non-conformable arguments`

I am using the following code:

```
m1str<-glmmTMB(Response ~ v1+ v2+ v3+
                                (1|ID2) +(0+v3|ID)
                                , family=poisson, data=dat ,doFit=F, verbose = T)
m1str$parameters$theta[1] = log(1e3)
m1str$mapArg = list(theta=factor(c(NA,1)))
v1<-glmmTMB:::fitTMB(m1str)
```

edit: split dev version install problem to new issue

**Comment by bbolker** [comment] 2019-05-23 15:35
Reproducible example:

```
library(lme4)
library(glmmTMB)

set.seed(101)
dat <- data.frame(v1=rnorm(200),v2=rnorm(200),v3=rnorm(200),
                 ID2=sample(20,size=200,replace=TRUE),
                 ID=sample(20,size=200,replace=TRUE))

dat$Response <- simulate(~ v1+ v2+ v3+ (1|ID2) +(0+v3|ID),
                  newdata=dat,
                  newparams=list(beta=rep(1,4),
                                 theta=rep(1,2)),
                  family=poisson)[[1]]

m1str<-glmmTMB(Response ~ v1+ v2+ v3+
                                (1|ID2) +(0+v3|ID)
             , family=poisson, data=dat ,
               doFit=FALSE, verbose = TRUE)
m1str$parameters$theta[1] = log(1e3)
m1str$mapArg = list(theta=factor(c(NA,1)))
v1<-glmmTMB:::fitTMB(m1str)
predict(v1,se.fit=TRUE)
```

(I get a different error: "Vtheta %*% t(A) : non-conformable arguments")

**Comment by bbolker** [comment] 2019-05-29 00:54
This works for me with the [mapArgs branch](https://github.com/glmmTMB/glmmTMB/tree/mapArgs):

```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB@mapArgs")
m1 <- glmmTMB(Response ~ v1+ v2+ v3+
                     (1|ID2) +(0+v3|ID)
               , family=poisson, data=dat 
               , map=list(theta=factor(c(NA,1)))
               , start=list(theta=c(log(1e3),0)))
predict(m1, se.fit=TRUE)
```

I won't close this until the PR is merged ...

**Comment by ajkroeg** [comment] 2019-05-31 12:00
Ah, perfect.  Confirmed that it works on my data, thanks!

**Closed** 2019-07-01 02:29 UTC

**Comment by sschloss1** [comment] 2019-12-31 23:00
I am still getting the `non-comformable arguments` error using both the dev version and the current release.

**Comment by bbolker** [comment] 2019-12-31 23:13
Can we have a reproducible example please?  The one above works for me.

To be precise: it worked just now with a clean dev install on MacOS (I wouldn't expect it to work with the current release!), using
```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB@strip_openmp")
```
(I need this rather than the `master` branch to install on my MacOS system, which doesn't have the OpenMP infrastructure needed); I can't quite find the `mapArgs` branch right now, but it was (apparently) merged with master before `strip_openmp` branched off ...

**Comment by sschloss1** [comment] 2020-01-01 00:35
Okay, your example (which was the one I was attempting earlier) works fine with the `@strip_openmp` branch.  I'm having trouble using `predict `with a different model, so I'm going to open a new issue for that, as it looks to be a different problem.  Thanks.
