### ISSUE TITLE
emmeans cannot handle class "glmmTMB" object even with latest development version

### ISSUE THREAD

**Issue by BlueManatee21** [glmmTMB/glmmTMB#516] opened 2019-09-13 07:12 UTC
Hello,

I am trying to perform some post-hoc analyses with emmeans and lsmeans on a glmmTMB model but keep getting this error message
```{r}
Error in ref_grid(object, ...) : Can't handle an object of class “glmmTMB” Use help("models", package = "emmeans") for information on supported models.
5.
stop(data)
4.
ref_grid(object, ...)
3.
emmfcn(...)
2.
.emwrap(emmeans, subst = "ls", ...)
1.
lsmeans(avm5, pairwise ~ season * site)
```
I have looked at similar posts on making glmmTMB compatible with multcomp, emmeans, and lsmeans, including this one (https://stackoverflow.com/questions/51316991/glmmtmb-post-hoc-testing-and-glht#comment89663210_51316991).

I've tried downloading the latest development version with
```{r}
devtools::install_github("glmmTMB/glmmTMB/glmmTMB")
#I'm sure I have the latest because the second time I tried it I got the following: Skipping install of 'glmmTMB' from a github remote, the SHA1 (f84f3e95) has not changed since last install.
  Use `force = TRUE` to force installation
```
and then ran this line after loading lsmeans and emmeans packages
```{r}
source(system.file("other_methods","lsmeans_methods.R",package="glmmTMB"))
```
However, I still cannot get emmeans to work with glmmTMB.

Thank you for your time!

**Comment by bbolker** [comment] 2019-09-13 11:46
I think we need a reproducible example, please.  Is there a reason you're using `lsmeans()` and not `emmeans()` ?  The vignette on model evaluation <https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/vignettes/model_evaluation.Rnw> suggests that emmeans() should work out of the box (*without* `source()`ing `lsmeans_methods.R`, which might actually be messing things up).

**Comment by bbolker** [comment] 2019-09-16 16:43
Bump ... can we have a reproducible example please/can you confirm you've tried the example above and it didn't work?  (Results of `sessionInfo()` from a clean session?) Otherwise I'll probably close this ...

**Comment by bbolker** [comment] 2019-09-23 13:16
Closing this now.  Can reopen if more information/reproducible example is provided.

**Closed by bbolker** 2019-09-23 13:16 UTC

**Comment by Anfileida2019** [comment] 2019-12-16 20:48
Dear Ben, I came across the same problem. 
My model:
 Model_1 <- glmmTMB(
  Response ~ YOF + spp_Status + (1|ZooID),
  family = "nbinom2",
  data = YOF_Status)

#But when trying to run Anova, I get this error and for emmeans too.
> Anova(Model_1,type="II")
Error in I.p[c(subs.relatives, subs.term), , drop = FALSE] : 
  subscript out of bounds
> emmeans::emmeans(Model_1, ~YOF, type = "response")
Error in ref_grid(object, ...) : 
  Can't handle an object of class  “glmmTMB” 
 Use help("models", package = "emmeans") for information on supported models.

Can you help please?

**Comment by bbolker** [comment] 2019-12-16 20:50
I can help (maybe) if you can give a **reproducible** example and the versions of `emmeans` and `glmmTMB` you're using.  What happens if you try to run the example I gave on Sep 13?

**Comment by Anfileida2019** [comment] 2019-12-16 21:37
I get the same message when I run your code.
data("cbpp",package="lme4")
> library(glmmTMB); library(emmeans)
> m1 <- glmmTMB(incidence/size ~ period + (1|herd), family=binomial, weights=size, data=cbpp)
> emmeans(m1, ~period)
Error in ref_grid(object, ...) : 
  Can't handle an object of class  “glmmTMB” 
 Use help("models", package = "emmeans") for information on supported models.

I am using R Studio version  3.3.3 (2017-03-06). 

Below is my model: 

summary(Model_1)
 Family: nbinom2  ( log )
Formula:          Response ~ YOF + spp_Status + (1 | ZooID)
Data: YOF_Status

     AIC      BIC   logLik deviance df.resid 
  2059.3   2100.1  -1020.7   2041.3      679 

Random effects:

Conditional model:
 Groups Name        Variance Std.Dev.
 ZooID  (Intercept) 1.082    1.04    
Number of obs: 688, groups:  ZooID, 44

Overdispersion parameter for nbinom2 family (): 2.08 

Conditional model:
             Estimate Std. Error z value Pr(>|z|)    
(Intercept)    0.4096     0.2066   1.983  0.04739 *  
YOFBefore     -0.4325     0.1009  -4.286 1.82e-05 ***
spp_StatusDD  -1.3679     0.2238  -6.113 9.78e-10 ***
spp_StatusEN  -0.7188     0.1621  -4.434 9.26e-06 ***
spp_StatusLC   1.7933     0.1545  11.608  < 2e-16 ***
spp_StatusNT  -0.7862     0.1628  -4.829 1.37e-06 ***
spp_StatusVU  -0.5029     0.1854  -2.712  0.00669 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> 

Thank you

**Comment by bbolker** [comment] 2019-12-16 21:40
Results of `packageVersion("glmmTMB"); packageVersion("emmeans")` ?

**Comment by Anfileida2019** [comment] 2019-12-16 21:42
sorry :( here it is:
packageVersion("emmeans")
[1] ‘1.4.3.1’
> packageVersion("glmmTMB")
[1] ‘0.2.0’

**Comment by Anfileida2019** [comment] 2019-12-16 21:44
No I don't think I have tried the development version.

**Comment by Anfileida2019** [comment] 2019-12-16 21:52
Dear Ben, 
It fixed the emmeans once I run the development version: emmeans::emmeans(Model_1, ~YOF, type = "response")
 YOF     rate    SE  df lower.CL upper.CL
 After  1.157 0.200 679    0.824     1.62
 Before 0.751 0.136 679    0.526     1.07

Results are averaged over the levels of: spp_Status 
Confidence level used: 0.95 
Intervals are back-transformed from the log scale 

But not Anova:(

Anova(Model_1,type="II")
Error in Anova.glmmTMB(Model_1, type = "II") : 
  could not find function "trivialFixef"

**Comment by bbolker** [comment] 2019-12-16 22:26
Are you really using the *development* version (i.e. `remotes::install_github("glmmTMB/glmmTMB/glmmTMB")` ?)  I'm not surprised that the version on CRAN wouldn't work (relevant changes were made in June 2019, CRAN version is from Jan 2019).

For me this works fine:

```
data("cbpp",package="lme4")
library(glmmTMB); library(emmeans); library(car)
m1 <- glmmTMB(incidence/size ~ period + (1|herd), family=binomial, weights=size, data=cbpp)
emmeans(m1, ~period)
Anova(m1, type="II")
```

**Comment by Anfileida2019** [comment] 2019-12-16 23:15
Thank you so much Sir. I appreciate your support and time! I updated all now  :) have a lovely festive seasons! All the best!

**Comment by Anfileida2019** [comment] 2019-12-21 14:50
I was wondering if anyone can help. I have downloaded the development version of glmmTMB and it was working perfectly. After a few days, when I run a different model, it doesn't load the package and shows an error :
library("glmmTMB") 
Error in library("glmmTMB") : there is no package called ‘glmmTMB’
I have uninstalled the package again and reinstall and still the same issue. I have run install.packages("glmmADMB", 
repos="http://www.math.mcmaster.ca/bolker/R",type="source"). Quit R and started again, and still doesn run.  Please help I need to re-do some analysis for a paper :( 
packageVersion("emmeans")
[1] ‘1.4.3.1’
> packageVersion("glmmTMB")
Error in packageVersion("glmmTMB") : package ‘glmmTMB’ not found.

Thank you

**Comment by bbolker** [comment] 2019-12-21 16:25
I'm not sure what `glmmADMB` has to do with it ... I would suggest making sure you're in a clean R session (i.e., close and restart R, making sure *not* to reload any saved `.RData` files), then `remotes::install_github("glmmTMB/glmmTMB/glmmTMB")`, but if that doesn't work I don't know what to suggest.

**Comment by Anfileida2019** [comment] 2019-12-21 17:07
sorry, I meant glmmTMB, not ADMB. Thank you! I will try it now.

**Comment by bbolker** [comment] 2019-12-21 17:12
There may also be an issue with the recent update of the `Matrix` package, which will make TMB (underlying glmmTMB) issue an error and stop.  If you get an error like `Package version inconsistency detected.`, try following the instructions [here](https://github.com/glmmTMB/glmmTMB/blob/master/README.md#handling-tmbmatrixglmmtmb-mismatches)

**Comment by Anfileida2019** [comment] 2019-12-21 17:21
Just one more question. Does emmeans works for the glmmDMB? I am trying a different model with glmmDMB and is not accepting emmeans. I ran these models using lsmeans a year ago and worked well, and now trying to change a label of a graph and have to re-run all in emmeans, and it gives an error message:

 lsm_YOF_Tot <- emmeans(Fit_Nat_2, ~ YOF_2008,type= "response", data = YOF_Nat_Exo)
Error in ref_grid(object, ...) : 
  Can't handle an object of class  “glmmadmb” 
 Use help("models", package = "emmeans") for information on supported models.

**Comment by bbolker** [comment] 2019-12-21 17:26
I don't know (I could figure it out but it would take me a little while ...) Is there any chance you can re-run your models in glmmTMB?  I'm encouraging people to do that whenever possible since it makes more sense to put our effort into improving glmmTMB at this point than working on glmmADMB ... the [emmeans vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/models.html) says that glmmADMB is "no longer supported" ...

**Comment by Anfileida2019** [comment] 2019-12-21 17:29
Thank you! That is what I am trying to do :( But I am having trouble with glmmTMB.
I did follow your instructions to restart R etc, and now I get this message: 

install.packages("glmmATMB", 
+                  repos="http://www.math.mcmaster.ca/bolker/R",type="source")
Warning in install.packages :
  package ‘glmmATMB’ is not available (for R version 3.3.3).

Which is weird because I have ran it on this R version just the other day :(

**Comment by bbolker** [comment] 2019-12-21 17:32
You have a typographical error ("glmmATMB" instead of "glmmADMB"). (I'm not clear why you're re-installing glmmADMB though; if you are simply trying to re-run everything with glmmTMB, you shouldn't need it ...)

**Comment by Anfileida2019** [comment] 2019-12-21 17:37
Sorry for confusing you. The models were on glmmADMB and now I am trying to run in glmmTMB, but having trouble installing it again:( Just tried again using the "install.packages("glmmATMB", 
      repos="http://www.math.mcmaster.ca/bolker/R",type="source")" 
and got this message:(
 > library(glmmTMB)
Error in library(glmmTMB) : there is no package called ‘glmmTMB’

**Comment by bbolker** [comment] 2019-12-21 17:43
I'm still confused.  To install `glmmTMB`, you should use

```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
```

The code you are quoting, besides containing a typographical error, is attempting to install glmmADMB - **not** glmmTMB ...

**Comment by Anfileida2019** [comment] 2019-12-21 17:50
I have used the remotes::install_github("glmmTMB/glmmTMB/glmmTMB") and now  I have removed glmmADMB and re-installed glmmTMB ;)  I had to install a new version of TMB. Thank you and sorry for the confusion. I am now having trouble getting Anova :( I get this error message: 
Error in I.p[subs.relatives, , drop = FALSE] : subscript out of bounds
In addition: Warning message:
In is.na(coef(mod)) :
  is.na() applied to non-(list or vector) of type 'NULL'

**Comment by Anfileida2019** [comment] 2019-12-21 17:54
It says "Error in Anova.glmmTMB(Nat_Exo_TMB_3, type = "II") : 
  could not find function "trivialFixef"

**Comment by Anfileida2019** [comment] 2019-12-21 18:06
and now this ;( after I run the updates for Anova suggested previously.

Error in UseMethod("isREML") : 
  no applicable method for 'isREML' applied to an object of class "glmmTMB"

**Comment by bbolker** [comment] 2019-12-21 18:48
Can you please open a new issue to help resolve this?  When doing so, please use the **reproducible** example below (or another one that you provide).

Also, please re-install glmmTMB development version one more time (`remotes::install_github("glmmTMB/glmmTMB/glmmTMB")`) (I just updated the version number to try to make this whole issue clearer) before running/posting your results.

```
library(glmmTMB); library(emmeans); library(car)
lapply(c("emmeans","glmmTMB","car"), packageVersion)
data("cbpp",package="lme4")
m1 <- glmmTMB(incidence/size ~ period + (1|herd), family=binomial, weights=size, data=cbpp)
emmeans(m1, ~period)
Anova(m1, type="II")
```

**Comment by Anfileida2019** [comment] 2019-12-21 19:17
I will try right away. Thank you!

**Comment by Anfileida2019** [comment] 2019-12-21 19:57
All resolved with the new version of R and updating glmmTMB:) happy days! Thank you so much!
