### ISSUE TITLE
"Error in fitTMB(TMBStruc) : 'g' object not found \n"

### ISSUE THREAD

**Issue by JoFloBlue** [glmmTMB/glmmTMB#504] opened 2019-07-11 16:00 UTC
Hello,

I'm using glmmTMB on a Poisson model with two random effects (random slopes model).
So I have many fixed effects (about 20 ) and two independant random effects in a big database of 15000 units.
Some times, the Hessian matrix was defined positive. I 've added:
` control = glmmTMBControl(optCtrl = list(iter.max = 3000, eval.max = 4000),profile = TRUE)` which helped me to solve most of the NA's I got before.
But now, I get a new error message :
`"Error in fitTMB(TMBStruc) : 'g' object not found \n"`
I have no clue of what may cause this.

Secondly,  what can I do to improve the convergence of my model ?
Should I add a control parameter ?

Thanks for any help

**Comment by bbolker** [comment] 2019-07-12 11:08
It's **very very** hard for us to figure out why your model is hard to fit without a reproducible example  ... can you share your data, or data that produce similar problems? The relevant code is [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R#L931-L945), and the logic looks slightly odd. I will revisit the changes made in [this commit](https://github.com/glmmTMB/glmmTMB/commit/4cb12d04eef467ba1740c6d835255812e7a8734d), and the relevant tests, and see if I can figure out what's going on.

**Comment by JoFloBlue** [comment] 2019-07-12 12:01
Hello, 
Here is attached an example of data that is giving this mistake.
[nsim_1HR1.xlsx](https://github.com/glmmTMB/glmmTMB/files/3386320/nsim_1HR1.xlsx)
And the code : 
```
library(surrosurv) # for poissonization
library(glmmTMB)        
colnames(don)[1] = 'id'
       don_pois = poissonize(don, interval.width = 1.7, factors = c ('trt', 'trialref', 'cov'), compress = FALSE)
    
    po_sp = glmmTMB(
                  formula = event ~ -1 + interval : factor(trt) + cov + offset(log(time))+ (0 + trt | trialref ) + (1| trialref ),
                  data = don_pois, 
                  control = glmmTMBControl(optCtrl=list(iter.max=1e3,eval.max=1e3),profile = TRUE),
                  family = poisson(link = "log")) 
```
I met so many convergence problems in my simulations ! I'm pretty desperate.
(I've also met "Hessian definite positive matrix" that give negative variance in the matrix of variances-covariances !
[HessianPositive.xlsx](https://github.com/glmmTMB/glmmTMB/files/3386338/HessianPositive.xlsx)
tmax = 15
```
don$status = ifelse (don$time > tmax, 0, don$status )
don$time   = ifelse (don$time > tmax, tmax, don$time )
don$id = seq(1:length(don$time))

don_pois = poissonize(don, interval.width = 1.5, factors = c ('trt', 'trial', 'cov'), compress = FALSE)
pois_est2    =  glmmTMB(
  formula = event ~ -1 + interval : factor(trt) + cov + offset(log(time))+ (0 + trt | trial) + (1| trial),
  data = don_pois, 
  family = poisson(link = "log"))

diag(vcov(pois_est2, full = TRUE)) 
```

I would be very grateful for any help. Currently, about half of my simulations are failing.

**Comment by ajkroeg** [comment] 2019-07-12 13:17
I suspect most of your problems with convergence come from this: `(0 + trt | trial) + (1| trial)`.

Since `trt` is a factor, it doesn't really have a 'slope'.  Rather it simply changes the intercept by each level of the factor.  If you want the effect of `trt` on to vary by `trial`, I believe the random effects should be coded like this: `(1| trial) + (1| trial:trt)`.  And actually `(1|trial)` might be redundant but I'm like...60% sure its necessary.

I had problems (a few months back) running models with control parameter  `profile=TRUE`, so you might try with that disabled if you're still getting problems.

**Comment by JoFloBlue** [comment] 2019-07-12 13:38
Thanks a lot for your suggestion! 
My model includes two random effets (`a` and `b`) for `trial` which is written as : a_(trial) + b_(trial) * D_(trt).
D_(trt) is a binary covariate (=-1 or 1).
My first random effect is for heterogenity between  levels of `trial` and the second one  is for heterogeneity of `trt` effect between levels of `trial`.
Do you confirm that I can replace my initial formulation  `(0 + trt | trial) + (1| trial) `by `(1| trial) + (1| trial:trt)` ?
Thanks again :-)

**Comment by ajkroeg** [comment] 2019-07-12 14:09
The 'a_', 'b_', and D_' formulation is a little confusing: 
> My model includes two random effets (a and b) for trial which is written as : a_(trial) + b_(trial) * D_(trt).

But if I understand you correctly, then yes.  `(1| trial) + (1| trial:trt)` will allow for both heterogeneity between levels of `trial`, and between the effects of levels of `trt` on the levels of `trial` (although, as I said the `(1| trial)` part may not be necessary...I just can't remember for sure).

**Comment by JoFloBlue** [comment] 2019-07-12 14:27
Thanks a lot for your suggestion :-) I've run few hundreds of simulations et no Na's appear.
I'll discuss with my supervisor  for the need to maintain the `(1|trial)`
Good continuation !!

**Comment by ajkroeg** [comment] 2019-07-12 14:47
No problem.  If you examine `ranef()` on a model run `(1| trial:trt)`, you'll see that it estimated the random intercepts for each `trial:trt` combination.  So for 5 levels of `trial` and 2 of `trt`, it's estimated 10 intercepts.  Might be helpful for illustrating to your supervisor that the required heterogeneity is captured.

And apologies to @bbolker, etc. for turning this into a stackexchange thread. :P

**Comment by JoFloBlue** [comment] 2019-07-12 15:00
Thank you for the extra details :-)
(Subsidiary question: if I need the observed inverse information matrix of this model, do you think it is correct to write: `vcov (po_sp, full = TRUE, information = "observed")` ? )

**Comment by bbolker** [comment] 2019-07-13 04:30
1. `(1|trial)` and  `(1|trial:trt)` are definitely confounded, due to the way that R constructs model matrices.
2. I'll still see if I can get this to give a more sensible error message. On my Linux machine I instead get `Error in (function (start, objective, gradient = NULL, hessian = NULL,  : 
  gradient function must return a numeric vector of length 2` and a (`NA/NaN function evaluation` warning) ... (without `profile=TRUE` I just get a non-pos-def warning)
3. where did you get `information="observed"` from in the previous example? I do think that `vcov()` should give you what you want ...

**Comment by bbolker** [comment] 2019-07-13 04:47
PS is it really intended that `interval` gets divided into 49 distinct categories, and that we thus have 99=49*2+1 fixed effect parameters (in your first example)?  (Your description says "about 20" fixed effects ...) You have enough observations to get away with this, and I certainly don't know the background behind your methods, but discretizing a predictor into many distinct categories without doing anything to regularize/smooth the answers seems questionable ...

**Comment by JoFloBlue** [comment] 2019-07-13 23:39
Hello Ben,
Thanks for all your suggestions.
1. When I  have` (1|trial:trt)` only, instead of `(1|trial) + (1|trial:trt)`, I only get the estimation of one random effect which does not correspond to my theoretical model which includes two (independant) random parameters with two distinct variances. 
I understand your point but I wouldn't know how to fit in my model with one variance estimation.
3. I made a confusion with the `merDeriv` package and its covariance matrix for the `lme4` package. Sorry !!
PS : in fact, I am only keeping time till 17:
```
tmax = 17
 data$status = ifelse (data$time > tmax, 0, data$status )
 data$time = ifelse (data$time > tmax, tmax, data$time )
```
This gives me 10 intervals times 2 ( two levels of `trt`) + 1 fixed parameter = 21 fixed parameters.
I always divide my `tmax` by 10 to have 10 intervals and 21 fixed effects at the end.  
It would be very hard to have more than 20 intervals one one dataset ! 
You are perfectly right, 49 intervals, it's definitely too much :-) 

Anyway, thank you very much for thinking about my problem. I have been stuck for weeks with these problems of non-convergence!

**Comment by bbolker** [comment] 2021-09-12 00:34
Closing as not reproducible ...

**Closed by bbolker** 2021-09-12 00:34 UTC
