### ISSUE TITLE
Test failure on big-endian systems since Matrix 1.3-0

### ISSUE THREAD

**Issue by ginggs** [glmmTMB/glmmTMB#665] opened 2021-02-02 09:17 UTC
Since upgrading to Matrix 1.3-0, I'm seeing the test failures below on big-endian systems (confirmed on s390x and ppc64).  The problem persists with Matrix 1.3-2.  I have re-installed TMB and most recently glmmTMB (as per #615).

Any ideas?
```
== Failed ======================================================================
-- 1. Error (test-VarCorr.R:11:1): (code run outside of `test_that()`) ---------
Error: gradient function must return a numeric vector of length 6
Backtrace:
 1. glmmTMB::glmmTMB(distance ~ age + (age | Subject), data = Orthodont) test-VarCorr.R:11:0
 2. glmmTMB::fitTMB(TMBStruc)
 4. glmmTMB:::optfun()
 6. base::with.default(...)
 7. [ base::eval(...) ] with 1 more call

-- 2. Error (test-basics.R:29:1): (code run outside of `test_that()`) ----------
Error: gradient function must return a numeric vector of length 3
Backtrace:
 1. glmmTMB::glmmTMB(Reaction ~ 1 + (1 | Subject), sleepstudy) test-basics.R:29:0
 2. glmmTMB::fitTMB(TMBStruc)
 4. glmmTMB:::optfun()
 6. base::with.default(...)
 7. [ base::eval(...) ] with 1 more call

-- 3. Error (test-bootMer.R:11:5): Bernoulli responses -------------------------
Error: gradient function must return a numeric vector of length 3
Backtrace:
 1. glmmTMB::glmmTMB(...) test-bootMer.R:11:4
 2. glmmTMB::fitTMB(TMBStruc)
 4. glmmTMB:::optfun()
 6. base::with.default(...)
 7. [ base::eval(...) ] with 1 more call

-- 4. Error (test-bootMer.R:19:5): Bernoulli responses -------------------------
Error: gradient function must return a numeric vector of length 3
Backtrace:
 1. glmmTMB::glmmTMB(...) test-bootMer.R:19:4
 2. glmmTMB::fitTMB(TMBStruc)
 4. glmmTMB:::optfun()
 6. base::with.default(...)
 7. [ base::eval(...) ] with 1 more call

-- 5. Error (test-control.R:26:5): profile method ------------------------------
Error: gradient function must return a numeric vector of length 15
Backtrace:
 1. glmmTMB:::myfit(profile = FALSE) test-control.R:26:4
 2. glmmTMB::glmmTMB(...) test-control.R:20:8
 3. glmmTMB::fitTMB(TMBStruc)
 5. glmmTMB:::optfun()
 7. base::with.default(...)
 8. [ base::eval(...) ] with 1 more call

-- 6. Error (test-control.R:71:3): parallel regions ----------------------------
Error: gradient function must return a numeric vector of length 15
Backtrace:
 1. glmmTMB:::capture_time_model(parallel = 1) test-control.R:71:2
 2. glmmTMB:::myfit(...) test-control.R:64:4
 3. glmmTMB::glmmTMB(...) test-control.R:54:4
 4. glmmTMB::fitTMB(TMBStruc)
 6. glmmTMB:::optfun()
 8. base::with.default(...)
 9. [ base::eval(...) ] with 1 more call

-- 7. Error (test-disp.R:33:1): (code run outside of `test_that()`) ------------
Error: gradient function must return a numeric vector of length 5
Backtrace:
 1. glmmTMB::glmmTMB(x ~ disp + (1 | fac), dispformula = ~disp, dat) test-disp.R:33:0
 2. glmmTMB::fitTMB(TMBStruc)
 4. glmmTMB:::optfun()
 6. base::with.default(...)
 7. [ base::eval(...) ] with 1 more call

-- 8. Error (test-edgecases.R:9:5): profiling failure --------------------------
Error: gradient function must return a numeric vector of length 3
Backtrace:
  1. testthat::expect_warning(...) test-edgecases.R:9:4
  6. glmmTMB::glmmTMB(...)
  7. glmmTMB::fitTMB(TMBStruc)
  9. glmmTMB:::optfun()
 11. base::with.default(...)
 12. [ base::eval(...) ] with 1 more call

-- 9. Error (test-env.R:18:5): basic example #1 --------------------------------
Error: gradient function must return a numeric vector of length 4
Backtrace:
 1. glmmTMB::glmmTMB(Reaction ~ Days + (1 | Subject), data = sleepstudy) test-env.R:18:4
 2. glmmTMB::fitTMB(TMBStruc)
 4. glmmTMB:::optfun()
 6. base::with.default(...)
 7. [ base::eval(...) ] with 1 more call

-- 10. Error (test-env.R:34:5): paranoia ---------------------------------------
Error: gradient function must return a numeric vector of length 4
Backtrace:
 1. glmmTMB::glmmTMB(Reaction ~ Days + (1 | Subject), data = sleepstudy) test-env.R:34:4
 2. glmmTMB::fitTMB(TMBStruc)
 4. glmmTMB:::optfun()
 6. base::with.default(...)
 7. [ base::eval(...) ] with 1 more call
  ... and 20 more


Maximum number of 10 failures reached, some test results may be missing.

== DONE ========================================================================
```

**Comment by mmaechler** [comment] 2021-02-02 09:34
Can you please upgrade to Matrix 1.3-2 -- there was a small problem there which unfortunately had an effect on `lme4`  and so may have had a similar effect here..

**Comment by ginggs** [comment] 2021-02-02 09:44
The problem persists with Matrix 1.3-2.

**Comment by mmaechler** [comment] 2021-02-02 10:22
Unfortuntely, the above output suppresses almost everything that would be relevant  (this is a reason people R developers like me don't like testthat.. but I divert).  But as you confirmed the errors persist with newer Matrix, I'll have a deeper look.

**Comment by mmaechler** [comment] 2021-02-02 11:29
Well, already in  'R CMD build glmmTMB`    when I have my usual setting
```
_R_CHECK_LENGTH_1_CONDITION_=true
_R_CHECK_LENGTH_1_LOGIC2_=verbose
```

I see embarrassing (given how long these things can be detected with settings as the above)  bad code from package
`MuMIn` : 

```
 ----------- FAILURE REPORT -------------- 
 --- failure: length > 1 in coercion to logical ---
 --- srcref --- 
: 
 --- package (from environment) --- 
MuMIn
 --- call from context --- 
plot.model.selection(owls_nb1_dredge)
 --- call from argument --- 
!is.null(labels) && !is.na(labels)
 --- R stacktrace ---
where 1: plot.model.selection(owls_nb1_dredge)
where 2: plot(owls_nb1_dredge)
where 3: plot(owls_nb1_dredge)
where 4: eval(expr, envir, enclos)
where 5: eval(expr, envir, enclos)
where 6: withVisible(eval(expr, envir, enclos))
where 7: withCallingHandlers(withVisible(eval(expr, envir, enclos)), warning = wHandler, 
    error = eHandler, message = mHandler)
where 8: handle(ev <- withCallingHandlers(withVisible(eval(expr, envir, 
    enclos)), warning = wHandler, error = eHandler, message = mHandler))
where 9: timing_fn(handle(ev <- withCallingHandlers(withVisible(eval(expr, 
    envir, enclos)), warning = wHandler, error = eHandler, message = mHandler)))
where 10: evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos, 
    debug = debug, last = i == length(out), use_try = stop_on_error != 
        2L, keep_warning = keep_warning, keep_message = keep_message, 
    output_handler = output_handler, include_timing = include_timing)
where 11: evaluate::evaluate(...)
where 12: evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning), 
    keep_message = !isFALSE(options$message), stop_on_error = if (options$error && 
        options$include) 0L else 2L, output_handler = knit_handlers(options$render, 
        options))
where 13: in_dir(input_dir(), evaluate(code, envir = env, new_device = FALSE, 
    keep_warning = !isFALSE(options$warning), keep_message = !isFALSE(options$message), 
    stop_on_error = if (options$error && options$include) 0L else 2L, 
    output_handler = knit_handlers(options$render, options)))
where 14: block_exec(params)
where 15: call_block(x)
where 16: process_group.block(group)
where 17: process_group(group)
where 18: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group), 
    error = function(e) {
        setwd(wd)
        cat(res, sep = "\n", file = output %n% "")
        message("Quitting from lines ", paste(current_lines(i), 
            collapse = "-"), " (", knit_concord$get("infile"), 
            ") ")
    })
where 19: process_file(text, output)
where 20: (if (grepl("\\.[Rr]md$", file)) knit2html_v1 else if (grepl("\\.[Rr]rst$", 
    file)) knit2pandoc else knit)(file, encoding = encoding, 
    quiet = quiet, envir = globalenv(), ...)
where 21: engine$weave(file, quiet = quiet, encoding = enc)
where 22: doTryCatch(return(expr), name, parentenv, handler)
where 23: tryCatchOne(expr, names, parentenv, handlers[[1L]])
where 24: tryCatchList(expr, classes, parentenv, handlers)
where 25: tryCatch({
    engine$weave(file, quiet = quiet, encoding = enc)
    setwd(startdir)
    output <- find_vignette_product(name, by = "weave", engine = engine)
    if (!have.makefile && vignette_is_tex(output)) {
        texi2pdf(file = output, clean = FALSE, quiet = quiet)
        output <- find_vignette_product(name, by = "texi2pdf", 
            engine = engine)
    }
    outputs <- c(outputs, output)
}, error = function(e) {
    thisOK <<- FALSE
    fails <<- c(fails, file)
    message(gettextf("Error: processing vignette '%s' failed with diagnostics:\n%s", 
        file, conditionMessage(e)))
})
where 26: tools::buildVignettes(dir = ".", tangle = TRUE)

 --- value of length: 7 type: logical ---
[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 --- function from context --- 
function (x, ylab = NULL, xlab = NULL, labels = attr(x, "terms"), 
    labAsExpr = FALSE, col = c("SlateGray", "SlateGray2"), col2 = "white", 
    border = par("col"), par.lab = NULL, par.vlab = NULL, axes = TRUE, 
    ann = TRUE, ...) 
{
```  
...........
```
        else if (!is.null(labels) && !is.na(labels)) {
```
.............
```
}
<bytecode: 0xe917690>
<environment: namespace:MuMIn>
 --- function search by body ---
Function plot.model.selection in namespace MuMIn has this body.
 ----------- END OF FAILURE REPORT -------------- 
Quitting from lines 238-241 (model_evaluation.Rnw) 
Error: processing vignette 'model_evaluation.Rnw' failed with diagnostics:
'length(x) = 7 > 1' in coercion to 'logical(1)'
--- failed re-building ‘model_evaluation.Rnw’

SUMMARY: processing the following file failed:
  ‘model_evaluation.Rnw’

Error: Vignette re-building failed.
Execution halted
```
where evidently  `&& !is.na(labels)`  should be  `&& anyNA(labels)` .
Ok, I'll rerun  R CMD build withOUT building vignettes ..

**Comment by mmaechler** [comment] 2021-02-02 13:55
I could not reproduce any error in  R CMD check.  I had a `WARNING` from the vignette building issue above (which I may only get because of the strict _R_CHECK_*.. setting  but I think they are part of `--as-cran` now anyway.  I used extra switches which rather find *more* problems, than less, usually:
```
R CMD check --as-cran --timings --run-donttest --install-args=--no-clean-on-error glmmTMB
```
One difference to you is that I used 'R 4.0.3 patched' (of ca. yesterday), but then that should influence who Matrix-1.3-2 works at all..

**Comment by ginggs** [comment] 2021-02-02 14:58
To be clear, I don't see any test failures on the little-endian systems; amd64, arm64, etc. only on the two big-endian systems I tried.

I'm happy to run more tests on big-endian systems, but would you please tell me how I can tweak `testthat` to give more output?

The reason I singled out `Matrix` as a possible cause is the failure appeared with 1.3-0, persists with 1.3-2, and the goes away again when reverted to 1.2-18.

**Comment by mmaechler** [comment] 2021-02-02 15:16
Thank you @ginggs for the extra evidence with Matrix versions. The C level changes in Matrix where very small between 1.2-18 and 1.3-0 ... and the R level changes between 1.2-18  and 1.3-2  should be uniformly "better than previous".. however not in all respects back compatibly.  Now  I've nortr heard of R level changes to be impactful only on one kind of *-endian so I'm a bit puzzled.  

On your `testthat` help issue, I hope my co-authors chime in: They imposed `testthat` on us. I've never used it on my own impulse: It looks cool if all the tests run fine, but every time a test fails, I lose much more time than if I'd use simple tests based on `stopifnot()`, `all.equal()`, `tools::assertError()`  etc.

**Comment by bbolker** [comment] 2021-02-13 22:15
I'm not sure there would be any more information available even if this were run under regular R tests. I *believe* that the error should be reproducible on your system(s) with just this (the error above says that it occurs on line 11 of `tests/testthat/test-VarCorr.R`; I've removed a few lines that *seem* to be irrelevant).

```r
stopifnot(require("testthat"),
          require("glmmTMB"),
          require("lme4"))
data("Orthodont", package="nlme")
fm1 <- glmmTMB(distance ~ age + (age|Subject), data = Orthodont)
```

This assumes (fingers crossed) that this isn't some very delicate state-dependent problem (i.e. it's sensitive to what other stuff has been run before) ...

Although this error is proximally from `nlminb`, we do see it from time to time when running `glmmTMB` (or `TMB`): [googling this error message](https://www.google.com/search?channel=fs&client=ubuntu&q=%22+gradient+function+must+return+a+numeric+vector+of+length+%22) usually seems to come from badly posed models that people try to run (I don't think we've ever gotten a solidly reproducible example to play with); for some reason I guess the underlying `TMB` functions fail in some way that leads to a wrong-length (or non-numeric?) gradient function being returned.

**Comment by ginggs** [comment] 2021-02-14 08:56
I tried this on s390x (big-endian):
```
> stopifnot(require("testthat"),
          require("glmmTMB"),
          require("lme4"))
Loading required package: testthat
Loading required package: glmmTMB
Loading required package: lme4
Loading required package: Matrix
> data("Orthodont", package="nlme")
> fm1 <- glmmTMB(distance ~ age + (age|Subject), data = Orthodont)
Error in (function (start, objective, gradient = NULL, hessian = NULL,  : 
  gradient function must return a numeric vector of length 6
In addition: Warning messages:
1: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
2: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
3: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
4: In (function (start, objective, gradient = NULL, hessian = NULL,  :
  NA/NaN function evaluation
Timing stopped at: 0.24 0 0.251
```

and on arm64 (little-endian):
```
> stopifnot(require("testthat"),
          require("glmmTMB"),
          require("lme4"))
Loading required package: testthat
Loading required package: glmmTMB
Loading required package: lme4
Loading required package: Matrix
> data("Orthodont", package="nlme")
> fm1 <- glmmTMB(distance ~ age + (age|Subject), data = Orthodont)
Warning messages:
1: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
2: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
3: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
```

**Comment by bbolker** [comment] 2021-02-14 17:03
the warning messages are chaff and should have been resolved since whenever 0f14b450fd071 was merged into the master branch.   Otherwise, your tests confirm that the minimal example does indeed display the problem.  Can you confirm/double-check that all packages been built/installed from source with consistent versions (i.e. install `Matrix`, `RcppEigen` from source *then* `TMB` *then* `glmmTMB` ?)

**Comment by ginggs** [comment] 2021-02-15 09:38
I started with the `r-base-core` binary package from Debian, and then
```
install.packages("glmmTMB")
```
I did check that none of the other binary packages from Debian were installed; `r-cran-matrix`, `r-cran-rcppeigen`, `r-cran-glmmtmb`, etc.  So I hope I got that all right.

**Comment by ginggs** [comment] 2021-02-15 09:41
@mmaechler I don't think there's anything "strange" about the C / Fortran compilers, Debian have the same GCC 10.2.1 across all architectures.

**Comment by bbolker** [comment] 2021-02-15 14:40
I would think that *should* work (since TMB and then glmmTMB should get installed from source).  A couple of other tests to try:

1. with development version:
```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
data("Orthodont", package="nlme")
fm1 <- glmmTMB(distance ~ age + (age|Subject), data = Orthodont)
```
2. TMB test:
```
library(TMB)
runExample("simple")
```

**Comment by ginggs** [comment] 2021-02-15 16:33
1. with development version:
```
> fm1 <- glmmTMB(distance ~ age + (age|Subject), data = Orthodont)
Error in (function (start, objective, gradient = NULL, hessian = NULL,  :
  gradient function must return a numeric vector of length 6
In addition: Warning message:
In (function (start, objective, gradient = NULL, hessian = NULL,  :
  NA/NaN function evaluation
```

2. TMB test:
```
> ## Fit model
> obj <- MakeADFun(data=list(x=x, B=B, A=A),
+                  parameters=list(u=u*0, beta=beta*0, logsdu=1, logsd0=1),
+              .... [TRUNCATED]

> opt <- nlminb(obj$par, obj$fn, obj$gr)
Error in nlminb(obj$par, obj$fn, obj$gr) :
  gradient function must return a numeric vector of length 4
In addition: Warning message:
In nlminb(obj$par, obj$fn, obj$gr) : NA/NaN function evaluation
```

**Comment by bbolker** [comment] 2021-02-16 14:52
The failure of the second test confirms that this is not specifically a `glmmTMB` problem but rather goes back to the upstream `TMB` package. I **strongly** suspect a binary incompatibility with the `Matrix` package, but I don't understand how it could be happening given that you install TMB from source.

**Comment by kaskr** [comment] 2021-02-16 15:50
I agree with @bbolker that it looks like a TMB problem more than a glmmTMB problem. @ginggs please feel free to post a bug report at https://github.com/kaskr/adcomp based on the above TMB example including a `traceback()`.

**Comment by bbolker** [comment] 2021-02-17 17:21
closing this for glmmTMB for now (feel free to reopen as appropriate)

**Closed by bbolker** 2021-02-17 17:21 UTC

**Comment by kaskr** [comment] 2021-04-07 15:07
I've been puzzled by this issue for a while and think I now know what's going on.

The problem seems to be that the Matrix package updated SuiteSparse from version 4.2.1 to 5.7.1 without updating the header `inst/cholmod.h` accordingly (@mmaechler can you confirm?). There is no longer a `print_function` in the `cholmod_common` struct, yet this change is not reflected by the Matrix headers. Indeed `Matrix_stubs.c` (Matrix_1.3-2) still has `Common->print_function = NULL`. And when a package LinkingTo Matrix (such as TMB) tries to read from `cholmod_common` everything is bogus (as observed in kaskr/adcomp#340 on big endian but I now see similar issues on little endian as well).

**Comment by kaskr** [comment] 2021-04-08 08:13
@mmaechler  FWIW I'm about to submit a version of TMB to CRAN that avoids using the faulty part of the Matrix headers. Fixing the Matrix package is thus not really urgent from a glmmTMB perspective.

**Comment by mmaechler** [comment] 2021-04-08 09:07
> The problem seems to be that the Matrix package updated SuiteSparse from version 4.2.1 to 5.7.1 without updating the header `inst/cholmod.h` accordingly (@mmaechler can you confirm?). 

Yes, you are right.  ... and I agree this is unfortunate.   In my `TODO` file for Matrix, I have had a section mentioning that it is problematic, that I need to manually maintain `Matrix/inst/cholmod.h`  .. and also that there is no test which tells me that an update is needed.   Would you have an idea there?   In any case, I'll update it now...  and I would be grateful if you could check that the Matrix *development* version after that.

Last: *how* do you work around it in `TMB`?  Do you have an equivalent `cholmod.h` there for now?

**Comment by kaskr** [comment] 2021-04-08 09:25
@mmaechler 

> Would you have an idea there?

Perhaps one could make a script that auto generates `cholmod.h` from `src/CHOLMOD`...

> if you could check that the Matrix development version after that.

yes will do...

> Last: how do you work around it in TMB?

Using [this commit](https://github.com/kaskr/adcomp/commit/e39d438ad6dc0e69cf0530a13438dcc90ff8f538)
