### ISSUE TITLE
R session aborts calculating performance metrics for glmmTMB betabinomial model

### ISSUE THREAD

**Issue by Natalie-J-M** [glmmTMB/glmmTMB#939] opened 2023-09-18 23:52 UTC
Hi there, I'm new to GithHub so I hope this is the appropriate place to report an issue.

I have a glmm with a beta-binomial distribution, crossed random effects and an autoregressive structure of order 1:
model <- glmmTMB(cbind(calling.n, recording.n-calling.n) ~ maxtemp + mintemp+ mslp + hum + rain.1 + rain.7 + rain.30 + 
                moon.phase + photoperiod + (1 | site.id) + (1 | frog.season) + ar1(frog.day + 0 | group), data = dat, family = betabinomial)

When I try to calculate/display performance metrics using performance:: r2, MuMIn:: r.squaredGLMM and more broadly sjPlot::tab_model, the R session aborts with a fatal error. It runs fine for other commands from these packages, such as performance:: check_collinearity.

If I run the same model with (family = binomial) the issue resolves. 

Are glmmTMB models with betabinomial distributions inherently incompatible? Or is it a bug that can be fixed?

Version info: R 4.3.1 and glmmTMB 1.1.7

**Comment by bbolker** [comment] 2023-09-26 23:49
They're not inherently incompatible as far as I know. This might be a better question for the [performance issues list](https://github.com/easystats/performance/issues) ... 

- what error do you get, exactly?
- can we have a reproducible example please?

**Comment by bbolker** [comment] 2023-10-08 00:08
Here's a reproducible example:

```r
remotes::install_github("glmmTMB/glmmTMB/glmmTMB@size_assign")
library(glmmTMB)
set.seed(101)
ngrp <- 20
npergrp <- 50
ntot <- ngrp*npergrp
dd <- data.frame(maxtemp = rnorm(ntot), mintemp = rnorm(ntot),
                              frog.day = numFactor(rep(1:npergrp, ngrp)), 
                              group = factor(rep(1:ngrp, each = npergrp)))
dd$calling <- simulate_new(~ maxtemp + mintemp + 
          ar1(frog.day + 0 | group), 
          weights = rep(100, nrow(dd)), 
          newdata = dd, 
          newparams = list(beta = rep(0,3),
                                          theta = c(0,1),
                                          betad = -2), 
          family = betabinomial)[[1]]
model <- glmmTMB(cbind(calling, 100-calling) ~ maxtemp + mintemp+ 
      ar1(frog.day + 0 | group), data = dd, family = betabinomial,
      control = glmmTMBControl(parallel = 4))
```

```r
performance::r2(model)
MuMIn::r.squaredGLMM(model)
sjPlot::tab_model(model)
```

I get warnings:

> Random slopes not present as fixed effects. This artificially inflates
  the conditional random effect variances.
  Solution: Respecify fixed structure! 
>  Can't calculate model's distribution-specific variance. Results are not
  reliable. 

These are more or less expected ... but no crashes.

R-devel, glmmTMB 1.1.18-9000 (devel), performance 0.10.5, sjPlot 2.8.15, insight 0.19.5, MuMIn 1.47.5

**Comment by bbolker** [comment] 2024-02-07 19:07
I'm going to close this because (1) it might not be specifically about `glmmTMB` and (2) I wasn't able to reproduce it.

**Closed by bbolker** 2024-02-07 19:07 UTC
