### ISSUE TITLE
Insufficient memory for predict() function when large amount of fixed effects

### ISSUE THREAD

**Issue by willtudorevans** [glmmTMB/glmmTMB#578] opened 2020-04-22 02:09 UTC
I have some large datasets with thousands of fixed effects, on which the model seems to run and converge ok. It also seems a lot faster than the standard `lm()` solution.

However a problem arises when trying to extract predictions of the trained data. When using `predict()` or `fitted()`, I get a 

> cannot allocate vector of size 6.5 Gb

error. Are there any ways to get around this? I've thought about extracting the coefficients manually and rebuilding the predictions but there's a high chance I will screw something up! I notice the `lm()` built model does not have the same problem when running `predict()`.

Any ideas would be much appreciated. I have version `1.0.1` of the package.

**Comment by mebrooks** [comment] 2020-04-22 10:15
That's unexpected behavior. Are you predicting the original data, or on a newdata object? If it's newdata, could there be something wrong with it?

**Comment by willtudorevans** [comment] 2020-04-24 02:36
I have tried it with and without newdata and the same result. I have also tried it with just `fitted(mod)`.

Strangely I've just tried it on a machine that has glmmTMB `v0.2.3` and I don't seem to get the same error.

**Comment by mebrooks** [comment] 2020-04-27 13:30
It would definitely be best to figure out what's happening with the latest version.  Please do install that on the machine that was ok with v0.2.3 to see if the source of the problem is the machine or the version.

**Comment by willtudorevans** [comment] 2020-04-30 06:10
I updated the other machine to `glmmTMB v1.0.1` and everything still worked fine.

I noticed that same machine wasn't running the latest version of R so I upgraded it from `v3.6.0` to `v.4.0.0`. I then had to reinstall all other packages as my `v3.6.0` packages didn't seem to carry over. After then rerunning the model and using the `predict()` function I get the same error as on the other machine:

> cannot allocate vector of size 6.1 Gb

Is there something you recommend I try next?

**Comment by mebrooks** [comment] 2020-04-30 08:20
Thanks for investigating that. To summarize, are you saying that you get the error on both machines now that you're running R `v.4.0.0`? Are both computers now using the latest R version? That sounds like a problem with R to me. Maybe other developers have an idea of how to debug this? @mmaechler  @bbolker @kaskr 
The news file for the new release of R is really long. I can't find a way to link to it, but see message "R 4.0.0 is released" from Peter Dalgaard. Maybe some of the big changes are affecting the size of some objects.

**Comment by willtudorevans** [comment] 2020-04-30 08:34
The first machine (where the error originally arouse) is actually running R `v3.5.3`. My guess is that the upgrade to R on the second machine (where originally there was no error) was not itself what caused the error to arise. Instead I'm guessing it was caused by a package that `glmmTMB` depends on that had to be re-installed once I updated R.

Are there any package dependencies you recommend I try re-installing to an earlier version to see if that resolves the `predict()` issue?

**Comment by mmaechler** [comment] 2020-04-30 08:44
Well, things like `numDeriv` come to mind,  but I doubt a bit that one of them or even R itself would be the culprit.  If you really cannot provide a reproducible example, say using artificial data; generated using set.seed(); runif(), rnorm() + maybe our (in)famous  `simulate(<formula>)` , then can you *at least*   type `traceback()` after the error occurs and provide that output , together with `sessionInfo()` s ?

**Comment by bbolker** [comment] 2020-05-01 02:15
for what it's worth, if all you want to do is run large linear regressions, there might be better (more specialized) solutions such as the `fastglm` package, or (if your fixed effects are dummy variables) constructing a sparse model matrix and using it in `lm.fit()` ...

**Comment by willtudorevans** [comment] 2020-05-01 02:44
When attempting to produce a reproducible example I run in to the following error when running the model: 

`Error in min(eigval) : invalid 'type' (complex) of argument`

Here is the code for the reproducible example:

```
library(glmmTMB)
set.seed(20)
n <- 100000
grps <- 3000
mingrpsize <- 30
y <- rnorm(n, 0, 3)
x1 <- paste0("Grp", rep(1:grps, each = mingrpsize, length.out = n))
x2 <- y + rnorm(n, 0, 3)
mod <- glmmTMB(y ~ x1 + x2, family = "gaussian")

```

The number of data points, and the number of fixed effects I'm attempting to model is comparable to my actual dataset but I don't yet get that error there. I have also tried different seeds and slightly different inputs to the synthetic data but I get the same error. If I dramatically reduce the number of data points however, I don't get this error.

I realise this may now be diverting from the underlying issue of this thread, but what is this reason for the `min(eigval)` error? I feel if I can avoid it I can then generate a dataset big enough to generate the 'cannot allocate vector' error relevant to this thread.

As a side-note, I realise perhaps a more sensible model to run would use a random effect for `x1`, but for the purposes of this project it needs to be fixed effects. I do however note that the random effects model: `y ~ x2 + (1|x1)` seems a lot faster, avoids the error messages and more efficient in just about every way.

**Comment by willtudorevans** [comment] 2020-05-01 02:47
Thanks bbolker, I looked into fastglm and found it really not to be that fast. I will look into the sparse model matrix solution you propose.

**Comment by bbolker** [comment] 2020-05-02 00:32
Thanks for the reproducible example, and sorry for the code dump below.  A few points:

- I've fixed the proximal problem that caused your error.
- If all you want to do is fit a linear model with a huge number of dummy fixed effects (i.e., a large number of fixed effects, but most of them are indicator variables derived from one or more many-level factors), there are probably much better ways to do this.
      - lm.fit.sparse() from MatrixModels is **way** faster
      - you can probably treat the fixed effects as a random effect with a fixed, large variance (i.e. don't allow shrinkage).  The main thing here is getting a sparse model matrix. I illustrate with `lme4` below, but you can probably do this with the `map` argument in glmmTMB (the coefficient match isn't perfect, there's probably some detail I'm not thinking about correctly).
- Most of glmmTMB's slowness and difficulty is that it's trying to compute the eigenvalues of a 3000x3000 covariance matrix as part of the error-checking.  Using `se=FALSE` will speed things up, if you don't need them (we might also be able to put in a switch to bypass the eigen-checking).
   

```
## simulate data
library(glmmTMB)
set.seed(20)
n <- 100000
grps <- 3000
mingrpsize <- 30
y <- rnorm(n, 0, 3)
x1 <- paste0("Grp", rep(1:grps, each = mingrpsize, length.out = n))
x2 <- y + rnorm(n, 0, 3)

## devtools::load_all("~/R/pkgs/glmmTMB/glmmTMB")
## debug(glmmTMB:::fitTMB)

tg1 <- system.time(mod <- glmmTMB(y ~ x1 + x2, family = "gaussian", verbose=TRUE,
                                 se = FALSE,
                                 control=glmmTMBControl(parallel=2)))
## 63 seconds 
tg2 <- system.time(update(mod, se=TRUE))
## 321 seconds

## max(Im(eigval))
## dim(sdr$cov.fixed)  ## 3002 x 3002
## eigval <- try(1/eigen(sdr$cov.fixed)$values, silent = TRUE)

## 
## 8 regions found.
## Using 8 threads
## Process R killed at Fri May  1 07:46:24 2020

library(MatrixModels)
X <- model.Matrix(~x1+x2, sparse=TRUE)
system.time(m2 <- MatrixModels:::lm.fit.sparse(X, y))
plot(fixef(mod)$cond,m2)
abline(a=0,b=1,col=2)

## another option: fit mixed models but fix random effects variance to be very large

library(lme4)
lmod <- lFormula(y ~ x2 + (1|x1), REML=FALSE)
devfun <- do.call(mkLmerDevfun, lmod)
devfun(theta=1000)
opt <- list(par=10000, fval=devfun(10000), conv=0)  ## fake optimization result

res <- mkMerMod(environment(devfun), opt, lmod$reTrms, fr = lmod$fr)
m1 <- c(unlist(ranef(res)[[1]])+fixef(res)[1],fixef(res)[2])
plot(m1,m2)
abline(a=0,b=1,col=2)
## not identical? not sure why ... missing something
```

**Comment by willtudorevans** [comment] 2020-05-02 03:00
Thanks @bbolker for the very helpful response. 

The idea of pre-specifying a much higher between group random effects variance had occurred to me but I wasn't sure if it was possible or how much difference it would make. The lmer4 solution you propose seems to work great, giving effectively the same results and running much faster. I'm unsure, however, on the code methodology which makes me hesitant to use it, but I should probably spend more time looking through it. 

Using `se = FALSE` not only speeds things up for me and gets rid of the `min(eigval)`, but also stops the `cannot allocate vector` error from generating when running `predict()`.

If there is a way to apply the large group variance idea to a `glmmTMB` model, that would be the ideal. As well as being more familiar with the `glmmTMB` syntax, I also like the fact I can easily model the variance component (i.e. `dispformula ~`).

The sparse model matrix solution is incredibly fast, but it doesn't offer the `predict()` functionality and I expect some other features I may end up needing too. It's good to have in mind though. 

Here is my latest code, testing the speeds of the different approaches, as well as comparing predictions at the end. All predictions seem to be near enough to identical, so I'm not sure that if that issue you raise at the end of your last comment will be a problem for me. I've reduced the size of `n` and `grps`, just so `fastglm` doesn't take too long:

```
library(glmmTMB)
library(fastglm)
library(Matrix)
library(MatrixModels)
library(lme4)
set.seed(20)
n <- 30000
grps <- 1000
mingrpsize <- 30
y <- rnorm(n, 0, 3)
x1 <- paste0("Grp", rep(1:grps, each = mingrpsize, length.out = n))
x2 <- y + rnorm(n, 0, 3)

#glmmTMB
system.time({
  TMBmod <- glmmTMB(y ~ x1 + x2, family = "gaussian", se = F)
  TMBpred <- predict(TMBmod)
})

#Sparse model matrix - only gets coefficients
system.time({
  form <- model.Matrix(~ x1 + x2, sparse = T)
  MMmod <- MatrixModels:::lm.fit.sparse(form, y)
})

#fastglm 
system.time({
  form <- model.matrix(~ x1 + x2)
  fastmod <- fastglm(form, y)
  Fastpred <- predict(fastmod, newdata = form)
})

#large group variamce specified in lme4
system.time({
  lmod <- lFormula(y ~ x2 + (1|x1), REML=FALSE)
  devfun <- do.call(mkLmerDevfun, lmod)
  devfun(theta=1000)
  opt <- list(par=10000, fval=devfun(10000), conv=0)  ## fake optimization result
  res <- mkMerMod(environment(devfun), opt, lmod$reTrms, fr = lmod$fr)
  lme4pred <- predict(res)
})

PredDf <- round(data.frame(TMBpred, Fastpred, lme4pred),3)
PredDf$AllMatch <- PredDf[,1] == PredDf[,2] & PredDf[,2] == PredDf[,3]
```

**Comment by willtudorevans** [comment] 2020-05-02 03:05
I realise I've somewhat derailed the thread from the headline issue. I'm yet to be able to generate synthetic data that is both small enough to avoid the `min(eigenval)` convergence issue, and big enough to generate the `cannot allocate vector` issue when running `predict()`. I will continue to try to find a reproducible example though. As a sidenote, using `se = FALSE` seems to be a work around that allows you to work with large fixed effect models and still maintain `predict()` functionality.

**Comment by willtudorevans** [comment] 2020-05-02 04:14
OK, I was wrong. Here is a reproducible example that generates the `cannot allocate vector` error on both machines, using `se = FALSE`. I'm curious if anyone else gets the same result:

```
library(glmmTMB)
set.seed(20)
n <- 150000
grps <- 3000
mingrpsize <- 30
y <- rnorm(n, 0, 3)
x1 <- paste0("Grp", rep(1:grps, each = mingrpsize, length.out = n))
x2 <- y + rnorm(n, 0, 3)
TMBmod <- glmmTMB(y ~ x1 + x2, family = "gaussian", se = F)
TMBpred <- predict(TMBmod)
```

**Comment by bbolker** [comment] 2020-05-03 18:57
Haven't gotten much farther on this yet.

- using the `map` argument would be the way to replicate the fixed-large-variance approach in glmmTMB
- I've started working on a development branch that allows you to directly specify that you want a sparse conditional fixed-effect model matrix, which should help a lot if/when it works ...

**Comment by willtudorevans** [comment] 2020-05-04 03:45
This sparse matrix feature seems to be working great @bbolker. Runs pretty fast and the `predict` function not generating the `cannot allocate vector` error.

**Comment by bbolker** [comment] 2020-05-11 17:59
Going to close this now (can reopen if there's a reason.)  Won't continue with the fixed-large-variance approach (which is mostly a work-around for the previous lack of a sparse-X option) in the foreseeable future unless there's some reason to spend time on it.

**Closed by bbolker** 2020-05-11 17:59 UTC

**Comment by willtudorevans** [comment] 2020-05-15 02:34
Hi Ben, yeah happy for this to be closed. 

I'm still unsure however if there's a way to increase variance between groups in glmmTMB? A lot of this comes from my lack of understanding of the underlying mathematics of hierarchical models and how the amount of convergence to the global mean is determined. 

From my understanding, it seems like I have two options in glmmTMB. One where I use a fixed effects model, and the amount of between group variance is maximised. Or a mixed effects model, where the between group means are somewhat converged to the global mean (particularly in groups with low sample size) and the between group variance is consequently reduced. 
For the mixed effects option, it seems like glmmTMB's 'out-of-the-box' settings invoke more convergence to the mean than I would like for some of my projects. I'm curious if there's a way to reduce that (without going all the way to fixed-effects) as some sort of 'prior' to the model. Or even if that's a mathematically sound or plausible thing to do. 

I realise this is not the topic of the original thread, so I can open this as a separate thread if preferred. The original question I asked does seem to have been solved.
