### ISSUE TITLE
Anova(model, type = "III", component = "zi") Error

### ISSUE THREAD

**Issue by ldharder** [glmmTMB/glmmTMB#672] opened 2021-03-06 17:28 UTC
Hi,

I have encountered a problem with the Anova function that may signal a code issue. (Note the version of glmmTMB that I am using was provided to me by Ben Bolker in response to issue #642.)

The analysis involves rather complex influences on a count variable, abun (the number of bees observed during 10-minute observations periods), recorded for two bee species once every other day for >2 months (i.e., repeated measures) on 22 randomly selected plants distributed among four different habitats.  Fixed effects include two factors (bee species and habitat) and four covariates that varied among sampling days (ltflw, ltterr1, ltdahl1 and prob).  Bees of a given species were not observed sufficiently often that the distribution of abun is over-dispersed compared to a negative binomial distribution, promoting analysis with a zero-inflation model.  In the analysis, I associate random among-plant variation with the zi component and the temporal auto-correlation resulting from repeated measurement of bee species on individual plants with the conditional component.  The code is as follows:

options(contrasts = c("contr.sum","contr.poly"))
abund$species <- as.factor(abund$species)
abund$habitat <- as.factor(abund$habitat)
abund$julday <- numFactor(abund$julday)
joint <- glmmTMB(abun ~ species + habitat + ltflw + ltterr1 + ltdahl1 + species:habitat + species:ltterr1 + species:ltdahl1 + prob + species:prob + exp(julday + 0|species:Plantf), 
                  zi = ~ species + habitat + ltflw + ltdahl1 + species:ltdahl1 + prob + species:prob + (1 | Plantf),
                         family=nbinom2, data=abund)
summary(joint)
Anova(joint, type=3, component="cond")
Anova(joint, type=3, component="zi")

The model fits without warnings and the model summary indicates reasonable estimates and standard errors for the partial regression coefficients.   The Anova for the conditional component produces reason results, but that for the zi component returns the message "Error in I.p[subs, , drop = FALSE] : subscript out of bounds".  

Using a Poisson distribution generates the same behavior.  The initial analysis does not converge nbinom1 distribution (non-positive-definite Hessian matrix).

If the species:habitat interaction is added to the zi component, Anova for the zi component works without complaint.  However, for that model summary for the zi component estimates extremely large SEs for partial regression coefficients associated with species, habitat and their interaction.  I interpret this as a consequence of collinearity; hence the exclusion of the species:habitat interaction from the zi component in the model described above.

Does this behavior signal a glmmTMB problem (over and above the challenging data)?

Thanks for your assistance.

PS. The data are available from [Joint abundance extract.xlsx](https://github.com/glmmTMB/glmmTMB/files/6095702/Joint.abundance.extract.xlsx)

**Comment by bbolker** [comment] 2021-03-07 03:55
this is an (accidental?) duplicate of #673

**Closed by bbolker** 2021-03-07 03:55 UTC
