### ISSUE TITLE
Installing glmmTMB with newer 'Matrix' package

### ISSUE THREAD

**Issue by ktmbiome** [glmmTMB/glmmTMB#276] opened 2017-11-22 02:03 UTC
In installing the glmmTMB package on my computer, I get the following warning, which nullifies the installation.

    Warning in checkMatrixPackageVersion() :
      Package version inconsistency detected.
    TMB was built with Matrix version 1.2.10
    Current Matrix version is 1.2.12
    Please re-install 'TMB' from source or restore original 'Matrix' package

I'm using `devtools::install_github("glmmTMB/glmmTMB/glmmTMB")`...

Does this mean that I need to go back to the old `Matrix` package for this to install correctly?

**Comment by bbolker** [comment] 2017-11-22 02:04
Can you instead re-install TMB from source as suggested ... ? `install.packages("TMB",type="source")` (you'll need compilers etc. installed)

**Comment by ktmbiome** [comment] 2017-11-22 02:13
It doesn't seem so... An excerpt of the error code is below...


    ERROR: compilation failed for package ‘TMB’
    * removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/TMB’
    * restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/TMB’
    Warning in install.packages :
      installation of package ‘TMB’ had non-zero exit status

    > library(glmmTMB)
    Warning message:
    In checkMatrixPackageVersion() : Package version inconsistency detected.
    TMB was built with Matrix version 1.2.10
    Current Matrix version is 1.2.12
    Please re-install 'TMB' from source or restore original 'Matrix' package

**Comment by ktmbiome** [comment] 2017-11-22 02:17
Sorry, how would I make sure that I have the right compilers installed?

**Comment by ktmbiome** [comment] 2017-11-22 02:25
And to answer my own question:
    > devtools::setup_rtools()
    [1] TRUE

**Comment by bbolker** [comment] 2017-11-22 02:26
... so does that mean you've succeeded ... ?

**Comment by ktmbiome** [comment] 2017-11-22 02:31
No, I'm still stuck with the error above (#3). I just was wondering how I make sure that I have the right compilers installed (per #4), and found the devtools::setup_rtools() function in the README, which returned as TRUE, suggesting that I do?

**Comment by bbolker** [comment] 2017-11-22 02:38
question is why `TMB` installation failed. Can you post the full error message + results of `sessionInfo()` ?

**Comment by ktmbiome** [comment] 2017-11-22 02:44
Sure! This is the verbage that comes from installing glmmTMB:

```
> devtools::install_github("glmmTMB/glmmTMB/glmmTMB", force=TRUE)
Downloading GitHub repo glmmTMB/glmmTMB@master
from URL https://api.github.com/repos/glmmTMB/glmmTMB/zipball/master
Installing glmmTMB
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/7r/03jgbwtj7t349m475c0vff940000gn/T/RtmpGX3FmY/devtools5166138970fe/glmmTMB-glmmTMB-8e4f33b/glmmTMB'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘glmmTMB’ ...
** libs
clang++  -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/TMB/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppEigen/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c glmmTMB.cpp -o glmmTMB.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o glmmTMB.so glmmTMB.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/glmmTMB/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Warning in checkMatrixPackageVersion() :
  Package version inconsistency detected.
TMB was built with Matrix version 1.2.10
Current Matrix version is 1.2.12
Please re-install 'TMB' from source or restore original 'Matrix' package
** help
*** installing help indices
** building package indices
** installing vignettes
   ‘covstruct.rmd’ using ‘UTF-8’ 
   ‘mcmc.rmd’ using ‘UTF-8’ 
   ‘miscEx.rmd’ using ‘UTF-8’ 
   ‘sim.rmd’ using ‘UTF-8’ 
   ‘troubleshooting.rmd’ using ‘UTF-8’ 
   ‘glmmTMB.Rnw’ using ‘UTF-8’ 
** testing if installed package can be loaded
Warning in checkMatrixPackageVersion() :
  Package version inconsistency detected.
TMB was built with Matrix version 1.2.10
Current Matrix version is 1.2.12
Please re-install 'TMB' from source or restore original 'Matrix' package
* DONE (glmmTMB)
> library(glmmTMB)
Warning message:
In checkMatrixPackageVersion() : Package version inconsistency detected.
TMB was built with Matrix version 1.2.10
Current Matrix version is 1.2.12
Please re-install 'TMB' from source or restore original 'Matrix' package
```

And my `sessionInfo()`:
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmTMB_0.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13    lattice_0.20-35 digest_0.6.12   withr_2.0.0     MASS_7.3-47     grid_3.4.2      R6_2.2.2       
 [8] nlme_3.1-131    git2r_0.19.0    httr_1.3.1      curl_3.0        minqa_1.2.4     nloptr_1.0.4    Matrix_1.2-12  
[15] devtools_1.13.3 splines_3.4.2   lme4_1.1-14     tools_3.4.2     TMB_1.7.11      compiler_3.4.2  memoise_1.1.0  
[22] knitr_1.17     

```
Some of it might be left over from troubleshooting, but I have shut down my R session and tried again to see if it was a loaded package that could be the issue...

**Comment by bbolker** [comment] 2017-11-22 02:46
What about the error messages caused by `install.packages("TMB",type="source")` ?

**Comment by ktmbiome** [comment] 2017-11-22 02:53
```
> install.packages("TMB", type = "source")
trying URL 'https://cran.rstudio.com/src/contrib/TMB_1.7.11.tar.gz'
Content type 'application/x-gzip' length 593282 bytes (579 KB)
==================================================
downloaded 579 KB

* installing *source* package ‘TMB’ ...
** package ‘TMB’ successfully unpacked and MD5 sums checked
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Matrix/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppEigen/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c external_metis.c -o external_metis.o
clang: error: unsupported option '-fopenmp'
make: *** [external_metis.o] Error 1
ERROR: compilation failed for package ‘TMB’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/TMB’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/TMB’
Warning in install.packages :
  installation of package ‘TMB’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/7r/03jgbwtj7t349m475c0vff940000gn/T/Rtmpn9JkxC/downloaded_packages’
```

Running `library(TMB)` works.  There's still a non-zero exit status indicated while installing, but I seem to be able to run glmmTMB okay right now. Does that all look okay to you?

Many, many thanks for all of your help with this!

**Comment by ktmbiome** [comment] 2017-11-22 02:56
Okay, I just shut down my R session, and now I can run `library(glmmTMB)`, but not `library(TMB)` which I believe should be fine (but kinda odd...).

**Comment by bbolker** [comment] 2017-11-22 03:04
Can you see if the material linked from https://github.com/RcppCore/RcppArmadillo/issues/143 helps?

**Comment by bbolker** [comment] 2017-11-22 03:08
We might also see if we can ask the CRAN maintainers to rebuild the binary packages for TMB on CRAN ...

**Comment by mmaechler** [comment] 2017-11-22 08:15
But really, why are we requiring  a specific version of `Matrix` --- this looks __REALLY__ error prone;
and I think the way we do it is *wrong* and against CRAN standards:  We just list 'Matrix' in the DESCRIPTION file's `Imports:`..  but the we require a specific version Matrix whereas we should ask for a specific version  ">= ..." or "<= ..." there.

Last but not least, the message that the user gets: He should downgrade Matrix is really way out!  Matrix is `Recommended` and comes with every R installation and `glmmTMB` is really behaving very impolitely if not offensively  towards "the R project" (or  to me as `Matrix` maintainer)

**Comment by kaskr** [comment] 2017-11-22 13:46
`TMB` is causing this issue - not `glmmTMB`.

`TMB` does not *require* a specific version of Matrix, but simply throws a warning if the loaded `Matrix` DLL (Matrix.so) corresponds to a different Matrix version than the one used when bulding the TMB DLL. If the two package DLLs go out of sync the only safe option is to either restore the original Matrix version *or* rebuild the TMB binary. The latter should happen automatically for CRAN packages (TMB is LinkingTo Matrix) when the Matrix package is updated. Looking at the unpacked binary packages for windows and mac:
https://cran.r-project.org/bin/windows/contrib/3.4/TMB_1.7.11.zip
https://cran.r-project.org/bin/macosx/el-capitan/contrib/3.4/TMB_1.7.11.tgz
it seems to me that rebuild was correctly triggered for windows but not for mac (see file `Matrix-version` and the time stamp).

**Comment by strengejacke** [comment] 2017-11-22 19:54
I had this issue, too, as some of my packages import *glmmTMB*. I solved this issue this way (and it has been confirmed to work for other users as well):

I just updated pkg "Matrix" from CRAN, then I completely removed TMB from my installed packages, downloaded the TMB-source from CRAN and installed locally from source package - the warning disappears for me now!

Anyone who can confirm this "workaround"?

**Comment by strengejacke** [comment] 2017-11-22 20:00
You could also navigate to the source folder of package *TMB* (e.g., on OS X located at: `/Library/Frameworks/R.framework/Versions/3.4/Resources/library/TMB`) and edit the file `Matrix-version` manually. There you have to enter the current package version of your installed Matrix-pkg.

**Comment by kaskr** [comment] 2017-11-23 08:22
@strengejacke 
First suggestion (reinstalling TMB) is the safe solution.
Second suggestion (bypassing the Matrix version check) should only be done if you can live with risk of getting wrong results.

**Comment by mmaechler** [comment] 2017-11-23 08:46
Thank you Kasper (@kaskr) for the clarification.  Yes, I was wrongly looking at `glmmTMB`s requirements instead of `TMB`s... and hence partly wrong in my conclusions as well; I'm sorry.

Still I would suggest to change

>      Please re-install 'TMB' from source or restore original 'Matrix' package

by something like

>      Please re-install 'TMB' from source or ask CRAN for a binary version of TMB maching CRAN's `Marix' package

The suggestion to downgrade Matrix seems clearly too strong, notably if read and execued by non-expert R users.

**Comment by kaskr** [comment] 2017-11-23 09:34
@mmaechler  Thanks for the suggestion! I have changed the warning message accordingly.

**Comment by ktmbiome** [comment] 2017-11-27 17:57
Okay, so I removed the glmmTMB and TMB packages from my list of packages (using `remove.packages()`), and now I get the following error when I try to install glmmTMB:

```
> devtools::install_github("glmmTMB/glmmTMB/glmmTMB", force=TRUE)
Downloading GitHub repo glmmTMB/glmmTMB@master
from URL https://api.github.com/repos/glmmTMB/glmmTMB/zipball/master
Installation failed: cannot open file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/glmmTMB/R/glmmTMB.rdb': No such file or directory
```

**Comment by bbolker** [comment] 2017-11-30 18:42
I don't know if this ever got resolved ... I think the correct resolution is to double-check whether the binaries have been re-built yet, and if not follow up with the CRAN maintainers (specifically the MacOS folks; this isn't listed publicly anywhere that I can see, so e-mail to `cran@r-project.org` is presumably the right channel) ...

**Comment by bbolker** [comment] 2017-12-22 23:16
Since the CRAN version of TMB (1.7.12) appears to be in sync with the CRAN version of Matrix (1.2.12), this problem seems at least temporarily resolved.  If Matrix is updated again before TMB updates, we may run into the same problem again (at which time we will need to ping the CRAN MacOS maintainers) ...

Closing for now.

**Closed by bbolker** 2017-12-22 23:16 UTC

**Comment by kvert-pre** [comment] 2018-04-17 01:40
Thank you very much.

**Comment by filipezabala** [comment] 2019-03-23 21:43
> Waaaay up in the beginning of the thread another user reported this error (search this page for "unsupported option"); I recommended following the steps suggested in [RcppCore/RcppArmadillo#143](https://github.com/RcppCore/RcppArmadillo/issues/143) (which points to http://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/)

Problem solved in macOS Mojave 10.14.2 (R 3.5.3) after following the above instructions and run the following code from https://github.com/frida/frida/issues/338.

```
cd /Library/Developer/CommandLineTools/Packages/
open macOS_SDK_headers_for_macOS_10.14.pkg
```

**Comment by clairerichardsRN** [comment] 2023-03-09 00:16
I'm having this exact same issue as well with R 4.2.2 @bbolker 
Looks like to resolve, I need the binary TMB package or something...

**Comment by bbolker** [comment] 2023-03-09 01:14
Given a stack (Matrix) → (TMB) → (glmmTMB), installing the later/closer-to-the-top-of-the-stack package *from source* (`install.packages(..., type = "source")`) with *whatever* version of the previous package you have installed should work.

In this particular case, Matrix is already 1.5.3 on CRAN. So if you run `install.packages("Matrix")` you should get 1.5.3 installed and be good to go.
