### ISSUE TITLE
substantial differences in predict() between glmmTMB and glmer when I(^x) is used instead of poly()

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#512] opened 2019-08-15 15:46 UTC
When using `predict()`, I found that results for `lme4::glmer()` differ quite a lot from those of `glmmTMB()` for the same model. For the following code, I would expect predicted values to (almost) match. But especially at the "tails", predicted values are not very close to each other.

Is there something I have missed, or is there a possible bug somewhere?

``` r
library(lme4)
#> Loading required package: Matrix
library(glmmTMB)

set.seed(123)
n <- 500
d <- data.frame(
  y = rbinom(n, size = 1, prob = .2),
  x = rnorm(n),
  site = sample(letters, size = n, replace = TRUE),
  area = sample(LETTERS[1:9], size = n, replace = TRUE)
)

m1 <- glmer(y ~ x + I(x^2) + I(x^3) + (1 | area), family = binomial("logit"), data = d)
m2 <- glmmTMB(y ~ x + I(x^2) + I(x^3) + (1 | area), family = binomial("logit"), data = d)

cbind(fixef(m1), fixef(m2)$cond)
#>                    [,1]        [,2]
#> (Intercept) -1.42593436 -1.42593271
#> x            0.38013718  0.38013862
#> I(x^2)      -0.07409527 -0.07409744
#> I(x^3)      -0.12605885 -0.12605990

nd <- data.frame(x = c(-2, -1, 0, 1, 2), area = NA)

predict(m1, newdata = nd, type = "link", re.form = NA)
#>         1         2         3         4         5 
#> -1.474119 -1.754108 -1.425934 -1.245951 -1.970512
predict(m2, newdata = nd, type = "link")
#> [1] -2.986839 -2.006229 -1.425933 -1.245951 -1.466285
```

<sup>Created on 2019-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment] 2019-08-15 15:47
Interestingly, when I use `poly()` instead of `I()`, everything is ok.

``` r
library(lme4)
#> Loading required package: Matrix
library(glmmTMB)

set.seed(123)
n <- 500
d <- data.frame(
  y = rbinom(n, size = 1, prob = .2),
  x = rnorm(n),
  site = sample(letters, size = n, replace = TRUE),
  area = sample(LETTERS[1:9], size = n, replace = TRUE)
)

m1 <- glmer(y ~ poly(x, 3) + (1 | area), family = binomial("logit"), data = d)
m2 <- glmmTMB(y ~ poly(x, 3) + (1 | area), family = binomial("logit"), data = d)

cbind(fixef(m1), fixef(m2)$cond)
#>                   [,1]       [,2]
#> (Intercept) -1.4846937 -1.4846951
#> poly(x, 3)1  0.3689377  0.3689691
#> poly(x, 3)2 -2.1013902 -2.1013764
#> poly(x, 3)3 -5.7808493 -5.7808698

nd <- data.frame(x = c(-2, -1, 0, 1, 2), area = NA)

predict(m1, newdata = nd, type = "link", re.form = NA)
#>         1         2         3         4         5 
#> -1.474118 -1.754105 -1.425931 -1.245952 -1.970526
predict(m2, newdata = nd, type = "link")
#> [1] -1.474120 -1.754109 -1.425932 -1.245951 -1.970524
```

<sup>Created on 2019-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by koenvanbenthem** [comment] 2019-08-15 16:55
This seems to be a bug caused by the function fix_predvars. In that function, somehow I(x^3) gets replaced with I(x^2), probably due to the use of match (on line 16) and the algorithm only checking first match of the short name of the variables (and the short name is the same for I(x^2) and I(x^3), due to the ^ not being recognised in the init_regexp - or so I guess)

**Comment by bbolker** [comment] 2019-08-15 17:07
cool -- looks like a one-character fix!

**Comment by bbolker** [comment] 2019-08-15 17:14
while we're at it can we think of other cases that will break this/could be fixed now?

**Comment by koenvanbenthem** [comment] 2019-08-15 17:14
I made an ugly fix on the branch fix_fix_predvars - for me this resolved the problem (but I don't understand the line that I made the fix to completely, so I'd rather not merge into the master right now)
https://github.com/glmmTMB/glmmTMB/tree/fix_fix_predvars

(at least this proves that this was indeed the issue)

**Comment by strengejacke** [comment] 2019-08-15 17:16
hehe, I see you have two different solutions here, but regular expressions are a miracle to me. Not sure which one works better?

**Comment by koenvanbenthem** [comment] 2019-08-15 17:17
I'll take my branch down, for sure Ben knows these things better than I do :)

**Comment by bbolker** [comment] 2019-08-15 17:28
I suspect mine is better. I'm going to explicate for future reference (not that either of you necessarily need it)

@koenvanbenthem's version: `"^\\^([(:_.[:alnum:]]+).*"`

- `^`: beginning of line
- `\\^`: escaped `^` (escaping *is* necessary in this context: `z <- "abc^def"; grep("^abc^",z); grep("^abc\\^",z)`)
- `([(:_.[:alnum:]]+)` reference group consisting of one or more characters in the set `(:_.` + alphanumeric characters
- `.*` rest of the string

I think this version doesn't actually achieve what it needs to, which is to chop extra arguments off a `poly(x,2,<other stuff>)` expression: because the `\\^` is at the beginning, it *only* matches a string with a `^` at the beginning, so nothing gets shortened in this example.  I'll try to see if I can construct an example that *would* fail with this regexp ...

my version: `"^([(^:_.[:alnum:]]+).*"` 

The key difference is that I have `^` *inside the `[]` group, which means that the reference group consists of one or more characters in the set `(^:_.` + alphanumeric characters. If the `^` were at the *beginning* of the `[]`-expression it would *negate* the sense ("one or more characters **not** in the set ...) but *in any position other than the first* it is taken literally and doesn't need to be escaped. Using `z` from above, compare `grep("[x^]",z)` (matches a single character in the set `x^`: TRUE) and `grep("^abcdef^",z)` (matches a single character **not** in the set `abcdef^`: FALSE)

What was that about miracles? :-)

**Comment by bbolker** [comment] 2019-08-15 17:34
FWIW the original version of this code was introduced in 6dc9a8eeb37fa2b, so we should look there for tests etc.

**Comment by bbolker** [comment] 2019-08-15 18:28
Maybe the regex should be "anything *but* a comma", i.e. `"^([^,]+).*"` ?

**Comment by bbolker** [comment] 2019-08-15 18:37
Trying to break it, haven't succeeded yet ...

```
set.seed(101)
library(glmmTMB)
dd <- data.frame(z=rnorm(100),x=rnorm(100),y=rnorm(100),w=rnorm(100))
form <- z ~ I((x+y)^2) + I((w+x)^2)
nd <- data.frame(x = 1:4, y=1:4, w=1:4)
head(predict(lm(form, dd),newdata=nd))
head(predict(glmmTMB(form,dd), newdata=nd))
```

**Comment by strengejacke** [comment] 2019-08-15 20:36
> Maybe the regex should be "anything _but_ a comma", i.e. `"^([^,]+).*"` ?

Not sure, but that regex looks similar to what I use to "clean" model parameter names from patterns like `log()`, `poly()` etc.

```r
pattern <- c(
  "as.factor", "factor", "offset", "log1p", "log10", "log2", "log-log",
  "log", "lag", "diff", "pspline", "poly", "catg", "asis", "matrx", "pol",
  "strata", "strat", "scale", "scored", "interaction", "sqrt", "lsp", "rcs",
  "pb", "lo", "bs", "ns", "t2", "te", "ti", "tt", # need to be fixed first "mmc", "mm",
  "mi", "mo", "gp", "s", "I"
)
# truncated code ...
p <- paste0("^", pattern[j], "\\(([^,)]*).*")
```

What is `fix_predvars()` actually doing? Can you give an example where this function is required because the order of predvars is not as it should be?

**Comment by bbolker** [comment] 2019-08-15 20:51
pretty sure those tests are [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/tests/testthat/test-predict.R#L190-L199) (also referenced above), although I haven't dug in yet ...

**Closed** 2019-10-22 12:37 UTC
