### ISSUE TITLE
Nested fixed effect not recognized in glmmTMB

### ISSUE THREAD

**Issue by hjia222** [glmmTMB/glmmTMB#627] opened 2020-09-10 15:26 UTC
I have a nested fixed effect in the model, lmer can handle it, but glmmTMB trying to estimate all the combination of the effects which does not exist in nested combination and issues error "Model convergence problem; non-positive-definite Hessian matrix". Did I miss something? 
 
```
> model <- as.formula("value ~ exp_level/event + (1 | block)")
> fit <- lmer(model, data = df)
fixed-effect model matrix is rank deficient so dropping 25 columns / coefficients
> summary(fit)
Linear mixed model fit by REML ['lmerMod']
Formula: value ~ exp_level/event + (1 | block)
   Data: df

REML criterion at convergence: -1528.5

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.2657 -0.6416 -0.0548  0.6038  4.0502 

Random effects:
 Groups   Name        Variance  Std.Dev.
 block    (Intercept) 0.0003919 0.01980 
 Residual             0.0093409 0.09665 
Number of obs: 885, groups:  block, 8

Fixed effects:
                          Estimate Std. Error t value
(Intercept)                0.37656    0.01396  26.970
exp_levellow               0.03302    0.01715   1.925
exp_levelmedium           -0.03047    0.01708  -1.783
exp_levelmedium:eventE008  0.03359    0.01708   1.966
exp_levellow:eventE010    -0.01505    0.01715  -0.877
exp_levelhigh:eventE026    0.05078    0.01708   2.972
exp_levelmedium:eventE027 -0.00625    0.01708  -0.366
exp_levelmedium:eventE028  0.02969    0.01708   1.738
exp_levellow:eventE029    -0.04005    0.01715  -2.335
exp_levelhigh:eventE032   -0.01484    0.01708  -0.869
exp_levellow:eventE032     0.03786    0.01722   2.199
exp_levelhigh:eventE045   -0.00358    0.01715  -0.209
exp_levelhigh:eventE051    0.02694    0.01770   1.522
exp_levelmedium:eventE116 -0.00625    0.01708  -0.366

Correlation matrix not shown by default, as p = 14 > 12.
Use print(x, correlation=TRUE)  or
    vcov(x)        if you need it

fit warnings:
fixed-effect model matrix is rank deficient so dropping 25 columns / coefficients
> 
> fit <- glmmTMB(model, data = df)
Warning message:
In fitTMB(TMBStruc) :
  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
> summary(fit)
 Family: gaussian  ( identity )
Formula:          value ~ exp_level/event + (1 | block)
Data: df

     AIC      BIC   logLik deviance df.resid 
      NA       NA       NA       NA      844 

Random effects:

Conditional model:
 Groups   Name        Variance  Std.Dev.
 block    (Intercept) 0.0003336 0.01827 
 Residual             0.0092025 0.09593 
Number of obs: 885, groups:  block, 8

Dispersion estimate for gaussian family (sigma^2): 0.0092 

Conditional model:
                          Estimate Std. Error z value Pr(>|z|)
(Intercept)               -0.51123         NA      NA       NA
exp_levellow               0.13320         NA      NA       NA
exp_levelmedium            0.85732         NA      NA       NA
exp_levelhigh:eventE008    1.00000         NA      NA       NA
exp_levellow:eventE008     1.00000         NA      NA       NA
exp_levelmedium:eventE008  0.03359         NA      NA       NA
exp_levelhigh:eventE010    1.00000         NA      NA       NA
exp_levellow:eventE010     0.77256         NA      NA       NA
exp_levelmedium:eventE010  1.00000         NA      NA       NA
exp_levelhigh:eventE026    0.93857         NA      NA       NA
exp_levellow:eventE026     1.00000         NA      NA       NA
exp_levelmedium:eventE026  1.00000         NA      NA       NA
exp_levelhigh:eventE027    1.00000         NA      NA       NA
exp_levellow:eventE027     1.00000         NA      NA       NA
exp_levelmedium:eventE027 -0.00625         NA      NA       NA
exp_levelhigh:eventE028    1.00000         NA      NA       NA
exp_levellow:eventE028     1.00000         NA      NA       NA
exp_levelmedium:eventE028  0.02969         NA      NA       NA
exp_levelhigh:eventE029    1.00000         NA      NA       NA
exp_levellow:eventE029     0.74756         NA      NA       NA
exp_levelmedium:eventE029  1.00000         NA      NA       NA
exp_levelhigh:eventE032    0.87295         NA      NA       NA
exp_levellow:eventE032     0.82546         NA      NA       NA
exp_levelmedium:eventE032  1.00000         NA      NA       NA
exp_levelhigh:eventE045    0.88421         NA      NA       NA
exp_levellow:eventE045     1.00000         NA      NA       NA
exp_levelmedium:eventE045  1.00000         NA      NA       NA
exp_levelhigh:eventE051    0.91473         NA      NA       NA
exp_levellow:eventE051     1.00000         NA      NA       NA
exp_levelmedium:eventE051  1.00000         NA      NA       NA
exp_levelhigh:eventE060    1.00000         NA      NA       NA
exp_levellow:eventE060     0.78762         NA      NA       NA
exp_levelmedium:eventE060  1.00000         NA      NA       NA
exp_levelhigh:eventE064    0.88779         NA      NA       NA
exp_levellow:eventE064     1.00000         NA      NA       NA
exp_levelmedium:eventE064  1.00000         NA      NA       NA
exp_levelhigh:eventE116    1.00000         NA      NA       NA
exp_levellow:eventE116     1.00000         NA      NA       NA
exp_levelmedium:eventE116 -0.00625         NA      NA       NA
```

**Comment by bbolker** [comment] 2020-09-11 14:01
The basic problem here is that you're trying to fit a rank-deficient model (_or equivalently_, your predictors are multicollinear; _or equivalently_ you have combinations of fixed effect factors that don't appear in your data). `lme4` is smart enough to (a) warn you about this ("fixed-effect model matrix is rank deficient so dropping 25 columns / coefficients") and (b) automatically remove some of the collinear columns.  This is basically a duplicate of https://github.com/glmmTMB/glmmTMB/issues/522 , which gives some workarounds for dealing with the problem ...

**Closed by bbolker** 2020-09-11 14:01 UTC
