### ISSUE TITLE
Questions about modeling overdispersion

### ISSUE THREAD

**Issue by psinger** [glmmTMB/glmmTMB#164] opened 2016-06-24 13:50 UTC
As suggested in the lme4 mailing list, I am trying out glmmTMB for modeling a Poisson model with overdispersion. I am quite unsure of how to actually do that, as far as I know, in glmmADMB this is done automatically. In lme4, I used an additional observation level random effect.

**Comment by bbolker** [comment] 2016-06-24 13:55
A few things:

- I don't *think* glmmADMB automatically handles overdispersion in Poisson models - could you clarify (if you want - this one is a bit tangential to glmmTMB) ?
- if you like you can use the same strategy as in lme4 (add an observation-level random effect: call it a "logNormal-Poisson model" if you want to sound fancy)
- glmmTMB also offers `nbinom2` (standard negative binomial parameterization, var=mu*(1+mu/k)) and `nbinom1` (linear-variance parameterization, var=mu*phi, phi>1) families; see `?family_glmmTMB`

**Comment by psinger** [comment] 2016-06-24 14:02
* I thought this is somehow done, but makes sense if it is not.
* One issue that I have is that if I add an observation-level random effect, it kind-of fits too well. Looks really overfitted even though the BIC is really, really good. It might be an option though, yes.
* I quickly tried ``nbinom2`` before but got a huge amount of error messages that I cannot replicate right now, I will try it out again though and report back.

**Comment by bbolker** [comment] 2016-06-24 14:10
You do have to be careful with assessing goodness of fit with an observation-level random effect (i.e., you have to assess the fit of the predictions *not including the observation-level random effect*).

**Comment by psinger** [comment] 2016-06-24 14:28
Of course, you are totally right, makes sense. If I predict without the random effect, the model can capture most of the zeros quite well, but too little. However, the predictions for those that are not zero are mostly way too large, e.g. max is 10mio while in the data max is 1000. 

As said, I will play a bit more around though and will report back with issues. If you have any other idea please let me know.

**Comment by psinger** [comment] 2016-06-27 09:00
Just a quick update regarding the nbinom troubles, I receive the following error a huge amount of times when fitting nbinom1 or nbinom2: ``1: In f(par, order = order, ...) : value out of range in 'lgamma'
``.

**Comment by bbolker** [comment] 2016-06-27 16:31
Hmm. Can we have a reproducible example?  I don't have a problem fitting nbinom1 or nbinom2.  (I've made a few changes in the tests -- it wouldn't hurt to re-install from Github -- but I don't think I've changed anything substantive.)  Perhaps this is a documentation/user-confusion error ... ?

**Comment by psinger** [comment] 2016-06-27 16:35
If I fit it on a smaller sample of let's say 10k samples, it works fine, but on my larger sample of 1mio data points, I end up with these errors.

**Comment by bbolker** [comment] 2016-06-27 16:41
Can we have a reproducible example? I'm trying this -- no errors.  Can you try elaborating on this example until you can produce an error, or arrange for us to have access to your data (suitably anonymized)?

```
set.seed(101)
d <- data.frame(y=rnbinom(1e6,size=1,mu=5))
library(glmmTMB)
glmmTMB(y~1,data=d,family=list(family="nbinom2",link="log"))
```

**Comment by bbolker** [comment] 2016-06-27 17:00
a longer example fails in a different way. 
https://github.com/glmmTMB/glmmTMB/blob/master/misc/GH164.R
```
Error in nlminb(start = par, objective = fn, gradient = gr) : 
  gradient function must return a numeric vector of length 4
In addition: Warning messages:
1: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
2: In he(par) : restarting interrupted promise evaluation
Timing stopped at: 40.664 8.932 54.877 
```

**Comment by psinger** [comment] 2016-06-28 09:03
I dumped a sample with the relevant information and you can download it here:
https://www.dropbox.com/s/kqqxmc3wp225lug/r_sample.csv.gz?dl=1

The following error occurs:

```
mnb1 = glmmTMB(y~1+a+(1|id),data=data,family="nbinom2")
Error in nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN gradient evaluation
In addition: Warning messages:
1: In f(par, order = order, ...) : value out of range in 'lgamma'
2: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
3: In f(par, order = order, ...) : value out of range in 'lgamma'
4: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
5: In f(par, order = order, ...) : value out of range in 'lgamma'
6: In f(par, order = order, ...) : value out of range in 'lgamma'
7: In f(par, order = order, ...) : value out of range in 'lgamma'
8: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
9: In f(par, order = order, ...) : value out of range in 'lgamma'
10: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
Timing stopped at: 1080.986 118.531 1201.079
```

**Comment by psinger** [comment] 2016-06-28 14:55
Just as a side note, fitting a binomial model on zero/nonzero data ends also in error

```
data$nz <- as.numeric(data$y>0)
fit_count2 <- glmmTMB(nz~1+a+(1|id), data=data, family="binomial")

Warning: In nlminb(start = par, objective = fn, gradient = gr): NA/NaN function evaluationWarning message:
Error in optimHess(par.fixed, obj$fn, obj$gr): gradient in optim evaluated to length 1 not 3
```

The same model also fails in lme4

    Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [glmerMod]

**Comment by timcdlucas** [comment] 2016-10-10 18:43
Sorry to butt in. I'm using straight TMB (not glmmTMB) and am getting the same error `gradient in optim evaluated to length 1 not 14`. 

As this is the only place on the internets that seems to mention this error I thought I'd see if you found out what caused it in your case.

**Comment by amyrobyn** [comment] 2016-11-15 04:22
I am receiving the same error using the surveillance package which I am assuming is calling in nlminb as it also uses a negative binomial distribution to model overdispersed count data. Any ideas?

dengue_fit_nepop <- update(dengueFit_offset, ne = list(f= ~log(pop)), data=list(pop=population(counts_sts)))

Error in nlminb(start, negll, gradient = negsc, hessian = fi, ..., scale = scale,  : 
  NA/NaN gradient evaluation

**Comment by bbolker** [comment] 2016-11-15 04:37
@amyrobyn , I don't think we can help you here. "NA/NaN gradient evaluation" is a generic `nlminb` error message, which can occur whenever something goes wrong in the objective and/or gradient function computation such that a bad value (`NA` or `NaN`) is returned, at which point `nlminb` gives up.  The other problems being discussed here are specifically `glmmTMB` problems; the *proximal* symptom/error message may be the same, but the ultimate cause is only the same in a very general (and not useful) sense ... you probably need to contact the package maintainers, e.g [here](https://r-forge.r-project.org/tracker/?group_id=45).

**Comment by bbolker** [comment] 2016-11-15 17:39
I certainly haven't gotten to the bottom of this, but I wonder if some of these issues are cryptic running-out-of-memory problems. Using `verbose=TRUE` seems to give some useful information ...

**Comment by amyrobyn** [comment] 2016-11-15 17:58
Thanks Ben for you response. I was able to sidestep the issue by removing the log function for now.

**Comment by bbolker** [comment] 2016-11-16 02:08
So, I tried [my example](https://github.com/glmmTMB/glmmTMB/blob/master/misc/GH164.R): 1 million observations, 1000 groups. The second example (`y2 ~ x + (1 | f)`) fails on my machine, but if I run it on a remote cluster on a compute node with 12G of memory, it works fine. It is *slow*: 49 minutes to fit, and several minutes just to read the fitted object back into R (because various aspects of the TMB object have to be reconstructed).

I will try the actual data set next.

This suggests that we need better ways to detect and report memory limitation problems ... ?

**Comment by bbolker** [comment] 2016-11-16 14:03
Unfortunately, the data set/example that @psinger posted *did* fail even when run in a large-memory environment, after 28 minutes.

**Comment by psinger** [comment] 2016-11-16 14:12
I actually ran the example on a 512GB RAM machine and encountered the error, so don't think it is a memory issue. I don't fully remember, but I somehow overcame the error in the end; scaling might have helped.

**Comment by bbolker** [comment] 2016-11-16 21:06
OK, then my next guess is that we are getting underflow problems (i.e. `exp(x)` underflows to 0 for sufficiently negative x). As you can see [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L67) we don't seem to be 'clamping' any of our inverse-link functions, i.e. assigning them sensible tiny minimum value rather than letting them underflow to zero. I think that @skaug or @kaskr could (???) probably say quickly how we implement the operation "set elements of a vector to the maximum of their current value or a specified scalar", i.e. shorthand for

```
    ans = exp(eta);
    n = ans.size();
    for (int i=0; i<n; i++) { if (ans[i]<minval) { ans[i]=minval; } }
```

(I would love to have a smaller/more convenient test case for this kind of problem!)

**Comment by mebrooks** [comment] 2016-11-16 22:36
I think this is what Dave invented `mfexp` for in `ADMB` to avoid the `if` statement.  I see it's used 7 times in [glmmADMB] (https://github.com/bbolker/glmmadmb/blob/332c179a11c34acb0e0ca681481cc9128616aec3/inst/tpl/glmmadmb.tpl). Tomorrow, I can check if there's already something like `mfexp` in `TMB` and we can discuss using it.

**Comment by bbolker** [comment] 2016-11-16 22:41
The function def'n in ADMB is [here](https://github.com/admb-project/admb/blob/master/src/linad99/mfexp.cpp), I think ...

**Comment by skaug** [comment] 2016-11-17 06:59
We should probably implement `mfexp` also in glmmTMB, with the definition taken directly from the ADMB source. The first derivative of `mfexp` is continuous, but not the second and third (after all, it was written prior to the random effects stuff). I am not sure what the consequence of the lack-of-continuity is, but since it has been time tested in glmmADMB, it is probably OK.

**Comment by mebrooks** [comment] 2016-11-17 17:13
I made a new branch that should handle over/underflow problems in the log-link. I didn't add robustness anywhere else in the code, but we could talk about it later
```
devtools::install_github("glmmTMB/glmmTMB/glmmTMB", ref="underflow")
```
Then run the model with `glmmTMB(..., robust = TRUE)`.

I tested it on a model with a log-link that does not have underflow problems and it still gives the same answer as before. Can one of you test it on the model that has underflow problems and let me know how it goes?

**Comment by bbolker** [comment] 2016-11-17 17:23
I will try this.  If/when this goes in the main branch, I would *really* like to see it documented - the justification (i.e. multiply differentiable extension of exp that doesn't under/overflow), the meaning of the cutoff setting and justification of the default value (`b=60`) ...  I really like the `robust` flag so it can be turned off easily if needed (although I might want to call it `robust.link` (or `robustLink` or `robust_link` or ...) instead)

**Comment by bbolker** [comment] 2016-11-25 15:38
@psinger : can you try a recent version of the package (you'll need to update TMB too, possibly from Github) and confirm that @kaskr's fixes resolve your problems?

**Comment by bbolker** [comment] 2016-11-29 20:12
Closing for now, since fixed by robustification as far as we know.

**Closed by bbolker** 2016-11-29 20:12 UTC
