### ISSUE TITLE
failing to install with clang pre-19

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#1046] opened 2024-06-16 13:39 UTC
I got an email from Brian Ripley saying "LLVM 19 is under preparation (18.1.7 is final), and a large number of C++-using packages are failing to install with the current snapshot (and have for a couple of months).  Most of these are from a broken StanHeaders headers, but others can be seen at https://www.stats.ox.ac.uk/pub/bdr/clang19/ (which contains a README.txt)."

The readme file says 
>Tests as for the main fedora-clang checks but using LLVM pre-19
>including its flang-new as the Fortran compiler.
>Other details as for 
>https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-clang .

>Prior to release, 'release notes' can be found at

>https://clang.llvm.org/docs/ReleaseNotes.html
>https://libcxx.llvm.org/ReleaseNotes.html"

The errors in our log appear to be:

```
In file included from /data/gannet/ripley/R/test-clang/TMB/include/TMB.hpp:218:
/data/gannet/ripley/R/test-clang/TMB/include/tmbutils/sparse_matrix_exponential.hpp:79:19: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   79 |     (*P).template f(A, x, y);
      |                   ^
/data/gannet/ripley/R/test-clang/TMB/include/tmbutils/sparse_matrix_exponential.hpp:89:19: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
```

I can't really work on it today, but maybe tomorrow.

**Comment by kaskr** [comment] 2024-06-16 15:24
@mebrooks I think I just fixed it in TMB. However, to test that it works, one has to setup that 'bdr/clang19' system. I'm tempted to submit to CRAN without testing...

**Comment by bbolker** [comment] 2024-06-16 23:05
Might be worth asking on `r-package-devel` whether anyone has a test platform that runs this. I think this *might* be doable with [rhub](https://r-hub.github.io/rhub/), but at present it doesn't look like it [works with packages in subdirectories of a repo](https://github.com/r-hub/rhub/issues/584) (one *could* set up a brand-new repo with just the package directory in it, for testing purposes ...)

**Comment by bbolker** [comment] 2024-06-19 15:37
- It is not clear whether CRAN will ask us to resubmit even if the problem is fixed upstream in `TMB` (my guess is that they will)
- We have made non-trivial changes since the last release.  We could:
     - Start working on testing now (especially revdep testing) to make sure the changes haven't broken anything
     - Submit the same code as was in the previous release, with the version number bumped

Thoughts?

**Comment by mebrooks** [comment] 2024-06-19 17:27
I'd be happy to get the version with random effects in the `dispformula` up on CRAN. I did revdep checks after we merged that and dealt with a couple of things. So there might not be much more to deal with. I can do the checks again, probably today or tomorrow.

**Comment by mebrooks** [comment] 2024-06-19 18:59
The reverse dependency issues are the same as when we merged the `dispRE` branch, so we're prepared for those.

**Comment by bbolker** [comment] 2024-06-20 00:41
What are those issues? Have downstream people been notified/do you want any help? We should also figure out whether we are up to date on NEWS etc., and whether there's any harmless/low-hanging stuff we want to do (e.g. documentation fixes, which can't possibly break anyone's code) before submitting the new version. (I'd certainly vote for merging #1050, #1052 in any case ...)

**Comment by bbolker** [comment] 2024-06-20 13:58
I can replicate that error locally, will look into it.

**Comment by kaskr** [comment] 2024-06-20 16:03
`TMB-1.9.12` is on CRAN and should fix the `clang-19` issue (still not tested).

**Comment by bbolker** [comment] 2024-06-20 16:45
The `afex` example works if I run `up2date` (or, presumably, if I were to re-fit the stored models with the new version of `glmmTMB`):

```r
load(system.file("extdata/", "tmb_example_fit.rda", package = "afex"))
try(afex_plot(tmb, "spp"))
tmb <- up2date(tmb)
afex_plot(tmb, "spp")
```

**Comment by bbolker** [comment] 2024-06-24 16:04
For what it's worth, I guess we haven't *officially* been told to fix anything (e.g. see https://hadley.github.io/cran-deadlines/), probably because BDR's tests were not part of the official test flow. So I think (??) we may be off the hook on this. We could bother CRAN and ask them explicitly, or we could figure that the upstream TMB fix was all that was needed, and submit a new version whenever we feel like it ... (and close this issue ...)

**Comment by kaskr** [comment] 2024-06-24 18:09
It also seems that glmmTMB has disappeared from the list https://www.stats.ox.ac.uk/pub/bdr/clang19 ?

**Closed** 2024-08-05 22:41 UTC
