### ISSUE TITLE
beta regression only works when family passed as list

### ISSUE THREAD

**Issue by meriops** [glmmTMB/glmmTMB#278] opened 2017-12-13 14:11 UTC
Not really a big problem, but I guess it's still worth mentioning...
Using `family = "betar"` or `family = beta` or `family = betar()` returns _Error in MakeADFun (...) Family not implemented!_. Using `family = list(family = "betar", link = "logit") works fine.

**Comment by bbolker** [comment] 2018-01-01 17:04
This should be fixed soon (the problem is that the internal `family` component still needs to be "beta" ...)

Also changed this to `beta_family()`, to avoid possible conflict/confusion with `mgcv::betar`

**Closed** 2018-01-01 17:57 UTC

**Comment by kjklauder** [comment] 2018-04-08 22:27
Sorry but I'm a bit confused by this thread and the package description...what is currently the best way to code the family portion of a beta-distributed model? (bonus question: if I have the development version, will the beta model play nice with effects package?)

**Comment by bbolker** [comment] 2018-04-08 23:41
Either `family=beta_family()` or `family=list(family="beta",link="logit")` should work. Better to use the former, going forward, as we'll probably have to add more information to the family object to get it to work with Anova/emmeans/effects/etc (which it doesn't yet but might soon??)

```
set.seed(101)
ngrp <- 100
eps <- 0.001
nobs <- 4000
ngrp <- 200
nobs <- 800
x <- rnorm(nobs)
f <- factor(rep(1:ngrp,nobs/ngrp))
u <- rnorm(ngrp,sd=1)
eta <- 2+x+u[f]
mu <- plogis(eta)
y <- rbeta(nobs,shape1=mu/0.1,shape2=(1-mu)/0.1)
y <- pmin(1-eps,pmax(eps,y))
dd <- data.frame(x,y,f)

library(glmmTMB)
m1 <- glmmTMB(y~x+(1|f),family=list(family="beta",link="logit"),
        data=dd)
m2 <- update(m1,family=beta_family())
```

**Comment by Tahsin1990** [comment] 2021-05-01 01:11
What is the difference between "family=beta_family()" or family=list(family="beta",link="logit")? Why do you update m1 model? wWhat is the purpose of "update" function? Thanks in advance.

**Comment by bbolker** [comment] 2021-05-01 11:52
Both ways of specifying a Beta-distributed response. The `list()` form works OK, but provides less information to `glmmTMB` than `family=beta_family()`  (you can use `str(beta_family())` to see what's included), so various model diagnostics and plotting will work better with `family=beta_family()`. The purpose of `update()` is to refit the model with a subset of the arguments changed.

**Comment by Tahsin1990** [comment] 2021-05-02 22:31
Thanks a lot. It's very useful.
