### ISSUE TITLE
glmmTMB: Error message for betafamily distribution 

### ISSUE THREAD

**Issue by sharri396** [glmmTMB/glmmTMB#770] opened 2021-11-03 18:44 UTC
Hi,
I have a dataset of proportion ranging from 0 to 1. I am analyzing mortality of insects at different insecticide treatment (6 treatments). The initial mortality values were percentage data which I converted to proportionate data by dividing it to 100. The distribution is right skewed (lots of 1) in the data. Since this is a mixed model I used glmmTMB package. I used following codes.

model1<- glmmTMB(mortality~ trt + (1|block), family="beta_family", data=insect3)
However, I am getting following error message
Error in eval(family$initialize) : y values must be 0 < y < 1
I thought it is due to lots of 1s in data but I converted 1 to 0.99. However, I am still getting same error message. I am not sure what is going wrong? Can anyone help me?

Thanks,
Sharri

**Comment by bbolker** [comment] 2021-11-03 19:00
If you have zeros in your data then I believe you need to specify a zero-inflation model, e.g. `ziformula = ~1` for a constant Z-I probability ... (glmmTMB doesn't do zero-one-inflation, yet, unfortunately).  It would be a good idea if we made the error message more specific ... it would also be good to make sure that the documentation is explicit about this requirement.

Here is the code for `initialize`, which (if you know how to read it) confirms my thought.

```
       initialize=expression({
                  if (exists("ziformula") && !ident(ziformula, ~0)) {
                      if (any(y < 0 | y >= 1)) {
                          stop("y values must be 0 <= y < 1")
                      }
                  } else {
                      if (any(y <= 0 | y >= 1))
                          stop("y values must be 0 < y < 1")
                  }
```

**Comment by sharri396** [comment] 2021-11-11 20:15
Thank you for reply. No I do not have any 0's. I have lots of 1 (histogram of dependant variable attached). The data is in proportion and the design is randomized block design so I used beta distribution with glmmTMB function. I tried to initialize ziformula function but I still get same message that y should be between 0<y<1.
my codes are 
model6<- glmmTMB(perc_pred1 ~ trt + (1|block), family="beta_family", data=betadistr)
 Any idea why I am getting this message.
![eggmortality](https://user-images.githubusercontent.com/93674969/141362521-f8383911-e6ea-432e-99d4-ef081a91c587.png)

**Comment by bbolker** [comment] 2021-11-11 21:19
Hmm. If you don't have any responses equal to 0, and you don't have any responses equal to 1 after modifying them, then I don't understand why this is happening. Any chance you can share your data (publicly is more convenient, but otherwise privately) so we can have a reproducible example?

**Comment by bbolker** [comment] 2021-11-14 22:25
A reproducible example:

```r
set.seed(101)
dd <- data.frame(y = c(rep(0,5), runif(100), rep(1,5)))
dd2 <- transform(dd, y = pmin(y, 0.999))
library(glmmTMB)
try(glmmTMB(y ~ 1, data = dd, family = "beta_family"))
## Error in eval(family$initialize) : y values must be 0 < y < 1
try(glmmTMB(y ~ 1, data = dd2, family = "beta_family"))
## Error in eval(family$initialize) : y values must be 0 < y < 1
try(glmmTMB(y ~ 1, data = dd, ziformula = ~1, family = "beta_family"))
## Error in eval(family$initialize) : y values must be 0 <= y < 1
glmmTMB(y ~ 1, data = dd2, ziformula = ~1, family = "beta_family")
## works
```

Can you show us the results of `summary(betadistr$perc_pred1)`, or `range(betadistr$perc_pred1)` ?

**Comment by bbolker** [comment] 2021-11-18 15:06
closing due to non-reproducibility; happy to re-open if we can get an example.

**Closed by bbolker** 2021-11-18 15:06 UTC
