### ISSUE TITLE
Error with glmmTMB

### ISSUE THREAD

**Issue by GabriellaS-K** [glmmTMB/glmmTMB#648] opened 2020-12-03 10:34 UTC
Hi, 

I'm trying to use glmmTMB 
and I keep getting the error:

`Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : "FreeADFunObject" not available for .Call() for package "glmmTMB"
`

Based on this [thread](https://github.com/glmmTMB/glmmTMB/issues/615) I have tried
-reinstalling TMB
-installing glmmTMB from source 

`install.packages("glmmTMB",` type="source")
`

Package versions are 1.0.2.1 for glmmTMB and 1.7.18 for TMB;  RStudio Version 1.3.1093, on a Mac OS Catalina (10.15.7). 

When I try to reinstall glmmTMB I get errors, pasting the whole error message below:

```

> install.packages("glmmTMB", type = "source")
trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/glmmTMB_1.0.2.1.tar.gz'
Content type 'application/x-gzip' length 2964506 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

* installing *source* package ‘glmmTMB’ ...
** package ‘glmmTMB’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/usr/local/Cellar/gcc/10.1.0/bin/g++-7 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TMB/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c glmmTMB.cpp -o glmmTMB.o
/bin/sh: /usr/local/Cellar/gcc/10.1.0/bin/g++-7: No such file or directory
make: *** [glmmTMB.o] Error 127
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/glmmTMB’
Warning in install.packages :
  installation of package ‘glmmTMB’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/bf/s948qjx51kb_vxsf6f4kjc7r0000gn/T/Rtmp2mvzBY/downloaded_packages’
```

If I run a glmmTMB function, I get:

```
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
```

but the model still runs...is this a usable model?

Thanks so much!

**Comment by bbolker** [comment] 2020-12-04 02:17
Can you try 

```r
install.packages("glmmTMB", repos="https://github.com/glmmTMB/glmmTMB/tree/master/repos",
                 type="binary")
```

and see if it works for you?

**Comment by bbolker** [comment] 2020-12-04 23:31
Duplicate of #615

**Closed by bbolker** 2020-12-04 23:31 UTC
