### ISSUE TITLE
Error in fitTMB(TMBStruc) :    negative log-likelihood is NaN at starting parameter values

### ISSUE THREAD

**Issue by eveboswood** [glmmTMB/glmmTMB#1118] opened 2024-11-16 15:53 UTC
When I run this code:

```r
mod_orca <- glmmTMB(
  abundance ~ year_centered * Country.list + (1 | id),
  data = filtered_orca,
  family = "nbinom2")
```

it gives me this error message:

> Error in fitTMB(TMBStruc) : 
  negative log-likelihood is NaN at starting parameter values

What does this mean?
I have tried removing NAs from the abundance column and centering year so that count starts at 1
What should I do?

**Comment by bbolker** [comment] 2024-11-16 17:27
I can think of two possibilities:

* your `glmmTMB` setup is out of sync, e.g. see [here](https://stackoverflow.com/questions/77466641/error-in-fittmbtmbstruc-negative-log-likelihood-is-nan-at-starting-parameter) or [here](https://github.com/glmmTMB/glmmTMB/issues/965). You could try

```
install.packages("TMB")
install.packages("glmmTMB", type = "source")
```
from a clean R session and see if that resolves the problem.

* You're fitting the model to a very large data set and are getting cryptic memory problems, e.g. [here](https://github.com/glmmTMB/glmmTMB/issues/744)

* Alternatively, you might have a case where the default starting values don't work well. 

Can you provide a reproducible example?

**Comment by eveboswood** [comment] 2024-11-17 08:59
Hello, thank you for your help, Im not sure what you mean by reproducible example, can i link the R-project here so you can see?
Also, the code does work when i remove (1|id) so maybe thats the problem bit?

**Comment by eveboswood** [comment] 2024-11-17 09:46
this is all my code:
library(tidyr)
library(dplyr)
library(ggplot2)
library(readr)
library(gridExtra)
library(lme4)
library(ggeffects)
library(DHARMa)
library(stargazer)
library(TMB)
library(glmmTMB)

#First the data is cleaned and then reduced to contain just our specific species
#Read LPI data
load("~/Downloads/Challenge3eveboswood/data/LPI_data.Rdata")
#Make the data 'long' by having all of the values for 'year' in one column
LPI_long <- gather(data, "year", "abundance", 25:69) 
#Remove the X's from the year column so they can be numeric, not a character
LPI_long$year <- parse_number(LPI_long$year)
#Abundance also has to be changed from a character to numeric
LPI_long$abundance <- as.numeric(LPI_long$abundance)
#Make a dataset just containing Orca abundance 
orca <- filter(LPI_long, Common.Name == "Killer whale / Orca")

#Summed the abundance for the preregistration
sum(orca$abundance, na.rm = TRUE)
#The abundance is not a whole number because some of the units are per km
#Remove four types of orca abundance because they are not individual count based
filtered_orca <- orca %>%
  filter(!Units %in% c('Number of encounters per kilometer', 'Estimated density', 'Frequency of groups sighted
', 'Estimated abundance'))
sum(filtered_orca$abundance, na.rm = TRUE)
#The sum now works and is a whole number  
#Only include countries that have more than 50 datapoints - this removes Iceland and the UK
filtered_orca <- filtered_orca %>%
  group_by(Country.list) %>%
  filter(n() >=50) %>%
  group_by(id, .add = TRUE) %>%
  filter(sum(!is.na(abundance)) >10) %>%
  ungroup()


#Created a linear model of the data and plotted this
#The residuals show that they violate some assumptions, especially the first graph
linear_orca <- lm(abundance ~ year * id, data = filtered_orca)
plot(linear_orca)

#YearScale variable meant that year started at 1
#YearScale had to be rescaled to a continuous variable 
#YearScale was centred and scaled to a mean of 0 and a standard deviation of 1
#This stopped the error message that there was a 'very large eigenvalue'
filtered_orca <- filtered_orca %>%
  mutate(YearScale = year - min(year) +1)
filtered_orca$YearScale <- scale(filtered_orca$YearScale)


#Calculate the mean and variance of abundance
#This is to see whether a negative Binomial or Poisson model would be a better fit
#Negative Binomial is better
mean_abundance <- mean(filtered_orca$abundance, na.rm = TRUE)
var_abundance <- var(filtered_orca$abundance, na.rm = TRUE)
# Compare them
mean_abundance
var_abundance

filtered_orca$year_centered <- filtered_orca$year - min(filtered_orca$year) + 1

mod_orca <- glmmTMB(
  abundance ~ year_centered * Country.list + (1 | id),
  data = filtered_orca,
  family = "nbinom2")
summary(mod_glmmTMB()summary(mod_orca))


ModResiduals <- simulateResiduals(fittedModel = mod_orca, plot=F)
plot(ModResiduals)
#Pretty good...

#This plot has points by id and trendlines with the same colour (without confidence intervals)
#The abundance scales are the same to make the two countries comparable
(Orcaplot <- ggplot() +
  geom_point(data = filtered_orca, aes(x = year, y = abundance, group = id, colour = factor(id))) +
  geom_smooth(data = filtered_orca, aes(x = year, y = abundance, group = id, colour = factor(id)),
              method = 'lm', se = FALSE) +
  facet_wrap(. ~ Country.list, scales = "fixed") +
  labs(colour = "Population ID", x = "Year", y = "Abundance") +
  theme_classic() +
  theme(text = element_text(size = 8),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        strip.background = element_rect(fill = "white"),
        strip.text = element_text(size = 10)))

stargazer(mod_orca, type = "text",
          digits = 3,
          star.cutoffs = c(0.05, 0.01, 0.001),
          digit.separator = "")

**Comment by bbolker** [comment] 2024-11-17 16:44
"reproducible" means that we need to be able to run your model ourselves and see the same problem. In short, that means we would need access to your data, *or* to simulated data that resemble your data; see `?glmmTMB::simulate_new` and https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

The first thing you could do is see if a basic example works for you:

```
library(glmmTMB)
glmmTMB(count ~ mined + (1|site), data = Salamanders, family = nbinom2)
```

I still haven't ruled out the idea that the problem is still with your installation of `glmmTMB`, rather than with your data or particular model setup ...

**Comment by bbolker** [comment] 2024-11-18 18:29
Any further info?

**Comment by bbolker** [comment] 2024-11-19 22:49
I will probably close this as non-reproducible if I don't hear back soon ...

**Comment by bbolker** [comment] 2024-11-24 00:05
I'm closing this &mdash; feel free to re-open if there is more information.

**Closed by bbolker** 2024-11-24 00:05 UTC
