### ISSUE TITLE
confint only prints the first two parameters in version 0.2.3

### ISSUE THREAD

**Issue by ShrewMaster** [glmmTMB/glmmTMB#438] opened 2019-01-19 18:14 UTC
This function used to work just fine under version 0.2.2. When I updated to version 0.2.3, it stopped printing all the parameters of the model by default, and now only prints the first two. The parameters are still there, it's just not printing them by default. Maybe something changed in another package I updated?

In other words, under version 0.2.2, `confint(model)` printed everything correctly.
Under version 0.2.3, I have to type `confint(model, parm = c(1:[_maximum number of parameters that can be printed_]))` to obtain the same result as before.
If I type `confint(model)` under version 0.2.3, it gives the same result as `confint(model, parm = c(1:2))` under version 0.2.2.

I hope this was clear.

**Comment by bbolker** [comment] 2019-01-20 01:43
Can we have a reproducible example please?

```
fm0 <- glmmTMB(Murder~Illiteracy+Population+Area+`HS Grad`,data=as.data.frame(state.x77))
> confint(fm0)
                         2.5 %       97.5 %      Estimate
cond.(Intercept) -7.469211e-01 1.451238e+01  6.882728e+00
cond.Illiteracy   1.642143e+00 4.693255e+00  3.167699e+00
cond.Population   7.291709e-05 3.601559e-04  2.165365e-04
cond.Area         2.072511e-06 1.950013e-05  1.078632e-05
cond.`HS Grad`   -2.139798e-01 2.969804e-02 -9.214087e-02
sigma             1.868788e+00 2.765670e+00  2.273423e+00
```

**Comment by ShrewMaster** [comment] 2019-01-20 21:09
That's interesting… I tried your example and it worked fine. I also tried the "Owls" example you talk about in your glmmTMB vignette, and it too printed correctly.

I investigated the problem a little deeper and eventually figured it out. It only happens when you set REML = TRUE, which is what is happening with my models. I reproduced your example again, but this time with REML = TRUE. The issue resurfaced.

`> fm0 <- glmmTMB(Murder~Illiteracy+Population+Area+`HS Grad`,data=as.data.frame(state.x77), REML = TRUE)
> confint(fm0)
                     2.5 %  97.5 % Estimate
cond.(Intercept) -1.159607 14.9251 6.882749
> confint(fm0, parm = c(1:5))
                         2.5 %       97.5 %      Estimate
cond.(Intercept) -1.159607e+00 1.492510e+01  6.882749e+00
cond.Illiteracy   1.559618e+00 4.775771e+00  3.167694e+00
cond.Population   6.514824e-05 3.679245e-04  2.165364e-04
cond.Area         1.601197e-06 1.997152e-05  1.078636e-05
cond.`HS Grad`   -2.205707e-01 3.628822e-02 -9.214126e-02`

**Comment by bbolker** [comment] 2019-01-21 01:18
this looks fairly straightforward, started working on it: https://github.com/glmmTMB/glmmTMB/tree/remlCIfix

**Comment by ShrewMaster** [comment] 2019-01-21 12:02
Thank you for your attention. Your package has been very useful in my modelling analyses :)

**Comment by stefaniemuff** [comment] 2019-04-25 19:04
I just came across the same confint problem described here, but my situation is a bit different. For theoretical reasons, I'm using models where we need to fix a variance parameter to a certain value, thus our model looks like this:

```
# We first set up the glmmTMB model, but dont' fit it
TMBStruc = glmmTMB(Loc ~ STAU1 + REST1 + Sohlenbrei +  
                     Breaks_Dis +  (1|str_ID) + 
                     (0 + STAU1 | ANIMAL_ID) + 
                     (0 + REST1 | ANIMAL_ID)   + 
                     (0 + Sohlenbrei | ANIMAL_ID), 
                   family=poisson, data=dat, doFit=FALSE) 

# Set the value of the standard deviation of the first random effect (here (1|str_ID)):
TMBStruc$parameters$theta[1] = log(1e3) 

# Tell glmmTMB not to change the first standard deviation, all other values are freely estimated (and are different from each other)
TMBStruc$mapArg = list(theta=factor(c(NA,1:3)))

# Fit the model and look at the summary:
glmm.TMB.random <- glmmTMB:::fitTMB(TMBStruc)
```

Now if I use 
`confint(glmm.TMB.random)`
the CI of the last random effect is not printed, and I suspect that this has to do with the fact that the fixed variance (here set to 10^6) is printed instead, so the last variance is kind of missing. It works if I run

`confint(glmm.TMB.random,parm = c(1:9))`

Agreed, this is not a very severe problem and will probably not affect many users (only those that will fix variances, like we do here: https://www.biorxiv.org/content/10.1101/411801v2).

Many thanks, also for the nice glmmTMB package!

**Comment by mebrooks** [comment] 2019-07-03 16:52
@stefaniemuff does the new branch solve your problem? I can't test it with your model since I don't have the data. Try the following and then run your code again.
```
devtools::install_github("glmmTMB/glmmTMB/glmmTMB", ref="remlCIfix", build_vignettes = TRUE)
```

**Comment by stefaniemuff** [comment] 2019-07-04 15:29
Thanks for taking care of that. First of all, I had to install the remlCIfix branch using

devtools::install_github("glmmTMB/glmmTMB/glmmTMB", ref="remlCIfix")

to get the installation done (no build_vignettes=TRUE), but I assume this is not critical. Unfortunately, the problem then still persists.

**Comment by mebrooks** [comment] 2019-07-04 20:10
@stefaniemuff is it possible to simulate data or use some data distributed with the package (or any package) to give a reproducible example?

**Comment by stefaniemuff** [comment] 2019-07-04 20:25
This is an example from our paper: There are four random effects, and (0 + Sohlenbrei | ANIMAL_ID) is the last one. The first RE is (1|str_ID), whose variance is fixed to a large value.

Does that help?

-----"Mollie Brooks" <notifications@github.com> schrieb: -----
An: "glmmTMB/glmmTMB" <glmmTMB@noreply.github.com>
Von: "Mollie Brooks" <notifications@github.com>
Datum: 04.07.2019 22:11
Kopie: "stefaniemuff" <stefanie.muff@uzh.ch>, "Mention" <mention@noreply.github.com>
Betreff: Re: [glmmTMB/glmmTMB] confint only prints the first two parameters in version 0.2.3 (#438)

@stefaniemuff is it possible to simulate data or use some data distributed with the package (or any package) to give a reproducible example?

**Comment by bbolker** [comment] 2019-07-04 22:40
@stefaniemuff: I think this problem might be solved if you use the "map" argument (in the main development branch): does this work as expected?
```
glmm.TMB.random = glmmTMB(Loc ~ STAU1 + REST1 + Sohlenbrei +  
                     Breaks_Dis +  (1|str_ID) + 
                     (0 + STAU1 | ANIMAL_ID) + 
                     (0 + REST1 | ANIMAL_ID)   + 
                     (0 + Sohlenbrei | ANIMAL_ID), 
                   family=poisson, data=dat, 
                    map=list(theta=factor(NA,1:3)),
                    start=list(theta=c(log(1e3),0,0,0))
confint(glmm.TMB.random)
```

**Comment by stefaniemuff** [comment] 2019-07-05 06:46
Thanks. Hm, this basically tells me that the "map" and "start" arguments are not used. That is, the procedure would not run. I just reainstalled glmmTMB from the main branch in github, but maybe I'm missing something here? 

-----"Ben Bolker" <notifications@github.com> schrieb: -----
An: "glmmTMB/glmmTMB" <glmmTMB@noreply.github.com>
Von: "Ben Bolker" <notifications@github.com>
Datum: 05.07.2019 00:40
Kopie: "stefaniemuff" <stefanie.muff@uzh.ch>, "Mention" <mention@noreply.github.com>
Betreff: Re: [glmmTMB/glmmTMB] confint only prints the first two parameters in version 0.2.3 (#438)

@stefaniemuff: I think this problem might be solved if you use the "map" argument (in the main development branch): does this work as expected?
 
glmm.TMB.random = glmmTMB(Loc ~ STAU1 + REST1 + Sohlenbrei +  
                     Breaks_Dis +  (1|str_ID) + 
                     (0 + STAU1 | ANIMAL_ID) + 
                     (0 + REST1 | ANIMAL_ID)   + 
                     (0 + Sohlenbrei | ANIMAL_ID), 
                   family=poisson, data=dat, 
                    map=list(theta=factor(NA,1:3)),
                    start=list(theta=c(log(1e3),0,0,0))
confint(glmm.TMB.random)

**Comment by bbolker** [comment] 2019-07-05 08:32
Hmm, this should be in the main branch since 10cab19 . The example below works for me in a clean R session: does it work for you? 

```
## fresh install from main branch
remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
library("glmmTMB")
m1 <- glmmTMB(count~ mined + (1|site), 
  zi=~mined,  family=poisson, data=Salamanders)
m1_map <- update(m1, map=list(theta=factor(NA)),
                start = list(theta=log(10)))
VarCorr(m1_map)
```

**Comment by stefaniemuff** [comment] 2019-07-05 14:10
The problems exist only for the confint() function. Your code works for me, but the confint does not print the last line. I'm comparing

confint(m1)
confint(m1_map)

In the scond case the last parameter (zi.zi~minedno) is not printed.

-----"Ben Bolker" <notifications@github.com> schrieb: -----
An: "glmmTMB/glmmTMB" <glmmTMB@noreply.github.com>
Von: "Ben Bolker" <notifications@github.com>
Datum: 05.07.2019 10:33
Kopie: "stefaniemuff" <stefanie.muff@uzh.ch>, "Mention" <mention@noreply.github.com>
Betreff: Re: [glmmTMB/glmmTMB] confint only prints the first two parameters in version 0.2.3 (#438)

Hmm, this should be in the main branch since 10cab19 . The example below works for me in a clean R session: does it work for you?
 
## fresh install from main branch
remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
library("glmmTMB")
m1 <- glmmTMB(count~ mined + (1|site), 
  zi=~mined,  family=poisson, data=Salamanders)
m1_map <- update(m1, map=list(theta=factor(NA)),
                start = list(theta=log(10)))
VarCorr(m1_map)

**Comment by bbolker** [comment] 2019-07-07 11:47
sorry about that.  Try one more time (with latest remlCIfix branch) please?

**Comment by stefaniemuff** [comment] 2019-07-07 17:02
I really appreciate your effort, thanks a lot. Unfortunately, also with the latest remlCIfix just reinstalled does the problem persist. 
My "workaround" is to move the random effect of which I fix the variance component (in my case (1|str_ID)) to the end of the formula, so that this is the variance that is left out by confint(). I suspect that there must be an internal counter that gets counfused when a variance is fixed instead of estimated, so that one too few is printed.

**Comment by bbolker** [comment] 2019-07-07 22:32
You're right, I still haven't got this fixed. Argh.

**Comment by mebrooks** [comment] 2019-07-08 10:07
I'm at a stock-assessment benchmark meeting this week and was prepping last week, so I can't be of much help right now. Sorry.

**Comment by stefaniemuff** [comment] 2019-07-08 11:20
No problem, it's really not an urgent thing. And there is this workaround in the mean time. Thanks anyway!

-----"Mollie Brooks" <notifications@github.com> schrieb: -----
An: "glmmTMB/glmmTMB" <glmmTMB@noreply.github.com>
Von: "Mollie Brooks" <notifications@github.com>
Datum: 08.07.2019 12:08
Kopie: "stefaniemuff" <stefanie.muff@uzh.ch>, "Mention" <mention@noreply.github.com>
Betreff: Re: [glmmTMB/glmmTMB] confint only prints the first two parameters in version 0.2.3 (#438)

I'm at a stock-assessment benchmark meeting this week and was prepping last week, so I can't be of much help right now. Sorry.

**Comment by bbolker** [comment] 2019-07-19 21:59
I think I may *finally* have fixed this ...

**Comment by stefaniemuff** [comment] 2019-07-21 13:53
Yes, it works! Many thanks, I highly appreciate your effort.

**Closed** 2019-08-07 13:52 UTC
