### ISSUE TITLE
segfault upon using glmmTMB

### ISSUE THREAD

**Issue by rdauria** [glmmTMB/glmmTMB#369] opened 2018-07-10 19:03 UTC
Hello,
I have installed glmmTMB on a linux cluster (centos 6.9) but I seem to get segmentation faults upon invoking glmmTMB. For example I have tried to follow the getting started demo in https://cran.r-project.org/web/packages/glmmTMB/vignettes/glmmTMB.pdf and I get:

```
 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("MakeADFunObject", data, parameters, reportenv, control = list(report = as.integer(ADreport)),     PACKAGE = DLL)
 2: retape(set.defaults = TRUE)
 3: MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg,     profile = NULL, silent = !verbose, DLL = "glmmTMB")
 4: eval(substitute(expr), data, enclos = parent.frame())
 5: eval(substitute(expr), data, enclos = parent.frame())
 6: with.default(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg,     random = randomArg, profile = NULL, silent = !verbose, DLL = "glmmTMB"))
 7: with(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg,     random = randomArg, profile = NULL, silent = !verbose, DLL = "glmmTMB"))
 8: fitTMB(TMBStruc)
 9: glmmTMB(NCalls ~ (FT + ArrivalTime) * SexParent + offset(log(BroodSize)) +     (1 | Nest), data = Owls, ziformula = ~1, family = poisson)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

```

Here is my session info:

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS/LAPACK: /u/local/compilers/intel/17.0.1/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] ggplot2_2.2.1   bbmle_1.0.20    glmmTMB_0.2.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17      lattice_0.20-35   MASS_7.3-47       plyr_1.8.4       
 [5] grid_3.4.2        nlme_3.1-131      gtable_0.2.0      scales_0.5.0     
 [9] pillar_1.1.0      rlang_0.2.1       lazyeval_0.2.1    minqa_1.2.4      
[13] nloptr_1.0.4      Matrix_1.2-14     splines_3.4.2     lme4_1.1-17      
[17] TMB_1.7.14        munsell_0.4.3     numDeriv_2016.8-1 compiler_3.4.2   
[21] colorspace_1.3-2  tibble_1.4.2     

```

The same problem occurs with R version 3.5.0, the same commands seem to work on R installed on my macbook.

Any idea of where the problem could be?

Thanks,

RD

**Comment by bbolker** [comment] 2018-07-10 19:12
can you successfully run any of the TMB examples, e.g.

```
library(TMB)
runExample("randomregression")
``` 

?

**Comment by rdauria** [comment] 2018-07-10 20:48
Actually not, this is what I get (I am also including the results from recompilation):

```
> install.packages("TMB",type="source")
Installing package into ‘/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.cnr.berkeley.edu/src/contrib/TMB_1.7.14.tar.gz'
Content type 'application/x-gzip' length 606414 bytes (592 KB)
==================================================
downloaded 592 KB

* installing *source* package ‘TMB’ ...
** package ‘TMB’ successfully unpacked and MD5 sums checked
** libs
/u/local/compilers/gcc/4.9.3/bin/gcc -std=gnu99 -I/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/include -DNDEBUG  -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include" -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/include" -I/u/local/compilers/gcc/4.9.3/include -I/u/local/apps/zlib/1.2.8/gcc-4.4.7/include -I/u/local/apps/bzip2/1.0.6/include -I/u/local/apps/xz/5.2.2/include -I/u/local/apps/pcre/8.39/include -I/u/local/apps/curl/7.49.1/include -I/include   -fpic  -O3  -m64 -fopenmp -fPIC  -c external_metis.c -o external_metis.o
/u/local/compilers/gcc/4.9.3/bin/gcc -std=gnu99 -I/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/include -DNDEBUG  -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include" -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/include" -I/u/local/compilers/gcc/4.9.3/include -I/u/local/apps/zlib/1.2.8/gcc-4.4.7/include -I/u/local/apps/bzip2/1.0.6/include -I/u/local/apps/xz/5.2.2/include -I/u/local/apps/pcre/8.39/include -I/u/local/apps/curl/7.49.1/include -I/include   -fpic  -O3  -m64 -fopenmp -fPIC  -c init.c -o init.o
/u/local/compilers/gcc/4.9.3/bin/gcc -std=gnu99 -I/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/include -DNDEBUG  -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include" -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/include" -I/u/local/compilers/gcc/4.9.3/include -I/u/local/apps/zlib/1.2.8/gcc-4.4.7/include -I/u/local/apps/bzip2/1.0.6/include -I/u/local/apps/xz/5.2.2/include -I/u/local/apps/pcre/8.39/include -I/u/local/apps/curl/7.49.1/include -I/include   -fpic  -O3  -m64 -fopenmp -fPIC  -c local_stubs.c -o local_stubs.o
/u/local/compilers/gcc/4.9.3/bin/gcc -std=gnu99 -I/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/include -DNDEBUG  -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include" -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/include" -I/u/local/compilers/gcc/4.9.3/include -I/u/local/apps/zlib/1.2.8/gcc-4.4.7/include -I/u/local/apps/bzip2/1.0.6/include -I/u/local/apps/xz/5.2.2/include -I/u/local/apps/pcre/8.39/include -I/u/local/apps/curl/7.49.1/include -I/include   -fpic  -O3  -m64 -fopenmp -fPIC  -c solve_subset.c -o solve_subset.o
/u/local/compilers/gcc/4.9.3/bin/gcc -std=gnu99 -I/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/include -DNDEBUG  -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include" -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/include" -I/u/local/compilers/gcc/4.9.3/include -I/u/local/apps/zlib/1.2.8/gcc-4.4.7/include -I/u/local/apps/bzip2/1.0.6/include -I/u/local/apps/xz/5.2.2/include -I/u/local/apps/pcre/8.39/include -I/u/local/apps/curl/7.49.1/include -I/include   -fpic  -O3  -m64 -fopenmp -fPIC  -c utils.c -o utils.o
/u/local/compilers/gcc/4.9.3/bin/gcc -std=gnu99 -shared -L/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/lib -L/u/local/compilers/gcc/4.9.3/lib -L/u/local/apps/zlib/1.2.8/gcc-4.4.7/lib -L/u/local/apps/bzip2/1.0.6/lib -L/u/local/apps/xz/5.2.2/lib -L/u/local/apps/pcre/8.39/lib -L/u/local/apps/curl/7.49.1/lib -o TMB.so external_metis.o init.o local_stubs.o solve_subset.o utils.o -L/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/lib -lRlapack -L/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/lib -lRblas -lgfortran -lm -lquadmath /u/local/compilers/gcc/4.9.3/lib/libgfortran.a /u/local/compilers/gcc/4.9.3/lib/libquadmath.a -L/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/lib -lR
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgfortran.so when searching for -lgfortran
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgfortran.a when searching for -lgfortran
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libquadmath.so when searching for -lquadmath
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libquadmath.a when searching for -lquadmath
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgcc_s.so when searching for -lgcc_s
installing to /u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/TMB/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Building example simple 
/u/local/compilers/gcc/4.9.3/bin/g++  -I/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/include -DNDEBUG -I/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/TMB/include -I/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple  -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/Matrix/include" -I"/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/include" -I/u/local/compilers/gcc/4.9.3/include -I/u/local/apps/zlib/1.2.8/gcc-4.4.7/include -I/u/local/apps/bzip2/1.0.6/include -I/u/local/apps/xz/5.2.2/include -I/u/local/apps/pcre/8.39/include -I/u/local/apps/curl/7.49.1/include -I/include   -fpic  -m64 -fopenmp -O3 -fPIC  -c simple.cpp -o simple.o
/u/local/compilers/gcc/4.9.3/bin/g++ -shared -L/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/lib -L/u/local/compilers/gcc/4.9.3/lib -L/u/local/apps/zlib/1.2.8/gcc-4.4.7/lib -L/u/local/apps/bzip2/1.0.6/lib -L/u/local/apps/xz/5.2.2/lib -L/u/local/apps/pcre/8.39/lib -L/u/local/apps/curl/7.49.1/lib -o simple.so simple.o -L/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/lib -lR
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgcc_s.so when searching for -lgcc_s
Build time 36.413 seconds

* DONE (TMB)

The downloaded source packages are in
	‘/work/tmp/RtmpuvqPgJ/downloaded_packages’
> library(TMB)
> runExample("randomregression")
Building example randomregression 
/u/local/compilers/gcc/4.9.3/bin/g++  -I/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/include -DNDEBUG -I/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/TMB/include -I/u/home/systems/dauria/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_randomregression  -DTMB_LIB_INIT=R_init_randomregression   -I/u/local/compilers/gcc/4.9.3/include -I/u/local/apps/zlib/1.2.8/gcc-4.4.7/include -I/u/local/apps/bzip2/1.0.6/include -I/u/local/apps/xz/5.2.2/include -I/u/local/apps/pcre/8.39/include -I/u/local/apps/curl/7.49.1/include -I/include   -fpic  -m64 -fopenmp -O3 -fPIC  -c randomregression.cpp -o randomregression.o
/u/local/compilers/gcc/4.9.3/bin/g++ -shared -L/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/lib -L/u/local/compilers/gcc/4.9.3/lib -L/u/local/apps/zlib/1.2.8/gcc-4.4.7/lib -L/u/local/apps/bzip2/1.0.6/lib -L/u/local/apps/xz/5.2.2/lib -L/u/local/apps/pcre/8.39/lib -L/u/local/apps/curl/7.49.1/lib -o randomregression.so randomregression.o -L/u/local/apps/R/3.4.2/gcc-4.9.3_MKL-2017.0/lib64/R/lib -lR
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgcc_s.so when searching for -lgcc_s
Build time 31.518 seconds

Running example randomregression 

> require(TMB)

> dyn.load(dynlib("randomregression"))

> ## Simulate random regression
> set.seed(123)

> n <- 100

> ng <- 10

> f <- gl(ng, n/ng)

> t <- rnorm(n, mean=2, sd=5)

> a <- rnorm(ng, mean=3, sd=4)

> b <- rnorm(ng, mean=8, sd=7)

> x <- a[f] * t + b[f] + rnorm(n, mean=0, sd=1)

> if(FALSE){
+   library(lattice); xyplot(x ~ t, group = f, type="l")
+ }

> ## Construct AD function object
> data <- list(group=f, x=x, t=t)

> parameters <- list(
+                    a = rep(1, nlevels(f)),
+                    b = rep(1, nlevels(f)),
+                    mu = rep(1, 2),
+ .... [TRUNCATED] 

> obj <- MakeADFun(data = data,
+                  parameters = parameters,
+                  random = c("a", "b"),
+                  DLL = "randomr ..." ... [TRUNCATED] 
0 regions found.
Using 8 threads
TMB has received an error from Eigen. The following condition was not met:
index >= 0 && index < size()
Please check your matrix-vector bounds etc., or run your program through a debugger.
Aborted (core dumped)

```

**Comment by bbolker** [comment] 2018-07-10 20:54
This seems useful (also suggests that this issue might want to get migrated to the TMB issues lists, but it can stay here for now ...)  I can't help much more, @kaskr or someone else who knows what they're doing will have to step in ... Do you have an option of using a different/more recent compiler? (The [TMB README](https://github.com/kaskr/adcomp) has a few notes on compilers, but they don't seem relevant here ...)

**Comment by kaskr** [comment] 2018-07-10 21:03
Duplicate of #232.

**Comment by bbolker** [comment] 2018-07-10 21:19
Closing this; @rdauria, if this turns out to differ in some significant way from #232 , please either add a comment there or open a new issue at https://github.com/glmmTMB/glmmTMB/issues , as seems appropriate.

**Closed by bbolker** 2018-07-10 21:20 UTC
