### ISSUE TITLE
Anova error for zi component

### ISSUE THREAD

**Issue by ldharder** [glmmTMB/glmmTMB#673] opened 2021-03-06 17:35 UTC
Hi,

I have encountered a problem with the `Anova` function that may signal a code issue. (Note the version of `glmmTMB` that I am using was provided to me by Ben Bolker in response to issue #642.)

The analysis involves rather complex influences on a count variable, `abun` (the number of bees observed during 10-minute observations periods), recorded for two bee species once every other day for >2 months (i.e., repeated measures) on 22 randomly selected plants distributed among four different habitats.  Fixed effects include two factors (bee species and habitat) and four covariates that varied among sampling days (`ltflw`, `ltterr1`, `ltdahl1` and `prob`).  Bees of a given species were not observed sufficiently often that the distribution of `abun` is over-dispersed compared to a negative binomial distribution, promoting analysis with a zero-inflation model.  In the analysis, I associate random among-plant variation with the `zi` component and the temporal auto-correlation resulting from repeated measurement of bee species on individual plants with the conditional component.  The code is as follows:

```r
options(contrasts = c("contr.sum","contr.poly"))
abund$species <- as.factor(abund$species)
abund$habitat <- as.factor(abund$habitat)
abund$julday <- numFactor(abund$julday)

joint <- glmmTMB(abun ~ species + habitat + ltflw + ltterr1 + ltdahl1 + species:habitat + species:ltterr1 + species:ltdahl1 + prob + species:prob + exp(julday + 0|species:Plantf),
 zi = ~ species + habitat + ltflw + ltdahl1 + species:ltdahl1 + prob + species:prob + (1 | Plantf),
 family=nbinom2, data=abund)

summary(joint)
Anova(joint, type=3, component="cond")
Anova(joint, type=3, component="zi")
```

The model fits without warnings and the model summary indicates reasonable estimates and standard errors for the partial regression coefficients.   The `Anova` for the conditional component produces reasonable results, but that for the `zi` component returns the message 

> Error in I.p[subs, , drop = FALSE] : subscript out of bounds

Using a Poisson distribution generates the same behavior.  The initial analysis does not converge for the `nbinom1` distribution (non-positive-definite Hessian matrix).

If the `species:habitat` interaction is added to the zi component, Anova for the zi component works without complaint.  However, for that model the summary for the `zi` component estimates extremely large SEs for partial regression coefficients associated with species, habitat and their interaction.  I interpret this as a consequence of collinearity; hence the exclusion of the species:habitat interaction from the `zi` component in the model described above.

Does this behavior signal a `glmmTMB` problem (over and above the challenging data)?

Thanks for your assistance.

PS. The data are available from [Joint abundance extract.xlsx](https://github.com/glmmTMB/glmmTMB/files/6095702/Joint.abundance.extract.xlsx)

**Comment by bbolker** [comment] 2021-03-07 03:36
sure looks like a bug, may be a duplicate of an issue we haven't handled yet ... ? Will take a look.

**Comment by bbolker** [comment] 2021-03-07 03:53
looks like it might be a one-line fix. See the `zi_Anova_fix` branch. (Still trying to come up with a smaller reproducible example for testing ...)

**Comment by ldharder** [comment] 2021-03-07 17:06
Thanks for taking this on.

The version installed by the zi_Anova_fix branch runs without the error mentioned above, which is great and much appreciated.

My understanding is that the zi_Anova_fix branch is version 1.0.2.900.  If so, it does not include some improvements that are available in the current version (1.4.2).  Is that correct?  If so, is a best-of-both-worlds version possible?

Thanks again.

**Comment by bbolker** [comment] 2021-03-07 18:40
One of us is confused. Where are you getting a version 1.4.2 from? Version 1.0.2.1 is on CRAN. The current version will be bumped to (presumably) 1.0.3 when it is submitted to CRAN.  The `zi_Anova_fix` branch will be merged into master soon (as soon as I, or someone else, finds some time to write some tests for the fix: your reproducible example was very useful, but it a little unwieldy for including in the test suite ... as I mentioned above, I'm still trying to come up with a *minimal* example that displays the problem for testing purposes).  The `zi_Anova_fix` branch is missing a *few* things from the master branch (see `Insights/Network`):

![Screenshot from 2021-03-07 13-36-57](https://user-images.githubusercontent.com/78918/110250674-84f6b400-7f4a-11eb-9545-4e217650cd3b.png)

but not very much. It would be possible to merge master into `zi_Anova_fix`, but it doesn't seem worthwhile since it will be merged into master soon ...

**Comment by ldharder** [comment] 2021-03-07 18:46
Sorry for the confusion (a misreading on my part).

Thanks for the status explanation, and again for the solution.

**Closed** 2021-03-15 12:45 UTC
