### ISSUE TITLE
0.2.3 release-critical/wishlist issues

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#382] opened 2018-09-01 12:37 UTC
This can't go on CRAN until after their hiatus (which is something like September 1-8). We are OK for our two-month delay between releases (last version went up on 3 July).

## critical
- <s>covstruct fix
    - fixed, on a branch; depends on unreleased lme4 version</s>
- ~remove MCMCpack dependency~

## wishlist
- sort out scaled variances
- ~merge parboot branch~
    - ~in particular, need to sort out behaviour with regard to binomial responses (when `simulate()` returns a two-column matrix)~

**Comment by strengejacke** [comment] 2018-10-04 09:16
May I add something to the wishlist, probably not for the next release, but in general: implement the `re.form`-argument in `predict()`. :-)

**Comment by mebrooks** [comment] 2018-10-11 11:55
**wishlist**: Tweedie variance #293

I'll reduce the test of the trunc compois #397

**Comment by mebrooks** [comment] 2018-11-29 12:42
I finally have a little time to look at this again and I'm hoping to submit the new version to CRAN soon (in less than a week unless someone needs time). Is anyone feeling motivated to tackle any of these wishlist items?

 @bbolker partially addressed @strengejacke 's issue with [this commit](https://github.com/glmmTMB/glmmTMB/commit/68b694df5dfdd1c9deca56dfaf5e462a53437cd4). @strengejacke , does that do what you need?

Does the parboot branch need more testing before it can be merged? What if we only allow one type of binomial response? Does it currently work for non-binomial data? That amount of functionality seems worth adding.

**Comment by strengejacke** [comment] 2018-11-29 12:47
> @bbolker partially addressed @strengejacke 's issue with this commit. @strengejacke , does that do what you need?

It's no urgent need, but it would be nice to have predictioned conditioned on random effects working, in general. As far as I can see, @bbolker 's commit just tackled the docs, to make more explicit _that_ `re.form` currently is not implemented? So, "no, it does not what I need", but there's no urgent need in general from my side. :-)

**Comment by mebrooks** [comment] 2018-11-29 12:52
Ok, so you need something other than population-level predictions.

**Comment by strengejacke** [comment] 2018-11-29 13:49
Sorry, I haven't seen that not only population-level predictions work with setting the re-term to `NA` in `newdata` (which is sufficient for me), but you can also make predictions for different levels of the re-term. So this indeed covers my personal needs! I though I needed to change the `re.form`-argument to do that, but for **glmmTMB** this is obviously not necessary... 

You can remove my point from the wishlist...

**Comment by bbolker** [comment] 2018-11-29 15:46
As far as I can recall, parboot is working *except* for binomial (and beta-binomial) models; there's some mess/confusion to sort out with making sure that the values that `simulate()` returns can be plugged back in as a response variable.  

Still need to sort out some documentation/checking/exporting stuff.  Would be lovely to actually fix this before release, but it could probably go out without being finished.

**Comment by mebrooks** [comment] 2018-12-05 14:18
wishlist: simulation method for `family = genpois`

**Comment by florianhartig** [comment] 2018-12-16 10:59
Hi guys, could I be a pain and put the re.form option back on the list? 

The issue I'm facing for DHARMa is that when plotting residuals against predicted, a spurious pattern occurs when including the random effects in the predictions. I am currently warning the users about this, and advice them to recalculate residuals, setting grouping variables to NA by hand, but this is not a very satisfying solution (see https://github.com/florianhartig/DHARMa/issues/16 ).

I have pondered creating a function in DHARMa that extracts the REs and the model.frame, matches names, and sets the grouping variables to NA, but that seems very hacky. 

I understand that implementing the entire formula interface for re.form is a bit of work, but as an interim solution, couldn't you at least implement re.form ~ 0? What I imagine is that you just check if re.form ~ 0, and if so, return the plain population-level predictions, and throw a not implemented error for all other inputs to re.form?

**Comment by mebrooks** [comment] 2018-12-18 17:41
I doubt we can get to the `re.form` option before CRAN's hiatus that begins Dec 21st. I'm thinking we should make that a priority for the next release. I'm thinking that it might be good enough to submit a new version now. It would be nice to speed up the vignettes among other things, but I don't have time to work on it now. Should I go through the steps to submit to CRAN, or are there any other things in the works?

**Comment by bbolker** [comment] 2018-12-18 17:50
I agree that we're under a time crunch, and I know from past experience that hurrying to make changes right before a release, no matter how harmless they seem to be,  can be dangerous.  It's not entirely trivial to "just" return the plain population-level predictions ... if I were the maintainer I would accept a PR within the next 24 hours, but otherwise I'd get busy working through the CRAN submission checklist (test with `--as-cran` locally, test on win-builder, test reverse dependencies ...)

**Comment by mebrooks** [comment] 2018-12-18 19:05
I checked the reverse dependencies using [the revdepcheck package](https://github.com/r-lib/revdepcheck) and all 8 seem OK. 

Now I sent it to Winbuilder, both release and devel.

**Comment by mebrooks** [comment] 2018-12-18 19:31
There were 2 [errors on Winbuilder](https://win-builder.r-project.org/KHv4gO32fMiB/00check.log)
```
 == Failed ======================================================================
  -- 1. Error: various binomial response types work (@test-methods.R#325)  -------
  object 'ddb' not found
  1: fixef(lme4::refit(f1b, s1[[1]])) at testthat/test-methods.R:325
  2: lme4::refit(f1b, s1[[1]])
  3: refit.glmmTMB(f1b, s1[[1]])
  4: eval(cc$data)
  5: eval(cc$data)
  
  -- 2. Failure: cov_struct_order (@test-varstruc.R#124)  ------------------------
  unname(fit1$fit$par) not equal to c(...).
  2/6 mismatches (average diff: 0.0614)
  [2] -4.1 - -4.22 == 0.12038
  [6]  1.0 -  1.00 == 0.00235
```
It's late here and I'll be on airplanes for most of the day tomorrow, so I probably can't fix this until Thursday. If anyone else has time, then help would be very much appreciated.

**Comment by bbolker** [comment] 2018-12-18 19:59
I'll try.  I think I have a fix for the first one  and will try to figure out what's going on with the second ....

**Comment by bbolker** [comment] 2018-12-18 20:57
Are you talking about something like [this thread](https://stat.ethz.ch/pipermail/r-package-devel/2018q2/002727.html)?  I'm a little surprised if that's the issue (the potential for variation in eigenvectors returned is well known, I'm mildly skeptical that it would influence generic uses of `mvrnorm` very much) -- but it's easy to test -- either sample from `mvrnorm()` once and save the values for use across platforms, or use `mvtnorm::mvtnorm` which is said (in the thread) to be more stable -- the former has fewer dependency issues (although maybe we already suggest `mvtnorm` ?)

**Comment by bbolker** [comment] 2018-12-18 22:48
We're down to three NOTEs on Win-builder: [check dir](https://win-builder.r-project.org/0TS5tubL73SP): 

- one on "new maintainer" (I hacked the DESCRIPTION file temporarily so I could get it to send me the e-mail)
- one on some junk files I had left lying around in my personal top-level directory
- one on large installed size (unavoidable, on R-release only)

... so I think we're good to go, barring any last-minute screwups (which I seem to be prone to). I will run one more `R CMD build; R CMD check --as-cran` at my end and report if anything bad happens ...

Before closing this we should make sure that any issues discussed above and not resolved (variance scaling, `re.form`, warning about `predict` with `type="response"` and `se.fit=TRUE` etc. ...) are at least still open in other issues, and perhaps copied over to a "2.4.0 release" issue ...

**Comment by bbolker** [comment] 2018-12-19 01:36
I may have some test failures on MacOS.  Stay tuned ...

**Comment by bbolker** [comment] 2018-12-19 16:14
@mebrooks : as far as I can tell we're ready to go for CRAN submission.

**Comment by mebrooks** [comment] 2018-12-21 00:52
Great! I'm working on the checks now.

**Comment by mebrooks** [comment] 2018-12-21 02:33
Ok. I submitted it. I guess I'll hear back tomorrow. My only concerns are that (1) a couple of linux systems [were giving a warning](https://cran.r-project.org/web/checks/check_results_glmmTMB.html) on the old version and I'm not sure we did anything about them  and (2) we didn't speed up the vignettes as CRAN asked in the past.

**Comment by bbolker** [comment] 2018-12-21 03:30
Looks like we did do something about the warning: https://github.com/glmmTMB/glmmTMB/commit/cc18ef2b6b5aa728595cb37558beefc81776e8dd

**Comment by strengejacke** [comment] 2018-12-21 10:50
> we didn't speed up the vignettes as CRAN asked in the past.

I'm using a workaround I found from the Stan-team, to compile "long-running" vignettes before ssubmitting to CRAN, see example (YAML-header) here: https://github.com/strengejacke/sjPlot/blob/master/vignettes/tab_bayes.Rmd

I'm not sure whether this only works with rmarkdown-vignettes and/or roxygene-package only.

Basically, this line
```
params:
    EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
```
checks whether you're compiling the vignette on CRAN or on your own computer and sets `EVAL` accordingly. Then, the knitr-option `eval = if (isTRUE(exists("params"))) params$EVAL else FALSE` checks whether to evaluate the vignette or not (i.e. whether to run code or not).

Now the steps are as following:

1) In RStudio, run the _Document_-command from the _Build_-pane (ctrl-shift-D). Make sure that under _Configure Build Tools_, roxygen also creates the vignettes.
![vig1](https://user-images.githubusercontent.com/26301769/50338882-17e7d700-0516-11e9-8d7a-8424b17518f4.png)

2) Vignettes are compiles and stored in the `vignettes` folder. Now copy all these files to `inst/docs`.

3) Remove unnecessary files from `vignettes`-folder.

Now on CRAN, vignettes with the above script in the YAML-header will ignore these vignettes and simply copies the pre-compiles vignettes from `inst/docs`.

See also here:
https://github.com/paul-buerkner/brms/issues/158

**Comment by bbolker** [comment] 2018-12-21 16:06
Uh-oh: 

```
foghorn::cran_incoming("glmmTMB")
# A tibble: 2 x 4
  package version cran_folder time               
  <chr>   <chr>   <fct>       <dttm>             
1 glmmTMB 0.2.3.1 archive     2018-12-21 04:32:00
2 glmmTMB 0.2.3   archive     2018-12-21 03:30:00
```
> archive package rejected: it does not pass the checks cleanly and
          the problems are unlikely to be false positives

**Comment by mebrooks** [comment] 2018-12-21 16:09
I made a mistake with 0.2.3, which I quickly realized, so I sent an email and resubmitted as 0.2.3.1 with an apology. The automated system wouldn't let me use the same number again.

There's an [error and a warning](https://win-builder.r-project.org/incoming_pretest/glmmTMB_0.2.3.1_20181221_043236/Debian/00check.log) when running one of the examples on Debian. The error says 
```
Error in ref_grid(object, ...) : 
  Can't handle an object of class  “glmmTMB” 
 Use help("models", package = "emmeans") for information on supported models.
Calls: emmeans -> ref_grid
```

I think the warning is 
```
* checking re-building of vignette outputs ... [16s/16s] WARNING
```
but the error comes right after that, so they could be related.

**Comment by bbolker** [comment] 2018-12-21 16:17
Ugh.  Why did none of us ever see these when testing?

The vignette error appears to come from [these lines](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/utils_covstruct.R#L35-L36) : `sapply(y, is.numeric) || sapply(y, is.factor)` should use a single-bar rather than a double-bar.

**Comment by mebrooks** [comment] 2018-12-21 16:19
We also got this note about the timing, which could be related to building the vignettes
```
Flavor: r-devel-windows-ix86+x86_64
Check: Overall checktime, Result: NOTE
 Overall checktime 16 min > 10 min
```
It was Windows where we had problems with Vignette timing with the [last version](https://cran.r-project.org/web/checks/check_results_glmmTMB.html).

**Comment by bbolker** [comment] 2018-12-21 16:33
If CRAN weren't so crunched at the beginning of their blackout period, I would ask them for advice about the emmeans/ref_grid problem.  I don't understand why it succeeded on every other platform tested by CRAN, and on win-builder, and on Travis, and on every other platform we've tried it on locally, but failed on that one particular platform ...  I did admittedly do something slightly hokey in exporting: as described [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/emmeans.R#L3-L9), I couldn't find a way other than exporting the methods explicitly (e.g. `recover_data.glmmTMB`).  Something to do with the version of `emmeans` installed? (I note that the last version of `emmeans` on CRAN is *fairly* recent, 13 Dec 2018 ...)

**Comment by bbolker** [comment] 2018-12-21 17:01
Just confirming that this works fine on my machine with an up-to-date R-devel (only 2 NOTEs about package size and maintainer):

```
R CMD check --as-cran glmmTMB_0.2.3.tar.gz
* using log directory ‘/media/sf_Documents/Rpkgs/glmmTMB/glmmTMB.Rcheck’
* using R Under development (unstable) (2018-12-21 r75883)
* using platform: x86_64-pc-linux-gnu (64-bit)
...
```

When we revisit this in the New Year I think we should (1) check with CRAN maintainers about possibility of a false positive (at least tell them that we can't recreate this error anywhere ...) (2) try to speed up vignettes as necessary.

**Comment by bbolker** [comment] 2019-01-03 20:40
would you like to merge the [profile_fix branch](https://github.com/glmmTMB/glmmTMB/tree/profile_fix) before sending to CRAN?  There are some useful (minor) fixes; on the other hand, there's always the worry about "fixing" things at the last minute ...

**Comment by mebrooks** [comment] 2019-01-04 12:35
I'm slightly in favor of adding the profile_fix branch. I did all the checks (`make test` and `check --as-cran`) and it seems fine. Any other opinions? 
I'd really like to submit to CRAN today.

**Comment by mebrooks** [comment] 2019-01-04 12:44
We might still have the error with `emmeans -> ref_grid` on Debian, but maybe it went away. If the error is still there, I'm afraid it's beyond my understanding since I haven't kept up with all the new downstream features lately.

**Comment by bbolker** [comment] 2019-01-04 14:32
The `emmeans -> ref_grid` error is beyond my understanding, too, since we haven't been able to reproduce it locally. It would be useful if possible to make sure that the Debian check is using the same version of emmeans that we are (1.3.1 on my end ...)

The best thing to do (IMO) would be to send a separate query to CRAN maintainers, *before* we submit, asking them about that error on Debian (i.e. telling them that we got that error last time round but haven't been able to reproduce it on Travis/local Ubuntu/MacOS/win-builder/etc etc etc ...) and asking for suggestions.

The second-best thing to do (if you're in a hurry) would be to submit as is but include that information as a note along with the submission.

**Comment by bbolker** [comment] 2019-01-04 14:58
Passes `R CMD check --as-cran` for me on MacOS (3.5.2) and Ubuntu 16.04 (latest r-devel).  Maybe worth checking one more time on win-builder and re-doing reverse dependencies one more time, just to be paranoid?

**Comment by bbolker** [comment] 2019-01-06 16:40
Status ... ?

**Comment by mebrooks** [comment] 2019-01-07 15:12
All checks have passes and I emailed the maintainer of the ggstatsplot package about the error. So I'm going to submit to CRAN with a note about the error that only seems to occur on Debian.

**Comment by bbolker** [comment] 2019-01-07 15:13
Go for it!

**Comment by mebrooks** [comment] 2019-01-07 19:11
The package was rejected. It looks like the Debian error occured again, but I didn't get a human response to my comment. I guess they're very busy these days.

```
Dear maintainer,

package glmmTMB_0.2.3.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/glmmTMB_0.2.3_20190107_162304/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/glmmTMB_0.2.3_20190107_162304/Debian/00check.log>
Status: 1 ERROR, 1 WARNING, 1 NOTE

Last released version's CRAN status: WARN: 2, NOTE: 5, OK: 5
See: <https://CRAN.R-project.org/web/checks/check_results_glmmTMB.html>

CRAN Web: <https://cran.r-project.org/package=glmmTMB>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/glmmTMB_0.2.3_20190107_162304/>
The files will be removed after roughly 7 days.

*** Strong rev. depends ***: broom.mixed DHARMa sjPlot sjstats

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: NOTE
 Maintainer: 'Mollie Brooks <mollieebrooks@gmail.com>'

 Size of tarball: 7423043 bytes

Flavor: r-devel-linux-x86_64-debian-gcc
Check: examples, Result: ERROR
 Running examples in 'glmmTMB-Ex.R' failed
 The error most likely occurred in:

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Anova.glmmTMB
### Title: Downstream methods for glmmTMB objects
### Aliases: Anova.glmmTMB Effect.glmmTMB recover_data.glmmTMB
###   emm_basis.glmmTMB downstream_methods

### ** Examples

warp.lm <- glmmTMB(breaks ~ wool * tension, data = warpbreaks)
if (require(emmeans)) {
 +     emmeans (warp.lm, poly ~ tension | wool)
 + }
 Loading required package: emmeans
 Error in ref_grid(object, ...) : 
   Can't handle an object of class  'glmmTMB' 
  Use help("models", package = "emmeans") for information on supported models.
 Calls: emmeans -> ref_grid
 Execution halted

Flavor: r-devel-linux-x86_64-debian-gcc
Check: re-building of vignette outputs, Result: WARNING
 Error(s) in re-building vignettes:
   ...
 --- re-building 'covstruct.rmd' using rmarkdown

 Attaching package: 'TMB'

 The following object is masked from 'package:glmmTMB':

     tmbroot

 --- finished re-building 'covstruct.rmd'

 --- re-building 'mcmc.rmd' using rmarkdown
 --- finished re-building 'mcmc.rmd'

 --- re-building 'miscEx.rmd' using rmarkdown
 --- finished re-building 'miscEx.rmd'

 --- re-building 'model_evaluation.rmd' using rmarkdown
 Loading required package: carData
 lattice theme set by effectsTheme()
 See ?effectsTheme for details.
 Loading required package: mvtnorm
 Loading required package: survival
 Loading required package: TH.data
 Loading required package: MASS

 Attaching package: 'TH.data'

 The following object is masked from 'package:MASS':

     geyser


 Attaching package: 'multcomp'

 The following object is masked from 'package:emmeans':

     cld

 Note that, since v0.1.6.2, DHARMa includes support for glmmTMB, but there are still a few minor limitations associatd with this package. Please see https://github.com/florianhartig/DHARMa/issues/16 for details, in particular if you use this for production.
 Loading required package: ggplot2
 Quitting from lines 94-96 (model_evaluation.rmd) 
 Error: processing vignette 'model_evaluation.rmd' failed with diagnostics:
 subscript out of bounds
 --- failed re-building 'model_evaluation.rmd'

 --- re-building 'sim.rmd' using rmarkdown
 --- finished re-building 'sim.rmd'

 --- re-building 'troubleshooting.rmd' using rmarkdown
 --- finished re-building 'troubleshooting.rmd'

 --- re-building 'glmmTMB.Rnw' using knitr
 Loading required package: stats4
 Warning in qt((1 - level)/2, df) : NaNs produced
 --- finished re-building 'glmmTMB.Rnw'

 SUMMARY: processing the following file failed:
   'model_evaluation.rmd'

 Error: Vignette re-building failed.
 Execution halted
```

**Comment by bbolker** [comment] 2019-01-07 20:07
Let's ask for help on `r-package-devel`, as suggested

**Comment by mebrooks** [comment] 2019-01-08 10:36
Uwe Ligges suggested that I should "take a recent version of R-devel, check with the --as-cran flag and set the environment variable

`_R_CHECK_LENGTH_1_LOGIC2_="package:_R_CHECK_PACKAGE_NAME_,abort,verbose"`
"
I'm stuck on the step of installing R-devel, but I'll keep trying.

**Comment by bbolker** [comment] 2019-01-08 14:32
OK.  I also think I have a possible fix, from `r-package-devel`: see responses to https://stat.ethz.ch/pipermail/r-package-devel/2019q1/003329.html

**Comment by mebrooks** [comment] 2019-01-08 15:08
I finally got R-devel installed, but I can't reproduce the error.

**Comment by bbolker** [comment] 2019-01-08 15:19
even with the environment variable `R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV` set to `TRUE`?  

Admittedly, I wasn't able to reproduce the error either; I tried setting this variable on the master branch (which doesn't have the fix) and couldn't make the examples fail.  I have (I think?) fixed the issues on [this branch](https://github.com/glmmTMB/glmmTMB/tree/downstream_methods_fix), as instructed on R-package-devel ...

**Comment by mebrooks** [comment] 2019-01-08 15:36
I tried building and checking as cran with
```
_R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=TRUE
```
and got 
```
Quitting from lines 94-96 (model_evaluation.rmd) 
Error: processing vignette 'model_evaluation.rmd' failed with diagnostics:
subscript out of bounds
```

**Comment by bbolker** [comment] 2019-01-08 15:40
OK, great (I guess).  Was this with the 'downstream_metnods_fix' branch or with the master branch?

**Comment by mebrooks** [comment] 2019-01-08 15:40
I was able to submit it as version 0.2.3 yesterday. I believe the rule is that you just can't have multiples of the same number in the queue at the same time

**Comment by mebrooks** [comment] 2019-01-08 15:41
I've only tried the master branch so far.

**Comment by bbolker** [comment] 2019-01-08 15:43
OK.  

- How exactly did you set the environment variable? with `export R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV` or ... ? 
- was the vignette error the only one you got, or did you also get the failure in the emmeans example?

I haven't tried with --as-cran yet, will try ...

**Comment by mebrooks** [comment] 2019-01-08 15:49
I just did 
```
export _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=TRUE
R CMD build glmmTMB
```
and it failed while building.

**Comment by bbolker** [comment] 2019-01-08 15:51
Huh. OK, Try building it first (with the env variable unset or set to FALSE), then using `R CMD check --as-cran` with the env variable set to TRUE) ...

**Comment by bbolker** [comment] 2019-01-08 15:55
I still can't replicate any errors, but I hope you can (*and* show that they go away with the `downstream_methods_fix` branch ...)

**Comment by mebrooks** [comment] 2019-01-08 16:09
Now I was able to replicate the error (build, then export, then check) in the master branch. In the `downstream_methods_fix` branch I get a different error. 
```
* checking examples ... ERROR
Running examples in ‘glmmTMB-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: Anova.glmmTMB
> ### Title: Downstream methods for glmmTMB objects
> ### Aliases: Anova.glmmTMB Effect.glmmTMB recover_data.glmmTMB
> ###   emm_basis.glmmTMB downstream_methods
> 
> ### ** Examples
> 
> warp.lm <- glmmTMB(breaks ~ wool * tension, data = warpbreaks)
> if (require(emmeans)) {
+     emmeans (warp.lm, poly ~ tension | wool)
+ }
Loading required package: emmeans
$emmeans
wool = A:
 tension   emmean     SE df lower.CL upper.CL
 L       44.55555 3.4382 47 37.63879 51.47232
 M       24.00000 3.4382 47 17.08323 30.91676
 H       24.55556 3.4382 47 17.63879 31.47233

wool = B:
 tension   emmean     SE df lower.CL upper.CL
 L       28.22222 3.4382 47 21.30545 35.13899
 M       28.77778 3.4382 47 21.86101 35.69454
 H       18.77778 3.4382 47 11.86101 25.69454

Confidence level used: 0.95 

$contrasts
wool = A:
 contrast    estimate       SE df t.ratio p.value
 linear    -19.999995 4.862349 47  -4.113  0.0002
 quadratic  21.111119 8.421836 47   2.507  0.0157

wool = B:
 contrast    estimate       SE df t.ratio p.value
 linear     -9.444443 4.862349 47  -1.942  0.0581
 quadratic -10.555557 8.421836 47  -1.253  0.2163


> if (require(car)) {
+     Anova(warp.lm,type="III")
+ }
Loading required package: car
Loading required package: carData
Analysis of Deviance Table (Type III Wald chisquare tests)

Response: breaks
                Chisq Df Pr(>Chisq)    
(Intercept)  167.9351  1  < 2.2e-16 ***
wool          11.2839  1  0.0007818 ***
tension       23.2023  2  9.155e-06 ***
wool:tension   9.4254  2  0.0089805 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> if (require(effects)) {
+     plot(allEffects(warp.lm))
+ }
Loading required package: effects
lattice theme set by effectsTheme()
See ?effectsTheme for details.
Error in mod.matrix %*% scoef : 
  requires numeric/complex matrix/vector arguments
Calls: plot ... effect.default -> Effect -> Effect.default -> Effect -> Effect.lm
Execution halted
```

By the way, is 
```
export _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=TRUE
```
equivalent to 
```
export R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=TRUE
```
because I've been doing the version with an underscore as the first character.

**Comment by mebrooks** [comment] 2019-01-09 13:07
Well, I submitted to CRAN and there weren't any errors, so that's good news, but now they would like the tarball to be smaller than 5 MB. They pointed out that the new size is 7.4 MB and the old one was 1/10th of that.

I looked around and the file `inst/vignette_data/mcmc.rda` is 5.7 MB, but we created this to speed up the vignettes as CRAN requested. I see these analyses are very useful guides for the users, but I think in the future I would put complex analyses that require many external packages some place other than vignettes, like maybe the github page. Another solution could be to write the vignette in a sort-of fake way that doesn't actually depend on having the real data.

**Comment by mebrooks** [comment] 2019-01-09 15:56
@strengejacke yes, thank you for the suggestion. I used it on the troubleshooting and covstruct vignettes. By the way, I was using the command line `R CMD build glmmTMB` and it was putting the vignette html files in inst/doc of the tarball automatically, so I didn't need to do it manually, but maybe our setups are different. 

The MCMC vignette wasn't actually very slow even when running all the sampling (assuming that was included when we did the timing in #364), so I guess it makes sense to use the `eval=FALSE` trick for this vignette also.

**Comment by bbolker** [comment] 2019-01-09 16:02
I feel like I might be channeling @mmaechler here, but I like including as much as possible of the vignette construction and data in the package itself; that makes sure that the most checking happens automatically, and means that the package+examples are more self-contained. I'm working on reducing the size of the vignette data.

**Comment by mebrooks** [comment] 2019-01-09 16:06
I'm probably just grouchy because of my experience installing r-devel yesterday :)

**Comment by bbolker** [comment] 2019-01-09 16:14
Provided I didn't break anything, [this pull request](https://github.com/glmmTMB/glmmTMB/pull/435) should take care of it.  In fact, I had already written machinery to store & load the PNG of the trace plot generated, so we didn't actually need to be saving the `tmbstan` output (which was the only thing that made the stored file size blow up).

**Comment by bbolker** [comment] 2019-01-09 16:31
Should be OK now?  I went ahead and merged the PR ...

**Comment by mebrooks** [comment] 2019-01-10 13:05
I get the impression that it's ok to reuse the same version number (0.2.3) once I have a response from CRAN about whether or not they'll accept the submitted version. 

With a built tarball from the new master branch, it passes `R CMD check --as-cran` on my computer which should still be using R-devel. However, it has errors and a warning on win-builder's R-devel version.  Here's the [temporary link](https://win-builder.r-project.org/8UTb1f48u4xW/). 

```
Quitting from lines 23-36 (model_evaluation.rmd) 
Error: processing vignette 'model_evaluation.rmd' failed with diagnostics:
package 'ggplot2' 0.9.3 is loaded, but >= 2.2.1 is required by 'dotwhisker'
```


```
Quitting from lines 87-89 (mcmc.rmd) 
Error: processing vignette 'mcmc.rmd' failed with diagnostics:
`inherit` must be a R6ClassGenerator.
```

```
Loading required package: ggplot2
Warning in structure(NULL, class = "waiver") :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

**Comment by strengejacke** [comment] 2019-01-10 13:16
I had similar issues (and same error messages) for a package I submitted, and I have no clue why this happens (as it didn't happen a few days before, where I also use ggplot in the examples of another package). I simply removed that code from the examples, because it was not worth the effort finding out the source for this strange bug. Especially, since all examples worked perfectly during the last submission about 2-3 months ago, and I haven't noticed any major changes in ggplot or other packages. Maybe it's a temporary issue with the CRAN check systems?

**Comment by mmaechler** [comment] 2019-01-10 13:42
> With a built tarball from the new master branch, it passes `R CMD check --as-cran` on my computer which should still be using R-devel. However, it has errors and a warning on win-builder's R-devel version. Here's the [temporary link](https://win-builder.r-project.org/8UTb1f48u4xW/).
> 
> ```
> Quitting from lines 23-36 (model_evaluation.rmd) 
> Error: processing vignette 'model_evaluation.rmd' failed with diagnostics:
> package 'ggplot2' 0.9.3 is loaded, but >= 2.2.1 is required by 'dotwhisker'
> ```
 ...
So it accidentally gets a very old version of `ggplot2`.  That is certainly a glitch on the win-builder, and I think you should tell Uwe Ligges about it (or I can if you'd prefer).

The remaining errors/warnings are partly at least a consequence of using that antique version of `ggplot2`.

**Comment by mebrooks** [comment] 2019-01-10 13:46
Should we specify the version of ggplot2 in suggests?

@mmaechler that would be nice of you to tell Uwe Ligges about it. Thank you.

**Comment by mebrooks** [comment] 2019-01-11 10:08
It's passing all the checks now when I suggested ggplot >=2.2.1.  I'm going to double check the formula ordering issue one more time. @kaskr can you convince yourself again that it's fixed before I submit to CRAN?

**Comment by kaskr** [comment] 2019-01-11 10:59
@mebrooks Seems to me that it's working.

**Comment by mebrooks** [comment] 2019-01-11 15:43
I submitted the package again since I'm 99% sure that it's fine.

**Comment by bbolker** [comment] 2019-01-11 15:52
> Just to be absolutely sure...
> I went back to checking with the release version of R 3.5.2. I checked in the normal way, but then I also did
> 
> ```
> export _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=TRUE
> ```
> 
> before checking and the old `emmeans -> ref_grid` error came back. This is ok right? We're only expecting `_R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=TRUE` in the later release?

Honestly, I don't know. One of the items on my to-do list is to write back to `r-package-devel` and (1) thank folks there for help and (2) try to find out where these issues are documented (or request that documentation be added somewhere ...)

**Comment by mebrooks** [comment] 2019-01-11 18:30
It's on CRAN! https://cran.r-project.org/web/packages/glmmTMB/index.html

**Closed by mebrooks** 2019-01-11 18:30 UTC

**Comment by strengejacke** [comment] 2019-01-11 19:12
🥂

**Comment by bbolker** [comment] 2019-01-11 21:49
thanks, Mollie!
