### ISSUE TITLE
Covariance structuring with more complex time-series data

### ISSUE THREAD

**Issue by adcorso** [glmmTMB/glmmTMB#446] opened 2019-03-11 14:12 UTC
Hello, 
I'm running a zero-inflated, mixed-effects negative binomial model. My current format:
`mod1 = glmmTMB(count ~ a + b + offset(c) + (1| year), ziformula= ~a +d, data = dat, family = nbinom2 `

I have noticed signs of temporal autocorrelation between count and year, but I'm struggling to write a covariance structure using `ar1`. 

I understand the general structure is `struc(terms + 0 | group)` and year (as a factor) will be the "terms" variable. However, based on the vignette I'm unsure what to use as the grouping variable? Would it also be year?  

In addition, what does the `+ 0` represent in the formula? 

Thanks,
Andrew

**Comment by ShrewMaster** [comment] 2019-03-13 12:47
I have a similar issue to adcorso.

In my case I was using `lme()`, and found out that my model greatly improved by adding an AR-1 autocorrelation structure (as per AICc). This was the final formula:

`lme(body_mass ~ day * season * social, data = dawn2, random = ~ 1 | indiv, correlation = corAR1(form = ~ day))`

The problem is I also found the Gamma distribution fits this model better than the Gaussian distribution, and I can't model Gamma distributions in lme. So I was trying to replicate the AR-1 autocorrelation structure in glmmTMB, but so far I've had no success. I've seen in another [vignette](http://bbolker.github.io/mixedmodels-misc/notes/corr_braindump.html) that we should add tt-1 to the ar1 formula followed by the correlated group, something like this:

`glmmTMB(body_mass ~ day * season * social + (1 | indiv) + ar1(tt-1 | day), data = dawn2, family = gaussian(link = "identity"), REML = TRUE)`

But R just says "object 'tt' not found". What could be a possible solution? Or is it currently not possible to replicate the AR-1 autocorrelation structure found in lme (package nlme)?

**Comment by mebrooks** [comment] 2019-03-13 13:10
I see you're referring to two examples, `ar1(times + 0 | group)` from `vignette("covstruct")` and `ar1(tt-1|f)` from  [here](http://bbolker.github.io/mixedmodels-misc/notes/corr_braindump.html).

`-1` as in `tt-1` and `+0` as in `terms+0` both mean to omit the intercept.

In the example [here,](http://bbolker.github.io/mixedmodels-misc/notes/corr_braindump.html) to see where `tt` comes from, you have to make the data using the `simCor1` function defined [here](https://github.com/bbolker/mixedmodels-misc/blob/master/notes/lme4ord_poiscorsim.R).

In both vignettes, the grouping variable (`group` or `f`) is just a 1 in every row of data.  In one it's a factor and the other it's an integer, so try making one of those in your data.

I don't think these issues are bugs, so I'm going to close this issue. Further [questions](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions) could be addressed to the R-sig-mixed list.

**Closed by mebrooks** 2019-03-13 13:10 UTC

**Comment by adcorso** [comment] 2019-03-13 14:56
The column of 1's worked well, thank you so much for the quick response. I will post to the correct list next time, my apologies.
