### ISSUE TITLE
Spatial structure in hurdle glmmTMB

### ISSUE THREAD

**Issue by mairekirkland** [glmmTMB/glmmTMB#579] opened 2020-04-22 15:50 UTC
I am trying to use the glmmTMB package (version 1.1.0) to run a hurdle model that includes a spatial covariance structure. However, when I try to include spatial information in the zero-inflated part of the model I get an error. 

Here is a reproducible example with the error message that I receive: 

```
library(glmmTMB)

d <- data.frame(count = as.vector(Salamanders$count),
               mined = as.vector(Salamanders$mined),
               x = as.vector(row(Salamanders)),
               y = as.vector(col(Salamanders)))

d$pos <- numFactor(scale(d$x), scale(d$y))
d$ID <- factor(rep(1, nrow(d)))

m <- glmmTMB(count ~ mined + mat(pos + 0 | ID), 
               zi = ~., 
               family = truncated_poisson, data = d
)

```

"Error in Reduce(addForm0, list(...)) : object 'mined' not found”

**Comment by amynang** [comment] 2020-05-29 19:46
I have the same issue using an ar1 term to account for correlation between repeated samplings. Works fine for the conditional model but gives the error mentioned above when included in the ziformula. Looks like ziformula currently (1.0.1) does not accept correlation structures?

**Comment by amynang** [comment] 2020-06-15 20:11
@mairekirkland A quick workaround for this would be to run the two components as individual models. Your ziformula is a logistic regression.

**Comment by mebrooks** [comment] 2020-06-15 20:22
This seems like a bug. @kaskr do you have any idea what's happening?

**Comment by bbolker** [comment] 2020-06-15 20:31
I don't think this is @kaskr's fault.  It looks like it's in the formula-manipulation code somewhere around [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R#L683-L690).  I don't know exactly what's going on, but `noSpecials(subbars(f),delete=FALSE)` is returning an expression without a leading tilde, which surprises me/looks funny:  `mined + (pos + 0 + ID)`. Maybe it isn't properly designed for one-sided formulas?

**Comment by bbolker** [comment] 2020-06-15 22:06
[This branch](https://github.com/glmmTMB/glmmTMB/tree/nospecials_fix) fixes the proximal problem (`remotes::install_github("glmmTMB/glmmTMB/glmmTMB@nospecials_fix")` should install this version), but ... the proposed example crashes - I think out of memory (has to process two 644x644 dense matrices?) not sure if the problem is pathological/misspecified in some way or if there's another bug?

**Comment by bbolker** [comment] 2020-06-16 18:04
Can anyone shed any more light on whether there's an issue with the example? @amynang , does your model work now (the fix has been merged to the master branch, so installing with `remotes::install_github("glmmTMB/glmmTMB/glmmTMB")` should work)

**Comment by amynang** [comment] 2020-06-17 05:49
Yes, no errors, and everything looks fine.
Thanks a lot for the fix!

**Closed** 2020-06-18 14:57 UTC
